import type { Seed } from "./catalog-kinetic";

/**
 * Kinetic collection, second batch.
 *
 * Split from the first only to keep either file readable. Same rules: real
 * copy, one dominant colour per entry, and no two neighbours sharing a theme.
 */
export const SEEDS_TWO: Seed[] = [
  /* ───────────────────────────────────────────────────────── photography */
  { slug: "k-aperture-studio", name: "Aperture — Studio Photography", category: "photography", theme: "newsprint", recipe: 4, brand: "Aperture", eyebrow: "Studio and product photography", headline: "Lit properly, shot once", subhead: "Product and still life for brands that need three hundred images to look like one brand.", cta: "Request a quote", tags: ["light", "editorial", "product", "studio"], gallery: ["Glassware", "Cosmetics", "Editorial still life", "On white", "Textures", "The studio"], features: [["Consistent across runs", "Lighting logged per setup, so next season matches this one."], ["Same-week turnaround", "Shot Monday, retouched and delivered Friday."], ["Shot for the crop", "Every frame composed for square, portrait and banner at once."]], stats: [["300+", "Images per day"], ["1 week", "Turnaround"], ["0", "Outsourced retouching"]] },
  { slug: "k-northlight-wedding", name: "Northlight — Wedding Photography", category: "photography", theme: "kiln", recipe: 4, brand: "Northlight", eyebrow: "Documentary wedding photography", headline: "Nobody will ask you to pose", subhead: "Documentary coverage of the day as it happens, with two photographers and no group-shot list.", cta: "Check your date", tags: ["light", "warm", "wedding", "documentary"], gallery: ["Morning", "The ceremony", "Speeches", "Late"], features: [["Documentary only", "No posed portraits unless you ask. It is why the pictures look like you."], ["Two photographers", "Two rooms at once, all day, included."], ["All the frames", "Six to eight hundred edited images, no print upsell."]], stats: [["2", "Photographers"], ["800", "Images delivered"], ["0", "Print packages"]] },
  { slug: "k-terrain-landscape", name: "Terrain — Landscape Prints", category: "photography", theme: "thicket", recipe: 4, brand: "Terrain", eyebrow: "Fine art landscape", headline: "Printed the size it was shot for", subhead: "Large-format landscape work, editioned, printed in-house on cotton rag.", cta: "Browse editions", tags: ["light", "craft", "print", "fine-art"], gallery: ["Cairngorms", "Coastal", "Winter", "Moorland"], features: [["Large format", "Shot on 5x4 film. It is why they hold at two metres wide."], ["Editioned to 25", "Numbered, signed, and retired when the edition closes."], ["Printed here", "Cotton rag, pigment ink, by the photographer."]], stats: [["25", "Per edition"], ["5x4", "Format"], ["2m", "Maximum print"]] },

  /* ──────────────────────────────────────────────────────────── portfolio */
  { slug: "k-atlas-industrial", name: "Atlas — Industrial Design", category: "portfolio", theme: "brass", recipe: 4, brand: "Atlas", eyebrow: "Industrial design consultancy", headline: "Designed to be manufactured", subhead: "Product design that arrives with tolerances, a bill of materials and a factory that has quoted it.", cta: "See case studies", tags: ["dark", "industrial", "product", "b2b"], gallery: ["Housing", "Tooling", "Assembly", "Prototypes"], features: [["Manufacturability from day one", "Every concept costed for tooling before it is presented."], ["Prototyped in-house", "Three printers and a small machine shop."], ["Factory relationships", "We take you to people we have shipped with."]], stats: [["64", "Products shipped"], ["3", "Printers"], ["16yr", "Practising"]] },
  { slug: "k-cinder-interior", name: "Cinder — Interior Architecture", category: "portfolio", theme: "cellar", recipe: 4, brand: "Cinder", eyebrow: "Interior architecture", headline: "Rooms that work before they are beautiful", subhead: "Interior architecture for restaurants and workplaces, where circulation matters more than mood boards.", cta: "See projects", tags: ["light", "luxury", "interior", "serif"], gallery: ["Dining room", "Workplace", "Detail", "Joinery"], features: [["Circulation first", "How people move through a room decides everything else."], ["Acoustics designed in", "Not treated afterwards with panels nobody wanted."], ["Drawn to build", "Full construction packages, not mood boards."]], stats: [["41", "Projects"], ["12yr", "Practice"], ["4", "Architects"]] },

  /* ───────────────────────────────────────────────────────────────── saas */
  { slug: "k-parcel-logistics", name: "Parcel — Logistics", category: "saas", theme: "hazard", recipe: 3, brand: "Parcel", eyebrow: "Delivery operations", headline: "Know where every van is, honestly", subhead: "Route planning and live tracking for fleets between ten and five hundred vehicles.", cta: "Book a demo", cta2: "See pricing", tags: ["dark", "bold", "logistics", "b2b"], words: ["Routing", "Live ETA", "Proof of delivery"], features: [["Routes that account for reality", "Traffic, loading time and the driver who knows a shortcut."], ["ETAs customers believe", "Updated live, accurate to eight minutes."], ["Proof of delivery", "Photograph, signature and location, attached to the order."]], stats: [["8 min", "ETA accuracy"], ["22%", "Fewer miles"], ["500", "Max fleet"], ["1,100", "Fleets"]] },
  { slug: "k-roster-scheduling", name: "Roster — Shift Scheduling", category: "saas", theme: "lagoon", recipe: 3, brand: "Roster", eyebrow: "Shift scheduling", headline: "Publish the rota two weeks out", subhead: "Scheduling for hospitality and retail that respects availability, contracts and the law.", cta: "Start free", cta2: "See features", tags: ["dark", "service", "scheduling", "b2b"], words: ["Availability", "Compliance", "Swaps"], features: [["Availability respected", "Nobody is scheduled into a shift they said they could not work."], ["Compliance checked", "Rest periods and hour caps enforced before you can publish."], ["Swaps without you", "Staff arrange cover; you approve or ignore."]], stats: [["2 weeks", "Published ahead"], ["91%", "Filled first time"], ["0", "Compliance breaches"], ["4,200", "Sites"]] },

  /* ─────────────────────────────────────────────────────────────── business */
  { slug: "k-beacon-charity", name: "Beacon — Charity", category: "business", theme: "thicket", recipe: 5, brand: "Beacon", eyebrow: "Registered charity", headline: "Eighty-four pence in the pound", subhead: "Where the money goes, published quarterly, with the overhead stated plainly rather than buried.", cta: "Donate", tags: ["light", "charity", "trust", "warm"], features: [["Published accounts", "Quarterly, in full, including salaries."], ["84p in the pound", "Direct to programmes. The other sixteen keeps the lights on."], ["Local delivery", "Every programme run by people who live there."]], steps: [["Give", "Monthly or once. Both matter; monthly matters more."], ["See it spent", "Quarterly report, by programme, by pound."], ["Visit", "We run open days twice a year."]], stats: [["84p", "To programmes"], ["4", "Reports a year"], ["1971", "Founded"]] },
  { slug: "k-forge-manufacturing", name: "Forge — Contract Manufacturing", category: "business", theme: "detonate", recipe: 3, brand: "Forge Works", eyebrow: "Contract manufacturing", headline: "Small runs, taken seriously", subhead: "Metal fabrication from fifty units, quoted in two days, with tolerances we will actually hold.", cta: "Send a drawing", cta2: "Capabilities", tags: ["dark", "bold", "manufacturing", "industrial"], words: ["50 unit minimum", "2-day quotes", "Certified"], features: [["Fifty-unit minimum", "Most shops start at a thousand. Prototyping needs somewhere to go."], ["Quoted in two days", "From a STEP file, with the assumptions written down."], ["Tolerance stated", "Measured and certified per batch, not per year."]], stats: [["50", "Minimum run"], ["48h", "Quote"], ["31yr", "Trading"], ["4", "Machines"]] },
  { slug: "k-outpost-workspace", name: "Outpost — Workspace", category: "business", theme: "voltage", recipe: 5, brand: "Outpost", eyebrow: "Workspace", headline: "Desks, not a lifestyle", subhead: "A quiet workspace with fast internet, real chairs and nobody organising a networking breakfast.", cta: "Book a tour", tags: ["dark", "bold", "workspace", "local"], features: [["Actually quiet", "Phone booths, and a rule about calls at desks that is enforced."], ["Chairs that cost money", "Eight hours a day in a bad one is a health issue."], ["No events", "If you want networking there are eleven other places."]], steps: [["Tour", "Twenty minutes, any weekday."], ["Day pass", "Try it properly before committing."], ["Monthly", "Rolling. Cancel with a month's notice."]], stats: [["1Gb", "Symmetric"], ["0", "Networking events"], ["40", "Desks"]] },

  /* ─────────────────────────────────────────────────────────────── creative */
  { slug: "k-lumen-lighting", name: "Lumen — Lighting Design", category: "creative", theme: "siren", recipe: 4, brand: "Lumen", eyebrow: "Architectural lighting", headline: "You should never see the fitting", subhead: "Lighting design for galleries, restaurants and homes, where the source stays hidden and the room works.", cta: "Discuss a project", tags: ["dark", "bold", "lighting", "design"], gallery: ["Gallery", "Restaurant", "Residential", "Facade"], features: [["Hidden sources", "If you can see the fitting from a seat, it is in the wrong place."], ["Modelled first", "Every scheme simulated before a single fitting is bought."], ["Controls that make sense", "Four scenes, labelled in words, on one plate."]], stats: [["4", "Scenes per room"], ["0", "Visible sources"], ["90+", "Colour rendering"]] },
  { slug: "k-anvil-typefoundry", name: "Anvil — Type Foundry", category: "creative", theme: "newsprint", recipe: 1, brand: "Anvil Type", eyebrow: "Independent type foundry", headline: "Typefaces drawn, not generated", subhead: "A small foundry releasing two families a year, each with the language coverage actually finished.", cta: "Browse typefaces", tags: ["light", "typography", "foundry", "editorial"], gallery: ["Specimen", "Weights", "Cyrillic", "In use"], features: [["Two families a year", "Finishing takes eighteen months and we would rather it were right."], ["Coverage completed", "Latin Extended, Cyrillic and Greek in every weight, not just regular."], ["Licences you can read", "One page. Web, desktop and app included by default."]], stats: [["2", "Families a year"], ["9", "Weights each"], ["1", "Page licence"]] },
  { slug: "k-cobalt-packaging", name: "Cobalt — Packaging Design", category: "creative", theme: "ultramarine", recipe: 1, brand: "Cobalt", eyebrow: "Packaging design", headline: "It has to survive the shelf", subhead: "Packaging designed to be recognised at three metres and read at thirty centimetres.", cta: "See work", tags: ["light", "bold", "packaging", "design"], gallery: ["Range", "Structure", "On shelf", "Detail"], features: [["Tested on shelf", "Printed, placed and photographed among competitors before sign-off."], ["Structure and surface", "We design the box as well as what is printed on it."], ["Production ready", "Dielines, separations and a printer who has already quoted it."]], stats: [["3m", "Recognition distance"], ["64", "Ranges"], ["9yr", "Studio"]] },

  /* ─────────────────────────────────────────────────────────── technology */
  { slug: "k-vertex-spatial", name: "Vertex — Spatial Computing", category: "technology", theme: "siren", recipe: 3, brand: "Vertex XR", eyebrow: "Spatial computing", headline: "Built for headsets people actually own", subhead: "Spatial applications for training and design review, shipped to the hardware your client already bought.", cta: "Discuss a build", cta2: "See demos", tags: ["dark", "bold", "xr", "technology"], words: ["Training", "Design review", "Cross-headset"], features: [["Cross-headset", "One build, every major device, including the cheap ones."], ["Comfort first", "Locomotion and framerate budgeted before any feature."], ["Measured outcomes", "Training builds ship with assessment data, not impressions."]], stats: [["90fps", "Floor"], ["4", "Headsets supported"], ["31", "Builds shipped"], ["0", "Reported nausea"]] },
  { slug: "k-mesh-robotics", name: "Mesh — Warehouse Robotics", category: "technology", theme: "hazard", recipe: 0, brand: "Mesh", eyebrow: "Warehouse automation", headline: "Robots that work the aisles you already have", subhead: "No re-racking, no floor markings, no six-month integration — it maps your building and starts moving stock.", cta: "Book a site survey", cta2: "Specifications", tags: ["dark", "bold", "robotics", "industrial"], words: ["No re-racking", "Self-mapping", "Shared aisles"], features: [["Maps your building", "Two days of survey, then it drives. No infrastructure changes."], ["Works alongside people", "Certified for shared aisles rather than caged off."], ["Scales one unit at a time", "Add a robot whenever volume needs it."]], stats: [["2 days", "To productive"], ["0", "Floor markings"], ["24/7", "Duty cycle"], ["180", "Units deployed"]] },

  /* ────────────────────────────────────────────────────────────── fitness */
  { slug: "k-tempo-training", name: "Tempo — Training App", category: "fitness", theme: "cadet", recipe: 3, brand: "Tempo", eyebrow: "Strength training", headline: "The programme adapts, you just turn up", subhead: "Progressive overload calculated from what you actually lifted, not what the plan assumed.", cta: "Start free", cta2: "How it works", tags: ["dark", "sport", "app", "modern"], words: ["Adaptive", "Evidence-based", "No adverts"], features: [["Adapts to the session", "A bad night changes next week automatically."], ["Evidence-based", "Programming follows the literature, with the citations linked."], ["No advertising", "Subscription only. Nothing is sold to you mid-workout."]], stats: [["0", "Adverts"], ["4.8", "Rating"], ["12", "Programmes"], ["180k", "Users"]] },

  /* ─────────────────────────────────────────────────────────────── travel */
  { slug: "k-passage-sailing", name: "Passage — Sailing School", category: "travel", theme: "beacon", recipe: 5, brand: "Passage", eyebrow: "Sailing school", headline: "Learn on a boat that is going somewhere", subhead: "Mile-building passages rather than laps of a bay, with a berth and a qualification at the end.", cta: "See passages", tags: ["dark", "sea", "training", "adventure"], features: [["Real passages", "Cross-channel and coastal, not exercises within sight of the marina."], ["Four students", "One instructor, four crew, everyone helms."], ["Miles logged", "Signed, counted and valid towards the next qualification."]], steps: [["Book a berth", "Five days, food included, no experience needed at the first level."], ["Sail", "Watches, a night passage, real navigation."], ["Log it", "Miles and qualification signed off before you leave the boat."]], stats: [["4", "Students per boat"], ["500", "Miles per passage"], ["5", "Days"]] },

  /* ─────────────────────────────────────────────────────────────── events */
  { slug: "k-gather-catering", name: "Gather — Event Catering", category: "events", theme: "kiln", recipe: 5, brand: "Gather", eyebrow: "Event catering", headline: "Food that survives being served to two hundred", subhead: "Menus designed for the realities of a field kitchen, so the ninetieth plate is as good as the first.", cta: "Request a menu", tags: ["light", "warm", "catering", "events"], features: [["Built for volume", "Dishes chosen because they hold, not because they photograph."], ["One tasting, properly", "Three courses, at our place, before you commit."], ["Dietary handled quietly", "Alternatives that look like the main menu, not an afterthought."]], steps: [["Tasting", "Three courses, six weeks out."], ["Final numbers", "Two weeks before. Small adjustments after that are fine."], ["On the day", "Our kitchen, our staff, our clean-up."]], stats: [["200", "Typical covers"], ["1", "Tasting included"], ["14yr", "Catering"]] },

  /* ───────────────────────────────────────────────────────────────── blog */
  { slug: "k-index-engineering", name: "Index — Engineering Writing", category: "blog", theme: "console", recipe: 2, brand: "Index", eyebrow: "Engineering writing", headline: "Postmortems, in public", subhead: "Incident writeups and architecture notes from a team that publishes the ones that went badly.", cta: "Read the archive", tags: ["dark", "terminal", "engineering", "writing"], quote: ["Publishing the failures is rare enough. Publishing them this clearly is why I send Index to every new hire.", "Marta Olsen", "Staff engineer, Corveil"], words: ["Postmortems", "In public", "Including ours"], features: [["Real postmortems", "Including the ones where we caused it. Especially those."], ["No marketing", "Nothing here is a product pitch in a hat."], ["Code that runs", "Every snippet is from a repository you can clone."]], steps: [["Read an incident", "Start with the database failover. It is the honest one."], ["Subscribe", "Fortnightly, no tracking pixels."], ["Argue", "Comments are open and the engineers are in them."]], stats: [["61", "Postmortems"], ["0", "Sponsored posts"], ["5yr", "Publishing"]] },

  /* ──────────────────────────────────────────────────────────── ecommerce */
  { slug: "k-provision-grocer", name: "Provision — Online Grocer", category: "ecommerce", theme: "press", recipe: 5, brand: "Provision", eyebrow: "Short supply chain grocer", headline: "Everything here has a farm attached", subhead: "A grocer where every product lists the producer and the week it was harvested.", cta: "Shop this week", tags: ["light", "food", "local", "retail"], features: [["Named producers", "Every item lists the farm and the distance it travelled."], ["Harvested this week", "Fresh produce picked within three days of delivery."], ["No single-use plastic", "Returnable crates, collected on the next delivery."]], steps: [["Order by Tuesday", "For Friday delivery in your area."], ["We pack Thursday", "After the farms deliver, so nothing sits."], ["Crates returned", "Left on the step, collected next week."]], stats: [["48", "Producers"], ["3 days", "Farm to door"], ["0", "Single-use plastic"]] },
];
