import type { TemplateDef } from "./catalog";
import type { KineticSectionKey } from "./sections-kinetic";

/**
 * The kinetic collection.
 *
 * Every entry is a real piece of writing rather than a slot-filled variation:
 * the headline, the services and the figures are specific to the business
 * being described, because a template whose copy is obviously placeholder
 * reads as a template no matter how it is laid out.
 *
 * The art direction comes from pairing a seed with one of eighteen themes and
 * one of six layout recipes, none of which centre a headline over three equal
 * cards. Adjacent entries never share a theme, so the catalogue never shows
 * two of the same colour side by side.
 */

const img = (seed: string, w = 1600, h = 900) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

/** Layout recipes. Each leads with a different kind of asymmetry. */
const RECIPES: KineticSectionKey[][] = [
  // 0 — headline against a column of figures, then an index of services
  ["nav:simple", "hero:offsetIndex", "block:ticker", "block:indexList", "block:manifesto", "block:bigQuote", "block:faq", "block:cta", "block:footer"],
  // 1 — poster type, figures as rules, work below
  ["nav:minimal", "hero:oversize", "block:dataRows", "block:indexList", "block:gallery", "block:bigQuote", "block:cta", "block:footer"],
  // 2 — statement first, argument pinned beside scrolling text
  ["nav:simple", "hero:statement", "block:ticker", "block:manifesto", "block:dataRows", "block:featureAlternating", "block:testimonials", "block:contact", "block:footer"],
  // 3 — ledger hero for anything that lives on numbers
  ["nav:simple", "hero:ledger", "block:indexList", "block:featureBento", "block:bigQuote", "block:pricing", "block:faq", "block:footer"],
  // 4 — gallery-led, for work that shows rather than tells
  ["nav:minimal", "hero:oversize", "block:gallery", "block:indexList", "block:dataRows", "block:contact", "block:footer"],
  // 5 — service business: index, steps, proof, booking
  ["nav:simple", "hero:offsetIndex", "block:indexList", "block:manifesto", "block:dataRows", "block:testimonials", "block:contact", "block:footer"],
];

export type Seed = {
  slug: string;
  name: string;
  category: string;
  theme: string;
  recipe: number;
  brand: string;
  eyebrow: string;
  headline: string;
  subhead: string;
  cta: string;
  cta2?: string;
  features: [string, string][];
  steps?: [string, string][];
  stats?: [string, string][];
  quote?: [string, string, string];
  words?: string[];
  gallery?: string[];
  tags: string[];
};

const NAV = [
  { label: "Work", href: "#features" },
  { label: "Approach", href: "#how" },
  { label: "Contact", href: "#contact" },
];

export function buildKinetic(seed: Seed): TemplateDef {
  const layout = RECIPES[seed.recipe % RECIPES.length];
  return {
    slug: seed.slug,
    name: seed.name,
    category: seed.category,
    theme: seed.theme,
    kinetic: true,
    description: seed.subhead,
    tags: seed.tags,
    layout,
    data: {
      brand: seed.brand,
      nav: NAV,
      eyebrow: seed.eyebrow,
      headline: seed.headline,
      subhead: seed.subhead,
      ctaPrimary: { label: seed.cta, href: "#contact" },
      ctaSecondary: seed.cta2 ? { label: seed.cta2, href: "#features" } : undefined,
      badges: seed.words,
      logos: seed.words,
      heroImage: img(seed.slug),
      heroImageAlt: `${seed.brand} work`,
      featuresTitle: "What we do",
      features: seed.features.map(([title, body]) => ({ title, body })),
      steps: (seed.steps ?? []).map(([title, body]) => ({ title, body })),
      stats: (seed.stats ?? []).map(([value, label]) => ({ value, label })),
      quotes: seed.quote ? [{ quote: seed.quote[0], name: seed.quote[1], role: seed.quote[2] }] : [],
      gallery: (seed.gallery ?? []).map((caption, i) => ({
        src: img(`${seed.slug}-${i}`, 900, 700),
        caption,
      })),
      faq: [
        { q: "How do we start?", a: "A short call, then a written proposal with scope, price and dates. No obligation either way." },
        { q: "What does it cost?", a: "Fixed price per project, agreed before anything begins. No hourly billing and no surprises at the end." },
        { q: "How long does it take?", a: "Most engagements run four to eight weeks. We will tell you honestly if yours is larger." },
      ],
      contact: {
        email: `hello@${seed.slug.split("-")[0]}.example`,
        phone: "+1 (555) 0100",
        address: "Studio address, your city",
        hours: "Mon — Fri, 9:00 — 17:00",
      },
      ctaTitle: "How it works",
      ctaBody: "Tell us what you are trying to do and we will tell you whether we are the right people for it.",
      footerNote: `${seed.brand} — ${seed.eyebrow.toLowerCase()}.`,
    },
  };
}

/*
 * Seeds, grouped by genre. Themes are assigned so that no two consecutive
 * entries share one — the catalogue reads as a collection rather than a
 * gradient.
 */
const SEEDS: Seed[] = [
  /* ─────────────────────────────────────────────────────────────── saas */
  { slug: "k-ledgerline-saas", name: "Ledgerline — Finance Ops", category: "saas", theme: "detonate", recipe: 3, brand: "Ledgerline", eyebrow: "Finance operations", headline: "Close the month before the month is over", subhead: "Reconciliation that runs continuously instead of in a panic on the third working day.", cta: "Book a walkthrough", cta2: "See the numbers", tags: ["dark", "bold", "b2b", "saas"], words: ["Reconciliation", "Close", "Audit trail", "Multi-entity"], features: [["Continuous reconciliation", "Transactions match as they land, so the close is a review rather than a rebuild."], ["Audit trail by default", "Every adjustment carries who, when and why. Nothing has to be reconstructed later."], ["Multi-entity, one ledger", "Consolidate across entities and currencies without a spreadsheet in the middle."], ["Controls that explain themselves", "Each rule states the exception it is watching for in plain language."]], stats: [["3.1 days", "Median close"], ["99.97%", "Auto-match rate"], ["$4.2B", "Reconciled monthly"], ["220", "Finance teams"]], quote: ["We closed in four days instead of eleven. The controller stopped working weekends, which is the only metric anyone remembers.", "Dana Whitfield", "Controller, Northwind"] },
  { slug: "k-quarry-data", name: "Quarry — Warehouse Analytics", category: "saas", theme: "ultramarine", recipe: 0, brand: "Quarry", eyebrow: "Warehouse-native analytics", headline: "Query the data where it already lives", subhead: "No second copy, no nightly sync to babysit, no arguments about which number is real.", cta: "Start free", cta2: "Read the docs", tags: ["dark", "bold", "data", "saas"], words: ["Warehouse-native", "No ETL", "Version-controlled", "Open SQL"], features: [["Zero copy", "Models compile to SQL and run in your warehouse. We never hold your data."], ["Metrics in version control", "Definitions live in git, so a number changing has an author and a diff."], ["Answers, then queries", "Ask in plain language, read the SQL it wrote, edit it if it is wrong."], ["Costs you can see", "Every dashboard shows what it costs to refresh before you schedule it."]], stats: [["0", "Copies of your data"], ["8s", "Median query"], ["1,900", "Teams"], ["40%", "Lower warehouse spend"]], quote: ["The metrics layer in git ended a two-year argument about revenue definitions in about a week.", "Marco Reyes", "Head of Data, Halcyon"] },
  { slug: "k-relay-support", name: "Relay — Support Desk", category: "saas", theme: "cadet", recipe: 2, brand: "Relay", eyebrow: "Customer support", headline: "Every conversation, in one thread", subhead: "Email, chat and phone collapse into a single history so nobody asks the customer to repeat themselves.", cta: "Try it free", tags: ["dark", "b2b", "saas", "modern"], words: ["Unified inbox", "SLA", "Macros", "Insights"], stats: [["4 min", "First reply"], ["1", "Thread per customer"], ["3", "Channels merged"]], features: [["One thread per person", "Channels merge into a single history, so context survives the handover."], ["SLAs that mean something", "Targets by plan and severity, with the breach visible before it happens."], ["Macros without the robot voice", "Snippets fill the facts and leave the sentences to your team."], ["Answers from your own tickets", "Suggestions drawn from what your team actually replied, not a generic model."]], steps: [["Connect a mailbox", "Forward an address and history imports in the background."], ["Set two SLAs", "First response and resolution. Everything else can wait."], ["Watch the queue", "Volume, backlog and the three conversations most likely to go wrong."]], quote: ["First response went from nine hours to forty minutes without hiring anyone.", "Priya Raman", "Support Lead, Vantage"] },
  { slug: "k-signal-observe", name: "Signalbox — Observability", category: "saas", theme: "console", recipe: 3, brand: "Signalbox", eyebrow: "Observability", headline: "Know it broke before the customer tells you", subhead: "Traces, logs and metrics in one place, priced so you do not have to sample away the incident you needed.", cta: "Start free", cta2: "See pricing", tags: ["dark", "terminal", "devtools", "saas"], words: ["Traces", "Logs", "Metrics", "No sampling"], features: [["Keep everything", "Full-fidelity retention at a price that does not punish a bad week."], ["One click from alert to trace", "The page that woke you links to the exact request that caused it."], ["Service map that is current", "Built from real traffic, not a diagram somebody drew in 2023."], ["Alerts with a hypothesis", "Every page arrives with what changed in the ten minutes before it."]], stats: [["100%", "Traces kept"], ["1.4s", "Alert to trace"], ["12k", "Services monitored"], ["31%", "Fewer pages"]], quote: ["We stopped sampling and our bill went down. I still do not entirely understand how.", "Tom Alvarez", "SRE, Orbit"] },

  /* ──────────────────────────────────────────────────────────── startup */
  { slug: "k-meridian-launch", name: "Meridian — Launch", category: "startup", theme: "siren", recipe: 1, brand: "Meridian", eyebrow: "Launching this spring", headline: "The scheduling app that respects your calendar", subhead: "It reads the meetings you already have and refuses to book over the two hours you actually get work done.", cta: "Join the waitlist", tags: ["dark", "bold", "startup", "product"], words: ["Focus time", "Two-way sync", "No double booking"], gallery: ["Availability that defends deep work", "Round-robin without the spreadsheet", "Buffers that hold", "Rescheduling in one tap"], features: [["Focus time is real time", "Blocks you mark as deep work are as unbookable as a client call."], ["Two-way, actually", "Changes propagate both ways in seconds, not on a five-minute poll."], ["Buffers that hold", "Fifteen minutes between calls that nothing is allowed to eat."], ["One link, many rules", "Different availability per audience, one address to share."]], stats: [["18,900", "On the list"], ["4.9", "Beta rating"], ["6", "People building it"]] },
  { slug: "k-tessera-marketplace", name: "Tessera — Marketplace", category: "startup", theme: "hazard", recipe: 0, brand: "Tessera", eyebrow: "Marketplace infrastructure", headline: "Payments, payouts and disputes in one API", subhead: "The unglamorous half of a marketplace, already built, already compliant in thirty countries.", cta: "Read the API docs", cta2: "Talk to us", tags: ["dark", "bold", "fintech", "api"], words: ["Payouts", "KYC", "Disputes", "30 countries"], features: [["Split payments", "Take a fee, pay the seller, handle the refund. Three calls, not three months."], ["Onboarding that passes", "KYC flows that regulators have already seen and approved."], ["Disputes handled", "Evidence collected automatically from the order you already stored."], ["Payouts on your schedule", "Daily, weekly, or held until delivery confirms."]], stats: [["30", "Countries"], ["$180M", "Processed"], ["2 weeks", "Median integration"], ["0.4%", "Dispute rate"]], quote: ["We shipped payouts in nine days. Our own estimate had been a quarter.", "Sarah Lindqvist", "CTO, Fielding"] },
  { slug: "k-northpoint-climate", name: "Northpoint — Climate Tech", category: "startup", theme: "thicket", recipe: 2, brand: "Northpoint", eyebrow: "Industrial decarbonisation", headline: "Cut the emissions you can actually measure", subhead: "We instrument the plant first and argue about targets second, because a number you cannot measure is a press release.", cta: "Request a survey", tags: ["light", "editorial", "climate", "industry"], words: ["Metering", "Scope 1", "Verified", "Retrofit"], stats: [["41%", "Median reduction"], ["18 mo", "To payback"], ["62", "Plants instrumented"]], features: [["Meter before model", "Real sensors on real equipment. Estimates come later, if at all."], ["Retrofit, not replace", "Most sites find a third of their savings in equipment they already own."], ["Verification built in", "Every claim traces to a reading an auditor can follow."]], steps: [["Two-week survey", "We instrument the highest-draw equipment and watch it for a fortnight."], ["Ranked plan", "Every action costed, with payback in months rather than a vague ROI."], ["Measured result", "The same meters prove the saving. No modelled numbers in the report."]], quote: ["They found 22% in compressed air alone. We had been quoted a new plant.", "James Okonkwo", "Operations Director, Corvus"] },
  { slug: "k-halcyon-health", name: "Halcyon — Digital Health", category: "startup", theme: "lagoon", recipe: 3, brand: "Halcyon", eyebrow: "Chronic care", headline: "Care that continues between appointments", subhead: "Remote monitoring that a nurse actually reads, with escalation rules a clinician wrote.", cta: "Book a demo", cta2: "See outcomes", tags: ["dark", "health", "clinical", "modern"], words: ["Remote monitoring", "Escalation", "Clinician-led"], features: [["Readings that reach someone", "Every alert has a named owner and a response time."], ["Clinician-written rules", "Thresholds set by the people responsible for the patient."], ["One record", "Readings land in the chart, not a separate portal nobody opens."], ["Patients who stay enrolled", "Weekly contact by the channel they chose, not the one we prefer."]], stats: [["94%", "12-month retention"], ["38%", "Fewer admissions"], ["11,200", "Patients monitored"], ["4 min", "Median response"]], quote: ["The escalation rules meant our nurses stopped drowning in readings nobody had time to interpret.", "Dr Anke Vogel", "Clinical Director"] },

  /* ────────────────────────────────────────────────────────── portfolio */
  { slug: "k-ashcroft-design", name: "Ashcroft — Product Design", category: "portfolio", theme: "newsprint", recipe: 4, brand: "Ren Ashcroft", eyebrow: "Product designer, Berlin", headline: "I design interfaces that explain themselves", subhead: "Twelve years on developer tools and financial products — the kind where being wrong is expensive.", cta: "See selected work", cta2: "Get in touch", tags: ["light", "editorial", "typography", "personal"], gallery: ["Ledger — reconciliation for finance teams", "Signal — observability for platform engineers", "Harbour — deployment dashboard", "Tide — treasury forecasting"], features: [["Dense interfaces", "Tables, filters and dashboards that stay readable at a thousand rows."], ["Design systems", "Tokens and components your engineers keep using after I leave."], ["Prototyping in code", "I build the real thing in HTML and CSS. Static mockups hide the hard problems."]], stats: [["12", "Years designing"], ["34", "Products shipped"], ["4", "Design systems built"]] },
  { slug: "k-vaquero-motion", name: "Vaquero — Motion Design", category: "portfolio", theme: "detonate", recipe: 1, brand: "Vaquero", eyebrow: "Motion direction", headline: "Things that move on purpose", subhead: "Title sequences, product film and brand motion for companies that live on screens.", cta: "View reel", tags: ["dark", "bold", "motion", "creative"], gallery: ["Vantage — identity in motion", "Orbit — launch film", "Fathom — title sequence", "Lumen — product film", "Kite — campaign", "Bramble — broadcast package"], features: [["Motion systems", "Not one film — the rules that let your team make the next twenty."], ["Built for the edit", "Delivered in the formats your channels actually need, on the day."], ["Sound as design", "Cut to a track that was written for it, not licensed over it."]], stats: [["120", "Films delivered"], ["9", "Years"], ["3", "People"]] },
  { slug: "k-okonkwo-arch", name: "Okonkwo — Architecture", category: "portfolio", theme: "yves", recipe: 4, brand: "Okonkwo Studio", eyebrow: "Architecture, Lagos & London", headline: "Buildings that know where they are", subhead: "Housing, cultural and civic work grounded in the climate and the street it sits on.", cta: "See projects", tags: ["light", "editorial", "luxury", "architecture"], gallery: ["Yaba Housing — 48 units", "Ikoyi Library", "Peckham Workshops", "Marina Pavilion"], features: [["Climate first", "Shade, mass and airflow before mechanical cooling."], ["Local material", "Specified from what is made within a day's drive where we can."], ["Built as drawn", "We stay on site through construction. Detail survives that way."]], stats: [["31", "Completed"], ["2", "RIBA awards"], ["14", "Years"]] },
  { slug: "k-marlowe-photo", name: "Marlowe — Photography", category: "photography", theme: "cellar", recipe: 4, brand: "Ida Marlowe", eyebrow: "Documentary photography", headline: "Long assignments, quiet pictures", subhead: "Reportage for magazines and institutions, usually over months rather than an afternoon.", cta: "See the work", tags: ["light", "editorial", "documentary", "serif"], gallery: ["Coastal — three winters on the North Sea", "Night Shift", "The Last Foundry", "Harvest", "River Season", "Terminus"], features: [["Long form", "Stories built over months. Nothing useful happens in an hour."], ["Print first", "Shot and graded for paper, delivered for screen as well."], ["Archive access", "Twenty years of negatives, catalogued and licensable."]], stats: [["20", "Years"], ["48", "Published essays"], ["6", "Books"]] },

  /* ───────────────────────────────────────────────────────────── agency */
  { slug: "k-fielding-growth", name: "Fielding — Growth", category: "agency", theme: "alarm", recipe: 5, brand: "Fielding", eyebrow: "Performance marketing", headline: "Growth that survives the quarter it was booked in", subhead: "We run acquisition for companies past product-market fit — the part where the easy channels stopped working.", cta: "Book a call", cta2: "See results", tags: ["dark", "bold", "b2b", "marketing"], words: ["Paid", "Lifecycle", "Landing pages", "Measured"], features: [["Paid acquisition", "Search, social and anything measurable. We stop what fails faster than most teams find comfortable."], ["Landing page systems", "A page per audience, built and tested in days, without your engineers."], ["Lifecycle and retention", "The cheapest customer is the one you already have. Most of the wins are here."], ["Reporting you can argue with", "The same dashboard we use, with the methodology written down."]], steps: [["Two-week audit", "Accounts, analytics and six months of spend before we propose anything."], ["Ninety-day plan", "Three channels, clear targets, weekly numbers."], ["Hand it back", "Most clients bring this in-house by month twelve. We write the playbook."]], stats: [["312%", "Median 12-month growth"], ["$48M", "Spend managed"], ["27", "Active accounts"], ["4.9", "Client rating"]], quote: ["They cut our spend by a third and revenue went up. That conversation was uncomfortable and correct.", "Sarah Lindqvist", "CMO, Fielding"] },
  { slug: "k-corvus-brand", name: "Corvus — Brand Studio", category: "agency", theme: "press", recipe: 1, brand: "Corvus", eyebrow: "Brand & identity", headline: "Identity for companies that outgrew their logo", subhead: "Naming, identity and the systems that keep it consistent once forty people are using it.", cta: "Start a project", tags: ["light", "editorial", "brand", "serif"], gallery: ["Vantage — full identity", "Orbit — naming and mark", "Fathom — editorial system", "Lumen — packaging"], features: [["Naming that clears", "Shortlists come pre-checked for trademark and domain, so nothing dies in legal."], ["Systems, not artefacts", "Tokens, components and rules your team can run without us."], ["Rollout planned", "Sequenced by what customers see first, not what is easiest to change."]], stats: [["48", "Identities"], ["11", "Years"], ["6", "People"]], quote: ["They gave us a brand that behaves. Engineering implemented it in a week.", "Priya Raman", "CEO, Vantage"] },
  { slug: "k-stackline-dev", name: "Stackline — Engineering", category: "agency", theme: "beacon", recipe: 2, brand: "Stackline", eyebrow: "Software engineering", headline: "We finish the things other teams started", subhead: "Rescue work, platform migrations and the projects that have been ninety percent done for eight months.", cta: "Describe your project", tags: ["dark", "terminal", "engineering", "b2b"], words: ["Rescue", "Migration", "Platform", "Handover"], stats: [["31", "Rescues completed"], ["6 wks", "Typical engagement"], ["0", "Rewrites proposed"]], features: [["Rescue engagements", "We inherit the codebase as it is and get it shipping again."], ["Migrations without a freeze", "Move platform while the product keeps releasing."], ["Handover as a deliverable", "Documentation, runbooks and two weeks of pairing before we go."]], steps: [["One-week read", "We read the code and talk to whoever is left. Then a written assessment."], ["Ship something", "Something real in production inside three weeks, however small."], ["Leave properly", "Your team runs it before the engagement ends, not after."]], quote: ["The only agency that ever told us to stop paying them.", "James Okonkwo", "Founder, Corvus"] },
  { slug: "k-bramble-content", name: "Bramble — Content", category: "agency", theme: "kiln", recipe: 5, brand: "Bramble", eyebrow: "Editorial & content", headline: "Writing that someone would read voluntarily", subhead: "Editorial for technical companies, written by people who understand what you sell.", cta: "See our work", tags: ["light", "editorial", "content", "warm"], features: [["Technical writing", "Documentation and long-form by writers who can read the code."], ["Editorial programmes", "A publishing rhythm your team can keep after the retainer ends."], ["Research first", "We talk to your customers before we write a word about them."]], steps: [["Interviews", "Five customers and three of your engineers. Recorded, transcribed, quoted."], ["Outline", "Agreed before drafting, so the first draft is not a surprise."], ["Two rounds", "Structural, then line. A third round means we got the outline wrong."]], stats: [["340", "Pieces published"], ["8", "Retained clients"], ["2.4x", "Median traffic lift"]] },

  /* ───────────────────────────────────────────────────────── restaurant */
  { slug: "k-solstice-dining", name: "Solstice — Fine Dining", category: "restaurant", theme: "cellar", recipe: 4, brand: "Solstice", eyebrow: "Tasting menu, twelve seats", headline: "One sitting. One menu. Every evening", subhead: "Twelve seats around an open kitchen, a menu that changes when the produce does, and no à la carte.", cta: "Reserve a seat", tags: ["light", "luxury", "serif", "dining"], gallery: ["The counter", "Winter menu", "The cellar", "Service"], features: [["One sitting", "Everyone eats together at seven. The kitchen cooks one thing properly."], ["Produce decides", "The menu is written the morning it is served."], ["No phones at the counter", "Not a rule, just something that stopped happening on its own."]], stats: [["12", "Seats"], ["1", "Sitting nightly"], ["7", "Courses"]] },
  { slug: "k-ember-grill", name: "Ember — Fire Kitchen", category: "restaurant", theme: "flare", recipe: 1, brand: "Ember", eyebrow: "Live fire cooking", headline: "Everything here touches flame", subhead: "No gas, no induction — one wood-fired hearth and whatever the market had that morning.", cta: "Book a table", tags: ["dark", "bold", "fire", "dining"], gallery: ["The hearth", "Whole turbot", "Embers", "The room", "Bread", "Sunday lunch"], features: [["Wood only", "Oak and beech. The temperature is managed by moving food, not turning a dial."], ["Whole animal", "We buy whole and use it across the week. The menu follows."], ["Open to nine", "Kitchen closes when the fire does."]], stats: [["1", "Hearth"], ["600°C", "Peak"], ["0", "Gas lines"]] },
  { slug: "k-mercato-deli", name: "Mercato — Deli & Bakery", category: "restaurant", theme: "kiln", recipe: 5, brand: "Mercato", eyebrow: "Bakery and deli", headline: "Bread at six, gone by two", subhead: "A neighbourhood bakery that bakes what it can sell in a day and closes when it runs out.", cta: "See today's bake", tags: ["light", "warm", "bakery", "local"], features: [["Slow fermentation", "Thirty-six hours. It is why it keeps for three days without anything added."], ["Daily, not frozen", "Nothing is part-baked. When it is gone, it is gone."], ["Whole grain milled here", "A stone mill in the back. Flour is never more than a week old."]], steps: [["Order the night before", "Large orders and celebration cakes need a day's notice."], ["Collect before two", "We rarely have anything left by early afternoon."], ["Wholesale from five", "Restaurant deliveries leave before the shop opens."]], stats: [["36h", "Fermentation"], ["6am", "First bake"], ["4", "Bakers"]] },
  { slug: "k-tavola-trattoria", name: "Tavola — Trattoria", category: "restaurant", theme: "press", recipe: 5, brand: "Tavola", eyebrow: "Family trattoria since 1974", headline: "The same eleven dishes for fifty years", subhead: "We change the menu roughly once a decade, and people write letters when we do.", cta: "Book a table", tags: ["light", "editorial", "family", "italian"], features: [["Eleven dishes", "Enough to choose from, few enough to cook perfectly every night."], ["Pasta made at four", "Every day, by hand, in the window where you can watch."], ["Wine from three regions", "We know these growers. That is the whole list."]], steps: [["Walk in before seven", "Half the room is kept for people who did not plan ahead."], ["Book after seven", "Evenings fill about two weeks out."], ["Sunday is family lunch", "One long table, one price, whatever the kitchen feels like."]], stats: [["1974", "Opened"], ["11", "Dishes"], ["3", "Generations"]] },

  /* ────────────────────────────────────────────────────────── ecommerce */
  { slug: "k-forge-tools", name: "Forge — Hand Tools", category: "ecommerce", theme: "brass", recipe: 1, brand: "Forge", eyebrow: "Hand tools, made to last", headline: "Buy it once", subhead: "Drop-forged tools with a hundred-year guarantee, sold direct because the markup was the only thing the middle added.", cta: "Shop the range", tags: ["dark", "industrial", "craft", "retail"], gallery: ["Chisels", "The forge", "Bench planes", "Handles", "Steel", "Finished"], features: [["Forged, not cast", "Grain follows the shape of the tool. It is why they do not snap."], ["Hundred-year guarantee", "Transferable. We expect to honour some of these for your grandchildren."], ["Sharpened before shipping", "Every edge is honed by hand and tested on end grain."]], stats: [["100yr", "Guarantee"], ["1 of 3", "UK forges left"], ["0", "Resellers"]] },
  { slug: "k-loom-textiles", name: "Loom — Textiles", category: "ecommerce", theme: "thicket", recipe: 4, brand: "Loom", eyebrow: "Woven in Yorkshire", headline: "Cloth with a postcode", subhead: "Blankets and throws woven on looms we own, from wool we can name the farm for.", cta: "Shop", tags: ["light", "craft", "textile", "warm"], gallery: ["The mill", "Undyed wool", "On the loom", "Finished throws"], features: [["Traceable to the farm", "Every batch lists the flock, the shearing date and the mill run."], ["Undyed where possible", "Seven natural fleece colours before anything reaches a dye bath."], ["Mended free, forever", "Send it back and we reweave it. Most come back once in thirty years."]], stats: [["1919", "Mill built"], ["7", "Natural colours"], ["9", "Weavers"]] },
  { slug: "k-cadence-audio", name: "Cadence — Audio", category: "ecommerce", theme: "beacon", recipe: 0, brand: "Cadence", eyebrow: "Studio monitors", headline: "Speakers that tell you the truth", subhead: "Monitors designed to be accurate rather than flattering, which is uncomfortable and correct.", cta: "Compare models", cta2: "Read the measurements", tags: ["dark", "technical", "audio", "retail"], words: ["Flat response", "Measured", "Serviceable", "10-year parts"], features: [["Published measurements", "Every model's response curve, on the product page, before you buy."], ["Serviceable by design", "Drivers and amps replaceable with a screwdriver. Parts stocked ten years."], ["Room correction included", "A microphone in the box and software that uses it properly."]], stats: [["±1.5dB", "Response"], ["10yr", "Parts stocked"], ["4", "Models"]] },
  { slug: "k-verdant-plants", name: "Verdant — Plants", category: "ecommerce", theme: "lagoon", recipe: 5, brand: "Verdant", eyebrow: "Nursery-grown houseplants", headline: "Grown here, not flown here", subhead: "Plants raised in our own glasshouses, shipped the week they are ready, with the light they need written on the label.", cta: "Shop plants", tags: ["dark", "botanical", "retail", "modern"], features: [["Grown, not imported", "Everything spends its whole life in our glasshouses."], ["Light, honestly labelled", "In lux, with a photograph of what that window actually looks like."], ["Replaced if it fails", "First ninety days, no photograph of the corpse required."]], steps: [["Tell us the window", "Direction and how far the plant will sit from it."], ["We pick", "Three options that will survive that spot, not the ones we overstocked."], ["Check in at week six", "One message asking how it is doing, then we leave you alone."]], stats: [["90 days", "Guarantee"], ["4", "Glasshouses"], ["0", "Air freight"]] },

  /* ─────────────────────────────────────────────────────────── developer */
  { slug: "k-anvil-ci", name: "Anvil — Build Pipeline", category: "developer", theme: "console", recipe: 3, brand: "Anvil", eyebrow: "Continuous integration", headline: "Builds that finish before you switch tabs", subhead: "Aggressive caching, real parallelism, and a bill that does not scale with how flaky your tests are.", cta: "Start building", cta2: "Read the docs", tags: ["dark", "terminal", "devtools", "ci"], words: ["Cached", "Parallel", "Reproducible", "OSS free"], features: [["Content-addressed cache", "Identical inputs never build twice, across branches and machines."], ["Real parallelism", "Test splitting by measured duration, not alphabetical order."], ["Reproducible by default", "Same inputs, same artefact, byte for byte."], ["Free for open source", "No seat count, no build minute maths."]], stats: [["94s", "Median build"], ["11x", "Cache hit speedup"], ["38k", "Repositories"], ["$0", "Open source"]], quote: ["Our pipeline went from nineteen minutes to under two. Nobody optimised anything; the cache just worked.", "Daniel Foss", "Platform Lead, Signal"] },
  { slug: "k-harbor-deploy", name: "Harbour — Deploys", category: "developer", theme: "cadet", recipe: 2, brand: "Harbour", eyebrow: "Deployment", headline: "Ship on Friday", subhead: "Progressive rollout, automatic rollback and a diff of exactly what is about to change in production.", cta: "Read the docs", tags: ["dark", "devtools", "modern", "b2b"], words: ["Canary", "Rollback", "Diff", "Audit"], stats: [["9 sec", "Rollback"], ["1,400", "Deploys a day"], ["0", "Maintenance windows"]], features: [["See the diff first", "Config, migrations and dependencies, before anything moves."], ["Canary that watches itself", "Rolls back on your metrics, not on a fixed timer."], ["Migrations gated", "Schema changes need a second pair of eyes. Enforced, not requested."]], steps: [["Connect the repo", "One file. It reads what you already have."], ["Set two signals", "Error rate and latency. That covers most bad deploys."], ["Deploy small, often", "Ten a day beats one a fortnight, and the tooling assumes it."]], quote: ["We deploy on Friday afternoons now. That sentence used to be a joke here.", "Anke Vogel", "VP Engineering, Ledger"] },
  { slug: "k-warden-cache", name: "Warden — Edge Cache", category: "developer", theme: "ultramarine", recipe: 3, brand: "Warden", eyebrow: "Edge caching", headline: "Invalidate exactly what changed", subhead: "Tag-based purging that clears one product page instead of your entire catalogue.", cta: "Try it free", cta2: "Benchmarks", tags: ["dark", "bold", "infra", "devtools"], words: ["Tagged purge", "Edge", "Stale-while-revalidate"], features: [["Tag anything", "Purge by product, by author, by tenant. Not by URL pattern and hope."], ["Stale while revalidate", "Nobody waits for a cold origin fetch, including the first visitor."], ["Origin shield", "One request reaches you per object, however many edges want it."]], stats: [["18ms", "Median edge"], ["99.3%", "Hit rate"], ["310", "Locations"], ["4M", "Purges/day"]] },
  { slug: "k-tideway-queue", name: "Tideway — Queues", category: "developer", theme: "hazard", recipe: 0, brand: "Tideway", eyebrow: "Durable queues", headline: "Exactly once, and we mean it", subhead: "A queue that survives your database going down, with a dead-letter path you will actually look at.", cta: "Read the docs", cta2: "See guarantees", tags: ["dark", "bold", "infra", "devtools"], words: ["Exactly once", "Durable", "Dead letter", "Replay"], features: [["Real exactly-once", "Idempotency keys handled by the broker, not by every consumer."], ["Dead letters with context", "The payload, the error and the three attempts, in one view."], ["Replay a window", "Re-run yesterday afternoon after you ship the fix."]], stats: [["0", "Messages lost"], ["8ms", "Median enqueue"], ["2.1B", "Delivered daily"], ["99.99%", "Uptime"]] },

  /* ─────────────────────────────────────────────────────────── education */
  { slug: "k-forge-academy", name: "Forge Academy — Engineering", category: "education", theme: "alarm", recipe: 5, brand: "Forge Academy", eyebrow: "Twelve-week intensive", headline: "Learn to build things that stay up", subhead: "Backend engineering taught by people who have been on call for what they are teaching you.", cta: "Apply now", tags: ["dark", "bold", "education", "technical"], features: [["Taught by practitioners", "Every instructor still works in the field. None teach full time."], ["Build under load", "The capstone runs against real traffic and real failure injection."], ["Small cohorts", "Sixteen people. Everyone gets read properly."]], steps: [["Weeks 1–4", "HTTP, databases, testing and the shape of a service."], ["Weeks 5–8", "Queues, caching, observability and failure modes."], ["Weeks 9–12", "Build, deploy and operate a real service under load."]], stats: [["16", "Per cohort"], ["87%", "Hired in 6 months"], ["12", "Weeks"]] },
  { slug: "k-atelier-school", name: "Atelier — Design School", category: "education", theme: "yves", recipe: 1, brand: "Atelier", eyebrow: "Design education", headline: "Draw before you open a laptop", subhead: "A year of fundamentals — type, colour, composition — before anyone touches design software.", cta: "See the syllabus", tags: ["light", "editorial", "design", "luxury"], gallery: ["Type studio", "Colour week", "Letterpress", "Final show"], features: [["Hand first", "Two terms on paper. It shows in everything afterwards."], ["Critique weekly", "Public, structured and kind. The single most useful hour."], ["Show at the end", "Real exhibition, real audience, real deadline."]], stats: [["1", "Year"], ["24", "Students"], ["9", "Tutors"]] },
  { slug: "k-lantern-tutoring", name: "Lantern — Tutoring", category: "education", theme: "kiln", recipe: 5, brand: "Lantern", eyebrow: "One-to-one tutoring", headline: "The gap is never where you think it is", subhead: "We diagnose before we teach, because most struggling students are missing something from two years earlier.", cta: "Book an assessment", tags: ["light", "warm", "education", "family"], features: [["Diagnose first", "A two-hour assessment before any lesson is scheduled."], ["Same tutor throughout", "Continuity matters more than matching a specialism exactly."], ["Parents get the plan", "Written, with what we are working on and how we will know it worked."]], steps: [["Assessment", "Two hours, in person, no sales pitch attached."], ["Written plan", "What is missing, in what order we will fill it."], ["Weekly sessions", "Same tutor, same time, reviewed every half term."]], stats: [["2h", "Assessment"], ["1:1", "Always"], ["12yr", "Running"]] },
  { slug: "k-summit-mba", name: "Summit — Executive Education", category: "education", theme: "cellar", recipe: 3, brand: "Summit", eyebrow: "Executive programmes", headline: "For people who cannot stop working for two years", subhead: "Modular executive education taught in intensive weeks, four times a year, in person.", cta: "Download the brochure", cta2: "Speak to admissions", tags: ["light", "luxury", "serif", "business"], features: [["Four weeks a year", "Intensive residential blocks rather than evenings after work."], ["Cohort of thirty", "Small enough that you will know all of them afterwards."], ["Applied capstone", "On a problem inside your own organisation."]], stats: [["4", "Weeks a year"], ["30", "Per cohort"], ["18", "Months"], ["94%", "Completion"]] },

  /* ──────────────────────────────────────────────────────────── finance */
  { slug: "k-cardinal-wealth", name: "Cardinal — Wealth", category: "finance", theme: "yves", recipe: 3, brand: "Cardinal", eyebrow: "Independent advice", headline: "Advice that is not selling you a product", subhead: "Fee-only planning. We hold no products, take no commission, and will tell you when to do nothing.", cta: "Book a consultation", cta2: "See our fees", tags: ["light", "luxury", "finance", "serif"], features: [["Fee only", "You pay us. Nobody else does. That is the whole model."], ["Plan before product", "Most first meetings end with a plan and no transaction."], ["Published fees", "On the site, in pounds, before you call."]], stats: [["£0", "Commission taken"], ["1996", "Founded"], ["310", "Families"], ["100%", "Fee-only"]] },
  { slug: "k-tallow-accounting", name: "Tallow — Accounting", category: "finance", theme: "brass", recipe: 5, brand: "Tallow", eyebrow: "Accounting for small companies", headline: "Your books, closed by the fifth", subhead: "Monthly bookkeeping and accounts for owner-managed businesses, at a fixed fee agreed in advance.", cta: "Get a quote", tags: ["dark", "professional", "finance", "b2b"], features: [["Fixed monthly fee", "Agreed up front. Questions do not cost extra."], ["Closed by the fifth", "Management accounts in your inbox before the first week is out."], ["One accountant", "The same person every month. They learn your business."]], steps: [["Handover", "We take the last twelve months and tidy them first."], ["Monthly rhythm", "You send receipts, we do the rest, accounts land on the fifth."], ["Year end, no drama", "Nothing to reconstruct because nothing was left."]], stats: [["5th", "Accounts delivered"], ["220", "Clients"], ["1", "Named accountant"]] },
  { slug: "k-anchor-insurance", name: "Anchor — Commercial Insurance", category: "finance", theme: "cadet", recipe: 0, brand: "Anchor", eyebrow: "Commercial broking", headline: "Read the policy before you need it", subhead: "We write plain-language summaries of what your cover actually excludes, because that is the part that matters.", cta: "Request a review", cta2: "How we work", tags: ["dark", "professional", "insurance", "b2b"], words: ["Plain language", "Exclusions", "Claims support"], features: [["Exclusions in plain English", "A one-page summary of what is not covered, alongside every quote."], ["Claims handled by us", "We argue with the insurer so you do not have to."], ["Annual review", "Cover checked against what your business actually does now."]], stats: [["1 page", "Plain summary"], ["94%", "Claims settled"], ["18yr", "Broking"], ["0", "Insurer ownership"]] },
  { slug: "k-meridian-fintech", name: "Meridian — Treasury", category: "finance", theme: "beacon", recipe: 3, brand: "Meridian", eyebrow: "Treasury software", headline: "Know your cash position at nine", subhead: "Balances, forecasts and exposures across every account and currency, refreshed overnight.", cta: "Book a demo", cta2: "See integrations", tags: ["dark", "technical", "fintech", "b2b"], words: ["Multi-bank", "Forecast", "FX", "Daily"], features: [["Every bank, one view", "Direct connections to 340 banks, no manual statement uploads."], ["Forecast that learns", "Built from your actual receipts, not a straight-line projection."], ["FX exposure, visible", "Net position by currency, updated as invoices are raised."]], stats: [["340", "Bank connections"], ["9am", "Daily refresh"], ["18", "Currencies"], ["±2%", "Forecast accuracy"]] },

  /* ───────────────────────────────────────────────────────── healthcare */
  { slug: "k-willow-clinic", name: "Willow — Clinic", category: "healthcare", theme: "lagoon", recipe: 5, brand: "Willow", eyebrow: "General practice", headline: "Twenty-minute appointments", subhead: "A practice built around consultations long enough to reach the actual problem.", cta: "Register", tags: ["dark", "clinical", "health", "calm"], features: [["Twenty minutes", "Standard. Not a double appointment you have to justify."], ["Same doctor", "Continuity is the single biggest predictor of good outcomes."], ["Results explained", "A call, not a portal notification you have to interpret alone."]], steps: [["Register online", "Ten minutes, no paperwork in the waiting room."], ["First appointment", "Forty minutes. We take a full history properly, once."], ["Ongoing care", "Same doctor, direct number, results by phone."]], stats: [["20 min", "Standard appointment"], ["1", "Named doctor"], ["48h", "Median wait"]] },
  { slug: "k-vessel-dental", name: "Vessel — Dental", category: "healthcare", theme: "thicket", recipe: 5, brand: "Vessel", eyebrow: "Dental practice", headline: "Prices on the wall", subhead: "Every treatment costed and displayed, so nobody finds out what it costs while lying down.", cta: "Book a check-up", tags: ["light", "calm", "dental", "health"], features: [["Published prices", "On the site and the wall. Quotes given before treatment, in writing."], ["No commission", "Clinicians are salaried. Nobody earns more by recommending more."], ["Prevention first", "We would rather see you twice a year than fix things once."]], steps: [["Check-up", "Full assessment, photographs, written plan with prices."], ["Decide in your own time", "No treatment agreed at the first visit unless it is urgent."], ["Six-month rhythm", "Most people never need more than this."]], stats: [["0", "Commission"], ["6mo", "Recall"], ["14", "Years"]] },
  { slug: "k-stride-physio", name: "Stride — Physiotherapy", category: "healthcare", theme: "hazard", recipe: 5, brand: "Stride", eyebrow: "Musculoskeletal physiotherapy", headline: "Fewer sessions, on purpose", subhead: "We aim to discharge you. Most people need four appointments, not a standing weekly slot.", cta: "Book an assessment", tags: ["dark", "bold", "sport", "health"], features: [["Discharge is the goal", "We tell you at assessment roughly how many sessions this should take."], ["Exercise you will do", "Three movements, filmed with you doing them, not a printed sheet."], ["Direct access", "No referral needed for most things."]], steps: [["Assessment", "Sixty minutes, including a plan and a session count."], ["Two to four sessions", "Most conditions. We say so up front if yours is different."], ["Discharge", "With a maintenance programme and an open door."]], stats: [["4", "Median sessions"], ["60 min", "Assessment"], ["92%", "Discharged"]] },
  { slug: "k-haven-mental", name: "Haven — Therapy", category: "healthcare", theme: "kiln", recipe: 2, brand: "Haven", eyebrow: "Psychological therapy", headline: "Matched properly, not to whoever is free", subhead: "A consultation with a clinical lead first, so you meet the right therapist rather than the next available one.", cta: "Book a consultation", tags: ["light", "warm", "therapy", "calm"], words: ["Matched properly", "Clinical lead first", "Evening appointments"], stats: [["1", "Consultation first"], ["9 days", "To first session"], ["24", "Clinicians"]], features: [["Matched by a clinician", "A senior therapist decides the fit, based on a proper assessment."], ["Change without awkwardness", "If it is not working, we move you. Say so and it happens."], ["Sessions at a fixed time", "The same slot every week. Routine is part of the treatment."]], steps: [["Consultation", "Fifty minutes with a clinical lead. No therapy yet."], ["Matched", "Within a week, with two options and the reasoning."], ["Weekly work", "Reviewed every six sessions, openly."]], quote: ["Being asked what had not worked before was the first time anyone had.", "Anonymous", "Client, two years"] },

  /* ──────────────────────────────────────────────────────────── fitness */
  { slug: "k-anvil-strength", name: "Anvil — Strength", category: "fitness", theme: "detonate", recipe: 5, brand: "Anvil", eyebrow: "Barbell gym", headline: "Barbells, chalk, nothing else", subhead: "A strength gym with no machines, no music policy and no classes — just coaching under the bar.", cta: "Book an induction", tags: ["dark", "bold", "gym", "strength"], words: ["Barbell", "Coached", "No contracts"], features: [["Coached, always", "Someone qualified is on the floor every hour we are open."], ["No contracts", "Monthly. Cancel by telling us."], ["Open 5am to 10pm", "Because shift work exists."]], steps: [["Induction", "Ninety minutes, one-to-one, teaching the four lifts."], ["Programme", "Written for you, adjusted every four weeks."], ["Train", "Coach on the floor whenever you are in."]], stats: [["0", "Machines"], ["17h", "Open daily"], ["1:1", "Induction"]] },
  { slug: "k-current-swim", name: "Current — Swim School", category: "fitness", theme: "beacon", recipe: 5, brand: "Current", eyebrow: "Adult swim coaching", headline: "It is never too late to learn", subhead: "Adult-only lessons in a quiet pool, taught by coaches who specialise in nervous beginners.", cta: "Book a lesson", tags: ["dark", "calm", "swim", "adult"], features: [["Adults only", "No children in the pool during lessons. It matters more than people expect."], ["Four to a lane", "Enough attention that nobody is left holding the wall."], ["Water at 30°C", "Warmer than a public pool. Cold makes fear worse."]], steps: [["First lesson free", "In the shallow end, no commitment, no swimming required."], ["Eight-week block", "Same coach, same time, same four people."], ["Open swim", "Free access outside lesson hours once you have started."]], stats: [["30°C", "Water"], ["4", "Per lane"], ["0", "Children"]] },
  { slug: "k-cadence-run", name: "Cadence — Run Club", category: "fitness", theme: "flare", recipe: 1, brand: "Cadence", eyebrow: "City run club", headline: "Nobody gets left behind", subhead: "Three paces, every Tuesday and Saturday, with a back marker who genuinely stays at the back.", cta: "Join a run", tags: ["dark", "bold", "running", "community"], gallery: ["Tuesday night", "Saturday long run", "Track session", "The bridge loop"], features: [["Three paces", "Nine, seven and five-thirty per kilometre. Everyone is somebody's pace."], ["A real back marker", "The slowest runner sets the group's speed, not the fastest."], ["Free, always", "No membership. Turn up."]], stats: [["3", "Paces"], ["2", "Runs weekly"], ["£0", "To join"]] },
  { slug: "k-summit-climb", name: "Summit — Bouldering", category: "fitness", theme: "hazard", recipe: 4, brand: "Summit", eyebrow: "Bouldering centre", headline: "Reset every Thursday", subhead: "Forty new problems a week across six grades, set by people who climb what they set.", cta: "Buy a pass", tags: ["dark", "bold", "climbing", "sport"], gallery: ["The cave", "Slab wall", "Comp wall", "Setting day"], features: [["Forty new problems weekly", "You will never climb the same wall twice in a month."], ["Six grades", "Genuinely graded for beginners, not just soft-touch expert routes."], ["Coaching included", "Technique sessions twice weekly, free with any pass."]], stats: [["40", "New problems weekly"], ["6", "Grades"], ["2", "Free sessions weekly"]] },

  /* ─────────────────────────────────────────────────────── construction */
  { slug: "k-keystone-build", name: "Keystone — Builders", category: "construction", theme: "brass", recipe: 5, brand: "Keystone", eyebrow: "Residential construction", headline: "One site at a time", subhead: "We take one project at a time, which is why we finish when we said we would.", cta: "Request a quote", tags: ["dark", "industrial", "trade", "local"], features: [["One project at a time", "The whole crew is on your site until it is done."], ["Fixed price", "Agreed after a survey, not adjusted halfway through."], ["Weekly photographs", "Every Friday, whether there was progress or not."]], steps: [["Survey", "Two hours on site before any number is quoted."], ["Fixed quote", "Itemised, with the assumptions written down."], ["Build", "Weekly photos, a named foreman, and a snagging week built in."]], stats: [["1", "Site at a time"], ["94%", "On schedule"], ["22yr", "Trading"]] },
  { slug: "k-mason-heritage", name: "Mason — Heritage Restoration", category: "construction", theme: "cellar", recipe: 4, brand: "Mason", eyebrow: "Heritage stonework", headline: "Repair, not replace", subhead: "Conservation stonemasonry on listed buildings, using lime mortar and the techniques the original masons used.", cta: "Discuss a project", tags: ["light", "craft", "heritage", "serif"], gallery: ["Cathedral tracery", "Lime pointing", "Carved replacement", "Before and after"], features: [["Lime, not cement", "Buildings this old need to breathe. Cement is why so many are failing."], ["Minimum intervention", "We replace the smallest amount of stone that solves the problem."], ["Recorded properly", "Every intervention photographed and documented for the building's file."]], stats: [["6", "Masons"], ["40yr", "Combined"], ["3", "Grade I projects"]] },
  { slug: "k-current-electric", name: "Current — Electrical", category: "construction", theme: "hazard", recipe: 5, brand: "Current", eyebrow: "Electrical contracting", headline: "Certified, first time", subhead: "Domestic and commercial electrical work that passes inspection without a second visit.", cta: "Book a survey", tags: ["dark", "bold", "trade", "local"], features: [["Certificates same day", "Signed and emailed before we leave, not chased for weeks."], ["Fixed price", "Quoted after a survey. Variations agreed in writing before work."], ["Emergency within 4 hours", "For existing customers, any hour."]], steps: [["Survey", "Free, and we will tell you if you do not need the work."], ["Written quote", "Itemised, valid 60 days."], ["Certified on completion", "Paperwork done before we pack up."]], stats: [["4h", "Emergency response"], ["100%", "First-time pass"], ["18yr", "Trading"]] },
  { slug: "k-timber-joinery", name: "Timber — Joinery", category: "construction", theme: "kiln", recipe: 4, brand: "Timber", eyebrow: "Bespoke joinery", headline: "Made to the millimetre of your wall", subhead: "Fitted furniture and staircases made in our workshop and installed by the people who made them.", cta: "Start a project", tags: ["light", "craft", "warm", "trade"], gallery: ["Workshop", "Staircase", "Fitted library", "Kitchen"], features: [["Measured on site", "Every piece cut to the actual building, not a nominal drawing."], ["Made by hand here", "One workshop, six joiners, no outsourced components."], ["Fitted by the maker", "The person who built it installs it and fixes anything that is off."]], stats: [["6", "Joiners"], ["1", "Workshop"], ["0", "Flat-pack"]] },

  /* ───────────────────────────────────────────────────────────── travel */
  { slug: "k-longitude-tours", name: "Longitude — Expeditions", category: "travel", theme: "beacon", recipe: 4, brand: "Longitude", eyebrow: "Small-group expeditions", headline: "Twelve people, no coach", subhead: "Expedition travel in groups small enough to change the plan when the weather does.", cta: "See departures", tags: ["dark", "adventure", "travel", "premium"], gallery: ["Svalbard", "Patagonia", "Kamchatka", "Greenland", "Atacama", "Faroes"], features: [["Twelve maximum", "Small enough for the guide to know everyone's name and pace."], ["Guides who live there", "Local, year-round, not flown in for the season."], ["Plans that flex", "Weather decides. The itinerary is a plan, not a promise."]], stats: [["12", "Group maximum"], ["9", "Destinations"], ["94%", "Return travellers"]] },
  { slug: "k-hearth-hotel", name: "Hearth — Country Hotel", category: "travel", theme: "cellar", recipe: 4, brand: "Hearth", eyebrow: "Fourteen rooms", headline: "No televisions, no minibar, no key cards", subhead: "A country hotel that removed everything nobody actually wanted and kept the fires lit.", cta: "Check availability", tags: ["light", "luxury", "hotel", "serif"], gallery: ["The library", "Room six", "The garden", "Breakfast"], features: [["Fourteen rooms", "Small enough that the kitchen cooks breakfast to order."], ["No screens", "Not a rule for you — there simply are not any in the rooms."], ["Dogs everywhere", "Including the dining room. Especially the dining room."]], stats: [["14", "Rooms"], ["0", "Televisions"], ["1780", "Built"]] },
  { slug: "k-transit-rail", name: "Transit — Rail Holidays", category: "travel", theme: "press", recipe: 1, brand: "Transit", eyebrow: "Travel by train", headline: "Get there slowly", subhead: "European holidays planned entirely by rail, with the connections booked and the sleepers reserved.", cta: "Plan a journey", tags: ["light", "editorial", "rail", "slow"], gallery: ["Alpine crossing", "Night train", "Coastal line", "Station hotels"], features: [["Every leg booked", "Including the connections that are impossible to book online."], ["Sleepers reserved early", "Berths open eleven months ahead and go in days. We watch for them."], ["Delay cover included", "If a connection breaks, we rebook it. From here, not from a platform."]], stats: [["0", "Flights"], ["11mo", "Booking horizon"], ["340", "Journeys planned"]] },
  { slug: "k-basecamp-lodge", name: "Basecamp — Mountain Lodge", category: "travel", theme: "lagoon", recipe: 5, brand: "Basecamp", eyebrow: "Mountain lodge", headline: "Ski out, walk back", subhead: "A lodge at the end of the lift line, with a drying room that works and dinner at seven.", cta: "Check dates", tags: ["dark", "alpine", "lodge", "sport"], features: [["On the piste", "Ski to the door. The last hundred metres are not a shuttle bus."], ["Drying room that dries", "Properly heated. Boots warm by morning, every morning."], ["Dinner at seven", "One sitting, one menu, everyone at the same table."]], steps: [["Book by the week", "Saturday to Saturday through the season."], ["Arrive to a lift pass", "Bought and waiting. We do that bit."], ["Ski", "Guiding available daily, included two days a week."]], stats: [["0m", "To the piste"], ["7pm", "Dinner"], ["22", "Beds"]] },

  /* ─────────────────────────────────────────────────────────── creative */
  { slug: "k-kiln-ceramics", name: "Kiln — Ceramics Studio", category: "creative", theme: "kiln", recipe: 4, brand: "Kiln", eyebrow: "Ceramics studio & school", headline: "Everything here was thrown by hand", subhead: "A working pottery with an open studio, evening classes and a shelf of seconds at half price.", cta: "Book a class", tags: ["light", "craft", "warm", "studio"], gallery: ["The wheel", "Glaze library", "Kiln opening", "Seconds shelf"], features: [["Open studio", "Members throw whenever we are open. Firing included."], ["Evening classes", "Six weeks, six people, one wheel each."], ["Seconds at half price", "Everything that came out of the kiln imperfect but usable."]], stats: [["6", "Per class"], ["2", "Kilns"], ["50%", "Off seconds"]] },
  { slug: "k-press-letterpress", name: "Press — Letterpress", category: "creative", theme: "newsprint", recipe: 1, brand: "Press", eyebrow: "Letterpress printing", headline: "Ink pressed into paper", subhead: "Wedding stationery, business cards and short-run books printed on presses older than anyone here.", cta: "Request a sample pack", tags: ["light", "editorial", "print", "craft"], gallery: ["Heidelberg", "Type cases", "Setting by hand", "Finished"], features: [["Real letterpress", "Metal and polymer, impression you can feel. Not digital with texture."], ["Papers you can hold", "Sample pack posted free, because screens lie about paper."], ["Short runs welcome", "Fifty cards is a job worth doing."]], stats: [["1962", "Oldest press"], ["50", "Minimum run"], ["3", "Printers"]] },
  { slug: "k-loom-textile-studio", name: "Warp — Textile Studio", category: "creative", theme: "thicket", recipe: 4, brand: "Warp", eyebrow: "Weaving studio", headline: "Cloth designed at the loom", subhead: "A studio developing woven fabric for interiors and fashion, sampling on hand looms before anything is scaled.", cta: "Commission a fabric", tags: ["light", "craft", "textile", "studio"], gallery: ["Hand looms", "Yarn store", "Sampling", "Production run"], features: [["Sampled by hand", "Every construction woven on a hand loom before a mill sees it."], ["Yarn sourced traceably", "Named mills, named farms, on the spec sheet."], ["Scaled with partners", "Production at mills we have worked with for a decade."]], stats: [["4", "Hand looms"], ["300+", "Constructions"], ["12yr", "Studio"]] },
  { slug: "k-signal-sound", name: "Signal — Recording Studio", category: "creative", theme: "flare", recipe: 1, brand: "Signal", eyebrow: "Recording & mixing", headline: "Tape, if you want it", subhead: "A live room built for bands playing together, with a desk from 1978 and a machine that still runs.", cta: "Check availability", tags: ["dark", "bold", "music", "studio"], gallery: ["Live room", "The desk", "Tape machine", "Control room"], features: [["Built for live takes", "A room where a whole band can play and still hear each other."], ["Tape or digital", "Both, on the same session, if that is what the song wants."], ["Engineer included", "Day rate includes someone who knows the room."]], stats: [["1978", "Console"], ["1", "Live room"], ["14", "Microphones on the wall"]] },

  /* ────────────────────────────────────────────────────────────── events */
  { slug: "k-assembly-conf", name: "Assembly — Conference", category: "events", theme: "voltage", recipe: 0, brand: "Assembly", eyebrow: "Two days, one track", headline: "One track, so everyone saw the same talk", subhead: "A single-track conference for engineers, because hallway conversations work better with shared references.", cta: "Get a ticket", cta2: "See speakers", tags: ["dark", "bold", "conference", "tech"], words: ["Single track", "No sponsors on stage", "Recorded free"], features: [["One track", "Everyone sees everything. The corridor conversation actually works."], ["No sponsor talks", "Sponsors get stands and dinners, not the stage."], ["Recorded and free", "Every talk online within a fortnight, no paywall."]], stats: [["1", "Track"], ["2", "Days"], ["600", "Attendees"], ["0", "Sponsor talks"]] },
  { slug: "k-vow-weddings", name: "Vow — Wedding Planning", category: "events", theme: "cellar", recipe: 5, brand: "Vow", eyebrow: "Wedding planning", headline: "We take the logistics, you keep the day", subhead: "Full planning for weddings where the couple would rather be present than project managing.", cta: "Check our dates", tags: ["light", "luxury", "wedding", "serif"], features: [["One planner throughout", "The person you meet is the person there on the day."], ["Suppliers we have used", "Recommended from experience, never from commission."], ["Timeline everyone has", "Printed, shared with every supplier, so nobody asks you."]], steps: [["Discovery", "Two hours. What you actually want, not what is expected."], ["Planning", "Monthly check-ins, everything tracked, decisions batched."], ["The day", "We are there from setup to carriages. You are not."]], stats: [["18", "Weddings a year"], ["1", "Planner per couple"], ["0", "Supplier commission"]] },
  { slug: "k-relay-festival", name: "Relay — Music Festival", category: "events", theme: "siren", recipe: 1, brand: "Relay", eyebrow: "Three stages, one weekend", headline: "Small enough to see everything", subhead: "Four thousand people, three stages, and a running order designed so the good clashes never happen.", cta: "Buy tickets", tags: ["dark", "bold", "music", "festival"], gallery: ["Main stage", "The barn", "Late tent", "Sunday"], features: [["No clashes that matter", "Running order set so headline sets never overlap."], ["Four thousand capacity", "You can cross the site in eight minutes."], ["Camping included", "In the ticket price, not a surprise add-on."]], stats: [["4,000", "Capacity"], ["3", "Stages"], ["8 min", "Across site"]] },
  { slug: "k-forum-summit", name: "Forum — Industry Summit", category: "events", theme: "alarm", recipe: 3, brand: "Forum", eyebrow: "Invitation only", headline: "Two hundred people who make decisions", subhead: "An invitation-only summit with no press, no recording and a Chatham House rule that is enforced.", cta: "Request an invitation", cta2: "See the format", tags: ["light", "luxury", "business", "serif"], features: [["No recording", "Nothing is filmed. It changes what people are willing to say."], ["Chatham House, enforced", "Attributed leaks end the invitation. It has happened twice."], ["Curated tables", "Seating planned so every dinner puts you next to someone useful."]], stats: [["200", "Attendees"], ["0", "Press"], ["2", "Days"], ["14yr", "Running"]] },

  /* ─────────────────────────────────────────────────────────── real-estate */
  { slug: "k-harbourside-estate", name: "Harbourside — Estate Agency", category: "real-estate", theme: "yves", recipe: 5, brand: "Harbourside", eyebrow: "Estate agency", headline: "We will tell you what it is worth", subhead: "Not what you want to hear. Honest valuations, because an overpriced listing helps nobody.", cta: "Book a valuation", tags: ["light", "luxury", "property", "serif"], features: [["Honest valuations", "Evidenced with comparables. We will decline an instruction we cannot deliver."], ["Photographed properly", "A professional photographer, and we wait for the right light."], ["One agent throughout", "Valuation to completion, the same person."]], steps: [["Valuation", "In person, with the comparables written down."], ["Marketing", "Photography, floorplan and copy before anything goes live."], ["Through to completion", "We chase the chain, not you."]], stats: [["97%", "Of asking achieved"], ["31", "Median days"], ["1", "Agent per sale"]] },
  { slug: "k-northgate-devt", name: "Northgate — Development", category: "real-estate", theme: "brass", recipe: 3, brand: "Northgate", eyebrow: "Residential development", headline: "Built to be lived in for eighty years", subhead: "Housing designed for the second owner as much as the first, with fabric specified above regulation.", cta: "Register interest", cta2: "See specification", tags: ["dark", "industrial", "property", "premium"], features: [["Fabric first", "Insulation and airtightness well past building regulations, before any technology."], ["Costs published", "Predicted running costs for every unit, on the floorplan."], ["Ten-year snagging", "Not two. We expect to be here."]], stats: [["A", "EPC rating"], ["£380", "Predicted annual heating"], ["10yr", "Snagging cover"], ["48", "Homes"]] },
  { slug: "k-atlas-commercial", name: "Atlas — Commercial Property", category: "real-estate", theme: "cadet", recipe: 0, brand: "Atlas", eyebrow: "Commercial agency", headline: "Space that fits how you work now", subhead: "Office and industrial agency for companies whose requirements changed and whose lease did not.", cta: "Discuss a requirement", cta2: "Current availability", tags: ["dark", "professional", "commercial", "b2b"], words: ["Office", "Industrial", "Lease advisory"], features: [["Requirement first", "We start with how your team actually works, not with what is available."], ["Lease advisory", "Break clauses, rent reviews and dilapidations, before they bite."], ["Off-market access", "Roughly a third of what we transact never reaches a portal."]], stats: [["1/3", "Off market"], ["2.4M", "Sq ft transacted"], ["19yr", "Trading"]] },
  { slug: "k-quay-lettings", name: "Quay — Lettings", category: "real-estate", theme: "lagoon", recipe: 5, brand: "Quay", eyebrow: "Residential lettings", headline: "Repairs fixed in days, not months", subhead: "Managed lettings with a maintenance team on staff, because tenants who are looked after stay.", cta: "List a property", tags: ["dark", "property", "modern", "service"], features: [["Maintenance in-house", "Our own team. No waiting for a contractor to call back."], ["Deposits protected properly", "Registered within 48 hours, every time, with the certificate sent to both sides."], ["Tenants who stay", "Median tenancy of three years. Voids are what actually cost landlords."]], steps: [["Valuation and photographs", "Both within a week of instruction."], ["Referenced properly", "Employment, affordability and a previous landlord call."], ["Managed", "Rent collected, repairs handled, statements monthly."]], stats: [["3yr", "Median tenancy"], ["48h", "Deposit registered"], ["2 days", "Median repair"]] },

  /* ─────────────────────────────────────────────────────────────── blog */
  { slug: "k-margins-blog", name: "Margins — Essays", category: "blog", theme: "newsprint", recipe: 2, brand: "Margins", eyebrow: "Essays, fortnightly", headline: "Long arguments about small things", subhead: "An essay every other Tuesday on software, cities and the places the two meet.", cta: "Subscribe", tags: ["light", "editorial", "writing", "typography"], words: ["Fortnightly", "Long arguments", "Small things"], stats: [["112", "Essays"], ["2 wks", "Between issues"], ["0", "Sponsored posts"]], features: [["Fortnightly, reliably", "Every other Tuesday for six years. Nothing skipped."], ["No advertising", "Reader-funded, so nothing is written to please anyone else."], ["Archive open", "Everything, free, forever, without an email wall."]], steps: [["Read anything", "The archive is open. Start wherever."], ["Subscribe if it lands", "Free by email, or pay if you want to."], ["Reply", "Every email is read by the person who wrote the essay."]], quote: ["The only newsletter I have never once archived unread.", "Marco Reyes", "Reader since 2019"] },
  { slug: "k-dispatch-mag", name: "Dispatch — Magazine", category: "blog", theme: "press", recipe: 1, brand: "Dispatch", eyebrow: "Quarterly magazine", headline: "Four issues a year, in print", subhead: "Long-form reporting on industry, labour and the built environment, printed because it deserves to be.", cta: "Subscribe", tags: ["light", "editorial", "print", "magazine"], gallery: ["Issue 14", "The foundry story", "Photography", "Spreads"], features: [["Print first", "Designed for paper. The website is the archive, not the product."], ["Reported properly", "Six weeks minimum per feature. Some take a year."], ["Photographers commissioned", "Never stock. Every image is shot for the story."]], stats: [["4", "Issues a year"], ["132", "Pages"], ["6", "Years"]] },
  { slug: "k-frame-review", name: "Frame — Film Criticism", category: "blog", theme: "cellar", recipe: 2, brand: "Frame", eyebrow: "Film writing", headline: "Criticism, not consumer advice", subhead: "Essays about what films are doing, from writers who assume you have already seen it.", cta: "Read the latest", tags: ["light", "serif", "film", "editorial"], words: ["No star ratings", "Spoilers assumed", "Criticism, not advice"], stats: [["640", "Reviews"], ["0", "Star ratings"], ["8yr", "Publishing"]], features: [["Spoilers assumed", "We write about the whole film, because that is where the argument is."], ["No star ratings", "A number is not an argument."], ["Archive by director", "Everything we have written, organised how you would look for it."]], steps: [["Read one", "Start with the most recent, or by director."], ["Subscribe", "Weekly, one essay, nothing else."], ["Argue back", "The comments are moderated and the writers are in them."]], quote: ["The rare film site that trusts you to have watched the thing.", "Ana Duarte", "Subscriber"] },
  { slug: "k-thread-newsletter", name: "Thread — Weekly", category: "blog", theme: "voltage", recipe: 2, brand: "Thread", eyebrow: "Weekly, Thursdays", headline: "Five links and why they matter", subhead: "A short weekly on engineering leadership, curated by someone doing the job.", cta: "Subscribe free", tags: ["dark", "bold", "newsletter", "tech"], quote: ["The only newsletter I read on the day it arrives. Five links, no filler, and the why is the whole point.", "Priya Raman", "VP Engineering, Northgate"], words: ["Five links", "Every Thursday", "And why they matter"], features: [["Five links", "Never more. Editing is the whole value."], ["Why, not just what", "Two sentences on why each one is worth your time."], ["Under four minutes", "Measured. If it runs long, something gets cut."]], steps: [["Subscribe", "Free, Thursdays, one email."], ["Read in four minutes", "Or skim the five headlines in thirty seconds."], ["Unsubscribe easily", "One click, no survey, no guilt."]], stats: [["5", "Links weekly"], ["3m 40s", "Median read"], ["21,000", "Subscribers"]] },

  /* ───────────────────────────────────────────────────────────── gaming */
  { slug: "k-pixelforge-studio", name: "Pixelforge — Game Studio", category: "gaming", theme: "siren", recipe: 1, brand: "Pixelforge", eyebrow: "Independent game studio", headline: "Small games, finished", subhead: "A nine-person studio that ships eighteen-month games instead of announcing five-year ones.", cta: "See our games", tags: ["dark", "bold", "games", "studio"], gallery: ["Verge", "Tidewalker", "Lantern", "Northbound", "Prototype", "The office"], features: [["Eighteen months", "Scoped to finish. We have never cancelled a project."], ["Nine people", "Everyone touches the game. Nobody manages managers."], ["No crunch", "Four shipped titles, zero crunch weeks. The scope is the answer."]], stats: [["4", "Games shipped"], ["9", "People"], ["0", "Crunch weeks"]] },
  { slug: "k-arena-esports", name: "Arena — Esports", category: "gaming", theme: "detonate", recipe: 0, brand: "Arena", eyebrow: "Tier-one competitive team", headline: "Nine players, four titles, one loud room", subhead: "Founded in a university dorm in 2018, currently ranked third in the world.", cta: "Watch live", cta2: "Meet the roster", tags: ["dark", "bold", "esports", "team"], words: ["Majors", "Ranked #3", "Thursdays 19:00"], features: [["Spring Major — 1st", "Beat Hyperion 3–1 after dropping the opening map."], ["Continental Cup — 2nd", "Lost the decider in overtime. We are not over it."], ["Invitational — 1st", "Nine maps, one dropped. Cleanest run of the year."]], stats: [["4", "Major titles"], ["218", "Matches won"], ["1.4M", "Followers"], ["$2.8M", "Prize money"]], quote: ["The most disciplined team in the league. Their mid-round calling is a level above.", "Ana Duarte", "Analyst, Circuit Weekly"] },
  { slug: "k-static-streamer", name: "Static — Streamer", category: "gaming", theme: "ultramarine", recipe: 1, brand: "Static", eyebrow: "Live five nights a week", headline: "Mostly strategy games, occasionally chaos", subhead: "Five nights a week, no sponsor reads, and a chat that is actually moderated.", cta: "Follow", tags: ["dark", "bold", "streaming", "community"], gallery: ["The setup", "Community night", "Charity marathon", "Clips"], features: [["Five nights weekly", "Same hours, so nobody has to guess."], ["Moderated properly", "Three mods on every stream. It is why the chat is worth reading."], ["No sponsor reads", "Ever. Supported by subs and nothing else."]], stats: [["5", "Nights weekly"], ["41k", "Followers"], ["0", "Sponsor reads"]] },
  { slug: "k-clan-servers", name: "Clan — Game Servers", category: "gaming", theme: "console", recipe: 3, brand: "Clan", eyebrow: "Game server hosting", headline: "Servers that stay up on launch night", subhead: "Dedicated game hosting with capacity reserved for the nights everyone actually plays.", cta: "Start a server", cta2: "See locations", tags: ["dark", "terminal", "hosting", "games"], words: ["Instant deploy", "DDoS filtered", "Mod support"], features: [["Deployed in ninety seconds", "Configured, modded and running before your friends join the call."], ["Capacity held back", "We reserve headroom for launch weekends rather than overselling."], ["Mods, properly", "One-click for the popular ones, SFTP for everything else."]], stats: [["90s", "To live"], ["18", "Locations"], ["99.98%", "Uptime"], ["0", "Overselling"]] },

  /* ───────────────────────────────────────────────────────── technology */
  { slug: "k-corvus-security", name: "Corvus — Security", category: "technology", theme: "alarm", recipe: 3, brand: "Corvus", eyebrow: "Offensive security", headline: "We break it before someone else does", subhead: "Penetration testing and red teaming with reports your engineers can act on the same week.", cta: "Scope an engagement", cta2: "See a sample report", tags: ["dark", "bold", "security", "b2b"], words: ["Pentest", "Red team", "Reproducible"], features: [["Reproducible findings", "Every issue with the exact request that triggered it."], ["Ranked by reachability", "Exploitable from the internet first, theoretical last."], ["Retest included", "Ninety days to fix, then we verify, at no extra cost."]], stats: [["90 days", "Free retest"], ["48h", "Critical disclosure"], ["12", "Testers"], ["0", "Automated-only reports"]] },
  { slug: "k-vertex-api", name: "Vertex — Edge API", category: "technology", theme: "beacon", recipe: 3, brand: "Vertex", eyebrow: "Edge compute", headline: "One endpoint, every region, no cold starts", subhead: "Deploy request handlers to two hundred locations and route each user to the nearest healthy one.", cta: "Deploy a function", cta2: "Read the reference", tags: ["dark", "technical", "infra", "api"], words: ["200 regions", "No cold start", "Typed SDKs"], features: [["Global by default", "Your code runs where your users are, with no region picker."], ["Sub-millisecond boot", "Isolates, not containers. Cold start is not a concept here."], ["Typed clients generated", "SDKs built from your schema on every deploy."], ["Per-route caching", "With tag invalidation, at the edge, included."]], stats: [["200", "Locations"], ["0.4ms", "Boot"], ["99.99%", "Uptime"], ["14", "Languages"]] },
  { slug: "k-lattice-ml", name: "Lattice — ML Platform", category: "technology", theme: "cadet", recipe: 0, brand: "Lattice", eyebrow: "Machine learning platform", headline: "From notebook to production without a rewrite", subhead: "The same code trains, evaluates and serves, so the model in production is the one you tested.", cta: "Book a demo", cta2: "Read the docs", tags: ["dark", "technical", "ml", "b2b"], words: ["Reproducible", "Versioned", "Served"], features: [["One artefact", "The thing you trained is the thing that serves. No reimplementation."], ["Versioned everything", "Data, code and weights pinned together, reproducible a year later."], ["Evaluation as a gate", "Models cannot deploy past a threshold you set."], ["Drift you find out about", "Alerts on input distribution, not just on errors."]], stats: [["1", "Artefact"], ["100%", "Reproducible runs"], ["340", "Teams"], ["9 min", "Notebook to endpoint"]] },
  { slug: "k-relay-iot", name: "Relay — Device Fleet", category: "technology", theme: "hazard", recipe: 3, brand: "Relay", eyebrow: "Connected device management", headline: "Update ten thousand devices without bricking one", subhead: "Staged firmware rollout with automatic rollback for hardware you cannot physically reach.", cta: "Talk to us", cta2: "See the protocol", tags: ["dark", "bold", "iot", "hardware"], words: ["OTA", "Staged", "Rollback", "Offline-safe"], features: [["Staged rollout", "One percent, then ten, then the fleet — halted automatically on failure."], ["Rollback that works offline", "A/B partitions, so a bad image never leaves a device dead."], ["Fleet health", "Battery, connectivity and version, per device, on one screen."]], stats: [["0", "Devices bricked"], ["2.4M", "Under management"], ["1%", "Canary stage"], ["A/B", "Partitions"]] },

  /* ────────────────────────────────────────────────────────── business */
  { slug: "k-ridgeway-consult", name: "Ridgeway — Consulting", category: "business", theme: "yves", recipe: 3, brand: "Ridgeway", eyebrow: "Operations consulting", headline: "We work on the floor, not in the boardroom", subhead: "Operations consulting for manufacturers, spent mostly on the shop floor with the people doing the work.", cta: "Arrange a visit", cta2: "How we work", tags: ["light", "professional", "consulting", "serif"], features: [["On the floor", "Most of an engagement is spent where the work happens."], ["Implemented, not recommended", "We stay until the change holds, usually a quarter past the report."], ["Measured before and after", "The same measure, taken the same way, both times."]], stats: [["78%", "Changes still in place at 12 months"], ["£14M", "Cost removed"], ["31", "Sites"], ["22yr", "Practising"]] },
  { slug: "k-halcyon-legal", name: "Halcyon — Commercial Law", category: "business", theme: "cellar", recipe: 3, brand: "Halcyon", eyebrow: "Commercial law", headline: "Fixed fees, plain drafting", subhead: "Commercial contracts written to be understood by the people who have to follow them.", cta: "Request a quote", cta2: "Our fee scale", tags: ["light", "luxury", "legal", "serif"], features: [["Fixed fee", "Quoted before the work. No six-minute billing units."], ["Plain drafting", "Contracts your operations team can read without us translating."], ["Published fee scale", "On the website. Most firms will not do this."]], stats: [["£0", "Hourly billing"], ["48h", "Median turnaround"], ["9", "Solicitors"], ["1998", "Founded"]] },
  { slug: "k-anchor-hr", name: "Anchor — People Ops", category: "business", theme: "thicket", recipe: 5, brand: "Anchor", eyebrow: "Outsourced people operations", headline: "HR for companies of eleven to sixty", subhead: "The stage where you need proper employment practice but cannot justify a full-time HR director.", cta: "Book a call", tags: ["light", "professional", "hr", "service"], features: [["Contracts and handbooks", "Compliant, readable, and specific to how you actually work."], ["Difficult conversations", "We sit in on them. That is usually why people call."], ["Fixed monthly fee", "By headcount band. Advice is never metered."]], steps: [["Audit", "Contracts, policies and practice, against what the law requires."], ["Fix the gaps", "Prioritised by risk, not alphabetically."], ["Ongoing", "Named adviser, unlimited questions, monthly fee."]], stats: [["11–60", "Headcount served"], ["1", "Named adviser"], ["0", "Metered advice"]] },
  { slug: "k-fathom-research", name: "Fathom — Market Research", category: "business", theme: "press", recipe: 2, brand: "Fathom", eyebrow: "Qualitative research", headline: "Twenty conversations beat two thousand responses", subhead: "Qualitative research for companies that need to understand a decision, not measure one.", cta: "Discuss a study", tags: ["light", "editorial", "research", "b2b"], words: ["Twenty conversations", "Not two thousand", "Findings in three weeks"], stats: [["20", "Conversations"], ["3 wks", "To findings"], ["0", "Survey panels"]], features: [["Depth over volume", "Twenty long interviews tell you why. A survey only tells you how many."], ["Recorded and quoted", "Every finding traceable to who said it and when."], ["Findings you can act on", "Written as decisions to make, not observations to admire."]], steps: [["Frame the decision", "What will you do differently depending on the answer?"], ["Twenty conversations", "Recruited to a screener we agree, recorded, transcribed."], ["Debrief, then write", "Findings presented live before the document exists."]], quote: ["The debrief changed the roadmap in the room. The report was almost a formality.", "Tom Alvarez", "Product Director, Orbit"] },

  /* ────────────────────────────────────────────────────── landing pages */
  { slug: "k-convert-launch", name: "Convert — Product Launch", category: "landing-page", theme: "flare", recipe: 1, brand: "Convert", eyebrow: "Launching Tuesday", headline: "One page. One decision", subhead: "A launch page built to do exactly one thing, with everything that does not serve it removed.", cta: "Get early access", tags: ["dark", "bold", "launch", "conversion"], gallery: ["The product", "In use", "Detail", "Packaging"], features: [["One action", "Every element on the page serves the single decision."], ["Proof above the fold", "Numbers and names before the pitch, not after."], ["Nothing to explore", "No nav, no footer links, no way to wander off."]], stats: [["1", "Call to action"], ["11.4%", "Median conversion"], ["0", "Nav links"]] },
  { slug: "k-signal-waitlist", name: "Signal — Waitlist", category: "landing-page", theme: "voltage", recipe: 1, brand: "Signal", eyebrow: "Private beta", headline: "Two thousand people are already waiting", subhead: "A waitlist page that tells the truth about where you are in the queue and when you will get in.", cta: "Join the list", tags: ["dark", "bold", "waitlist", "startup"], gallery: ["Early build", "Dashboard", "Mobile", "The team"], features: [["Position shown", "Where you are, honestly, updated weekly."], ["Referrals move you up", "Two places per invite. Stated plainly, not gamified."], ["Batched invites", "Fifty a week, so support can keep up."]], stats: [["2,140", "Waiting"], ["50", "Invited weekly"], ["+2", "Places per referral"]] },
  { slug: "k-offer-course", name: "Offer — Course Launch", category: "landing-page", theme: "ultramarine", recipe: 1, brand: "Offer", eyebrow: "Enrolment closes Friday", headline: "Six weeks, six people, one wheel each", subhead: "A landing page for a course that genuinely has limited places, with the count shown honestly.", cta: "Enrol now", tags: ["light", "warm", "course", "conversion"], gallery: ["The studio", "Week one", "Firing", "Final pieces"], features: [["Real scarcity", "Six places because there are six wheels, not because scarcity converts."], ["What you leave with", "Listed specifically, including the pieces you take home."], ["Refund until week two", "Full, no questions, if it is not for you."]], stats: [["6", "Places"], ["6", "Weeks"], ["2", "Week refund window"]] },
  { slug: "k-pledge-campaign", name: "Pledge — Campaign", category: "landing-page", theme: "alarm", recipe: 1, brand: "Pledge", eyebrow: "Campaign closes in 9 days", headline: "£84,000 of £120,000", subhead: "A campaign page that leads with the number and shows exactly what each tier pays for.", cta: "Back this project", tags: ["dark", "bold", "campaign", "nonprofit"], gallery: ["The site", "Volunteers", "Plans", "Progress"], features: [["Costed tiers", "Each amount tied to a specific thing it buys."], ["Progress, honestly", "Including the weeks nothing moved."], ["Refunded if we miss", "All or nothing. Nobody pays for a half-built thing."]], stats: [["£84,000", "Raised"], ["£120,000", "Target"], ["9", "Days left"], ["1,240", "Backers"]] },

  /* ─────────────────────────────────────────────────────────── personal */
  { slug: "k-okonkwo-cv", name: "Okonkwo — CV", category: "personal", theme: "newsprint", recipe: 2, brand: "James Okonkwo", eyebrow: "Platform engineering", headline: "I make deploys boring", subhead: "Infrastructure engineer working on the unglamorous things that stop pagers going off at 3am.", cta: "Download CV", tags: ["light", "typography", "personal", "minimal"], words: ["Platform engineering", "Boring deploys", "Quiet pagers"], stats: [["11yr", "Engineering"], ["4", "Platform teams"], ["3am", "Pager, quiet"]], features: [["Platform engineering", "Kubernetes, Terraform, and the internal tooling that makes them survivable."], ["Incident practice", "I run the postmortems. They are the most useful hour of any quarter."], ["Documentation", "Written, maintained, and actually read. Rare enough to list."]], steps: [["Head of Platform · Northline · 2021—now", "Rebuilt the developer platform. Deploy frequency up 4x, incidents halved."], ["Senior SRE · Basalt · 2017—2021", "On-call for a payments platform. Learned most of what I know here."], ["Engineer · Corvus · 2013—2017", "First infrastructure hire. Built the thing I later had to replace."]], quote: ["James left better documentation than most companies have staff to write.", "Anke Vogel", "CTO, Northline"] },
  { slug: "k-marlowe-speaker", name: "Marlowe — Speaker", category: "personal", theme: "cellar", recipe: 2, brand: "Ida Marlowe", eyebrow: "Speaking & workshops", headline: "I talk about the parts people leave out", subhead: "Keynotes and workshops on design practice, delivered without a single stock photograph.", cta: "Check availability", tags: ["light", "serif", "speaking", "personal"], quote: ["Ida gave the only conference talk that year people were still arguing about at dinner.", "Samir Haddad", "Programme chair, Interval"], words: ["Keynotes", "Workshops", "The parts left out"], features: [["Keynotes", "Forty minutes, written for your audience, not recycled."], ["Workshops", "Half or full day, capped at twenty-four people."], ["No stock photography", "Ever. It is sort of the point."]], steps: [["Tell me the room", "Who is there, what they came for, what they already believe."], ["I write it", "New material. I do not have a circuit talk."], ["Rehearse with you", "One run-through with the organiser, a week ahead."]], stats: [["40 min", "Keynote"], ["24", "Workshop cap"], ["61", "Talks given"]] },
  { slug: "k-ashcroft-consult", name: "Ashcroft — Freelance", category: "personal", theme: "voltage", recipe: 2, brand: "Ren Ashcroft", eyebrow: "Available from March", headline: "One client at a time", subhead: "Freelance product design, taken one engagement at a time so nobody is queued behind anyone.", cta: "Check availability", tags: ["dark", "bold", "freelance", "personal"], quote: ["Booking Ren means you get Ren, not a team you were not introduced to. We had the whole design done in five weeks.", "Dana Whitfield", "Founder, Kestrel"], words: ["One client", "At a time", "Available from March"], features: [["One at a time", "You get the whole week, not a slice of five."], ["Fixed weekly rate", "Not hourly. It stops both of us optimising the wrong thing."], ["Two-week minimum", "Less than that and I am still learning your product."]], steps: [["Call", "Thirty minutes. What you need, whether I am right for it."], ["Two-week block", "Booked and paid up front. Extended weekly after that."], ["Handover", "Files, rationale and a walkthrough with whoever inherits it."]], stats: [["1", "Client at a time"], ["2wk", "Minimum"], ["12yr", "Experience"]] },
  { slug: "k-vaquero-links", name: "Vaquero — Links", category: "personal", theme: "siren", recipe: 2, brand: "Vaquero", eyebrow: "Everything in one place", headline: "All of it, one page", subhead: "A link page that is actually designed, rather than a list of buttons on a gradient.", cta: "Get in touch", tags: ["dark", "bold", "links", "personal"], quote: ["It replaced four different link pages and finally looks like the rest of our brand.", "Toby Nkemelu", "Manager, Halston Records"], words: ["Everything", "One page", "Actually designed"], features: [["The work", "Reel, selected projects and the studio site."], ["Writing", "Occasional essays on motion and production."], ["Contact", "One address, answered personally, usually same day."]], steps: [["Watch the reel", "Ninety seconds, updated quarterly."], ["Read something", "If you would rather know how I think than what I made."], ["Say hello", "Direct email. No form."]], stats: [["90s", "Reel"], ["1", "Email address"], ["24h", "Reply time"]] },
];

import { SEEDS_TWO } from "./catalog-kinetic-2";

export const CATALOG_KINETIC: TemplateDef[] = [...SEEDS, ...SEEDS_TWO].map(buildKinetic);
