import type { TemplateDef } from "./catalog";

/**
 * Second wave of the bundled catalogue.
 *
 * Written to fill the thin categories from the first pass — photography, trades,
 * finance, health, travel, events — and to spread the theme and layout
 * combinations further apart so the marketplace does not read as one design
 * recoloured thirty times.
 */

const img = (seed: string, w = 1400, h = 900) => `https://picsum.photos/seed/${seed}/${w}/${h}`;
const f = (title: string, body: string, icon?: string) => ({ title, body, icon });
const q = (quote: string, name: string, role: string) => ({ quote, name, role });
const faq = (question: string, answer: string) => ({ q: question, a: answer });

export const CATALOG_EXTRA: TemplateDef[] = [
  /* ───────────────────────────────────────────────────────── photography */
  {
    slug: "vessel-wedding-photography",
    name: "Vessel — Wedding Photography",
    category: "photography",
    theme: "blush",
    description: "Soft, romantic photography site with packages and an enquiry form.",
    tags: ["photography", "wedding", "light", "romantic"],
    layout: ["nav:centered", "hero:cover", "block:gallery", "block:pricing", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Vessel",
      nav: [{ label: "Portfolio", href: "#work" }, { label: "Packages", href: "#pricing" }, { label: "Kind words", href: "#testimonials" }, { label: "Enquire", href: "#contact" }],
      eyebrow: "Now booking next season",
      headline: "The day, remembered honestly",
      subhead: "Documentary wedding photography — no stiff posing, no shot list you have to perform.",
      ctaPrimary: { label: "Check your date", href: "#contact" },
      ctaSecondary: { label: "See the work", href: "#work" },
      heroImage: img("wedding-cover-2", 1800, 1100),
      gallery: [
        { src: img("wed-a", 800, 600), caption: "Marta & Joan — Girona" },
        { src: img("wed-b", 800, 600), caption: "Ellie & Sam — Yorkshire" },
        { src: img("wed-c", 800, 600), caption: "Noor & Idris — Marrakesh" },
        { src: img("wed-d", 800, 600), caption: "First look, golden hour" },
        { src: img("wed-e", 800, 600), caption: "The speeches" },
        { src: img("wed-f", 800, 600), caption: "Last dance" },
      ],
      plans: [
        { name: "Half day", price: "$1,600", cadence: "6 hours", cta: "Enquire", features: ["Ceremony and portraits", "300+ edited images", "Online gallery"] },
        { name: "Full day", price: "$2,900", cadence: "12 hours", cta: "Enquire", featured: true, features: ["Prep to last dance", "700+ edited images", "Online gallery", "Print box"] },
        { name: "Weekend", price: "$4,800", cadence: "2 days", cta: "Enquire", features: ["Rehearsal and wedding", "Second shooter", "Album included"] },
      ],
      quotes: [
        q("We forgot she was there, which is exactly what we wanted.", "Marta & Joan", "Girona, 2024"),
        q("Photos that look like the day actually felt.", "Ellie & Sam", "Yorkshire, 2023"),
      ],
      contact: { email: "hello@example.com", phone: "+44 7700 900321", address: "Based in Bristol, travelling anywhere", hours: "Replies within two days" },
      footerNote: "Twelve weddings a year, so each one gets proper attention.",
    },
  },
  {
    slug: "grain-studio-portraits",
    name: "Grain — Portrait Studio",
    category: "photography",
    theme: "paper",
    description: "Bright, editorial portrait studio page with session types and booking.",
    tags: ["photography", "portrait", "light", "studio"],
    layout: ["nav:minimal", "hero:editorial", "block:gallery", "block:steps", "block:pricing", "block:contact", "block:footer"],
    data: {
      brand: "Grain",
      nav: [{ label: "Work", href: "#work" }, { label: "Sessions", href: "#pricing" }, { label: "Book", href: "#contact" }],
      eyebrow: "Studio portraits",
      headline: "A photograph that looks like you on a good day",
      subhead: "Headshots, family sittings and personal portraits, made in a daylight studio in about an hour.",
      ctaPrimary: { label: "Book a session", href: "#contact" },
      heroImage: img("portrait-hero", 900, 1200),
      gallery: [
        { src: img("port-1", 800, 600), caption: "Headshot — natural light" },
        { src: img("port-2", 800, 600), caption: "Family sitting" },
        { src: img("port-3", 800, 600), caption: "Personal branding set" },
        { src: img("port-4", 800, 600), caption: "Studio, morning" },
        { src: img("port-5", 800, 600), caption: "Black and white series" },
        { src: img("port-6", 800, 600), caption: "Editorial commission" },
      ],
      steps: [
        f("Book", "Pick a slot online. Weekday mornings have the best light."),
        f("Sit", "About an hour. Bring two changes and we will guide the rest."),
        f("Choose", "Proofs within three days, retouched finals within a week."),
      ],
      plans: [
        { name: "Headshot", price: "$240", cadence: "45 min", cta: "Book", features: ["One look", "Five retouched images", "Web and print files"] },
        { name: "Portrait", price: "$420", cadence: "90 min", cta: "Book", featured: true, features: ["Three looks", "Fifteen retouched images", "Full gallery", "Print credit"] },
      ],
      contact: { email: "studio@example.com", phone: "+1 (555) 402-1188", address: "Unit 5, Daylight Studios", hours: "Tue — Sat, 9am to 5pm" },
      footerNote: "Daylight studio. No flash unless you ask for it.",
    },
  },

  /* ───────────────────────────────────────────────────────── construction */
  {
    slug: "form-interior-design",
    name: "Form — Interior Design",
    category: "construction",
    theme: "linen",
    description: "Calm interior design studio with project gallery and a clear process.",
    tags: ["interior", "design", "light", "studio"],
    layout: ["nav:centered", "hero:editorial", "block:gallery", "block:steps", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Form",
      nav: [{ label: "Projects", href: "#work" }, { label: "Process", href: "#how" }, { label: "Studio", href: "#testimonials" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Interior design and styling",
      headline: "Rooms that work before they impress",
      subhead: "Residential interiors planned around how you actually live — light, storage, and where people end up standing.",
      ctaPrimary: { label: "Start a project", href: "#contact" },
      heroImage: img("interior-hero", 900, 1200),
      gallery: [
        { src: img("int-1", 800, 600), caption: "Victorian terrace — full refit" },
        { src: img("int-2", 800, 600), caption: "Coastal house — kitchen and living" },
        { src: img("int-3", 800, 600), caption: "Apartment — small space planning" },
      ],
      steps: [
        f("Survey", "We measure, photograph and listen. Two hours on site."),
        f("Concept", "Plans, palette and a costed schedule before anything is ordered."),
        f("Delivery", "We manage trades, deliveries and the snagging list."),
      ],
      quotes: [
        q("They talked us out of the extension and fixed the layout instead.", "Ruth Palmer", "Homeowner"),
        q("Every measurement was right. That is rarer than it should be.", "Alex Nowak", "Contractor"),
      ],
      contact: { email: "studio@example.com", phone: "+44 20 7946 0777", address: "Second floor, 18 Hoxton Square", hours: "Mon — Thu, 9:30am to 5:30pm" },
      footerNote: "Small studio. Four projects at a time.",
    },
  },
  {
    slug: "summit-roofing",
    name: "Summit — Roofing",
    category: "construction",
    theme: "slate",
    description: "Straightforward trades page with services, guarantees and free quotes.",
    tags: ["roofing", "trades", "light", "local"],
    layout: ["nav:simple", "hero:split", "block:stats", "block:featureGrid", "block:gallery", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Summit Roofing",
      nav: [{ label: "Services", href: "#features" }, { label: "Work", href: "#work" }, { label: "FAQ", href: "#faq" }, { label: "Free quote", href: "#contact" }],
      eyebrow: "24-hour emergency call-out",
      headline: "Fixed properly, guaranteed for a decade",
      subhead: "Flat roofs, pitched roofs, gutters and emergency repairs across the county. Free quotes, no pressure.",
      ctaPrimary: { label: "Get a free quote", href: "#contact" },
      ctaSecondary: { label: "See our services", href: "#features" },
      heroImage: img("roofing-hero", 1000, 1100),
      stats: [
        { value: "10 yr", label: "Workmanship guarantee" },
        { value: "24 hr", label: "Emergency response" },
        { value: "2,100+", label: "Roofs completed" },
        { value: "4.9", label: "Average review score" },
      ],
      features: [
        f("Repairs", "Leaks traced properly, not patched and hoped for.", "shield"),
        f("Replacement", "Full strip and re-roof with a written specification.", "layers"),
        f("Gutters and fascia", "Cleaned, repaired or replaced while we are up there.", "bolt"),
      ],
      gallery: [
        { src: img("roof-1", 800, 600), caption: "Slate re-roof, Victorian semi" },
        { src: img("roof-2", 800, 600), caption: "Flat roof replacement, EPDM" },
        { src: img("roof-3", 800, 600), caption: "Storm damage repair" },
      ],
      faq: [
        faq("Do you charge for quotes?", "No. We visit, inspect and give you a written price with no obligation."),
        faq("Are you insured?", "Fully — public liability and workmanship cover, certificates available on request."),
      ],
      contact: { email: "quotes@example.com", phone: "+44 1273 555 010", address: "Yard 4, Station Road", hours: "Mon — Sat 7am to 6pm · Emergencies 24/7" },
      footerNote: "Family run since 1994. Checked trader scheme member.",
    },
  },

  /* ───────────────────────────────────────────────────────────── finance */
  {
    slug: "anchor-insurance",
    name: "Anchor — Insurance Broker",
    category: "finance",
    theme: "slate",
    description: "Reassuring broker page with cover types, claims process and quote request.",
    tags: ["insurance", "broker", "light", "services"],
    layout: ["nav:simple", "hero:split", "block:featureGrid", "block:steps", "block:testimonials", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Anchor",
      nav: [{ label: "Cover", href: "#features" }, { label: "Claims", href: "#how" }, { label: "FAQ", href: "#faq" }, { label: "Get a quote", href: "#contact" }],
      eyebrow: "Independent broker",
      headline: "Cover that pays out when it matters",
      subhead: "We read the policy wording so you do not have to, and we handle the claim when something goes wrong.",
      ctaPrimary: { label: "Get a quote", href: "#contact" },
      ctaSecondary: { label: "How claims work", href: "#how" },
      heroImage: img("insurance-hero", 1000, 1100),
      features: [
        f("Business", "Liability, premises, cyber and professional indemnity.", "shield"),
        f("Property", "Landlord, commercial and unoccupied property cover.", "lock"),
        f("Specialist", "Trades, events and anything a comparison site refuses.", "spark"),
      ],
      steps: [
        f("Tell us the risk", "A short call, not a thirty-field form."),
        f("We shop the market", "Twenty insurers, one recommendation with the reasoning."),
        f("We handle claims", "You call us, not a call centre."),
      ],
      quotes: [
        q("They found an exclusion our previous broker missed for six years.", "Denise Aluko", "Café owner"),
        q("Claim settled in eleven days.", "Rob Feeney", "Joinery workshop"),
      ],
      faq: [
        faq("Do you charge a fee?", "No — we are paid a commission by the insurer, and we will tell you what it is."),
        faq("Can you review my current policy?", "Yes, at no cost. Most reviews find at least one gap."),
      ],
      contact: { email: "quotes@example.com", phone: "+44 161 555 0180", address: "5 Exchange Street", hours: "Mon — Fri, 8:30am to 6pm" },
      footerNote: "Authorised and regulated. Independent of any single insurer.",
    },
  },
  {
    slug: "meridian-wealth",
    name: "Meridian — Wealth Advisory",
    category: "finance",
    theme: "noir",
    description: "Discreet advisory page for a private client practice.",
    tags: ["wealth", "advisory", "dark", "luxury"],
    layout: ["nav:centered", "hero:cover", "block:featureGrid", "block:stats", "block:team", "block:contact", "block:footer"],
    data: {
      brand: "MERIDIAN",
      nav: [{ label: "Services", href: "#features" }, { label: "Team", href: "#team" }, { label: "Approach", href: "#features" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Private clients since 1997",
      headline: "Patient capital, plainly explained",
      subhead: "Independent advice on investments, retirement and succession for families who prefer fewer, better decisions.",
      ctaPrimary: { label: "Arrange a meeting", href: "#contact" },
      ctaSecondary: { label: "Our approach", href: "#features" },
      heroImage: img("wealth-hero", 1800, 1100),
      features: [
        f("Investment", "Low-cost portfolios rebalanced on a schedule, not on a hunch.", "chart"),
        f("Retirement", "Cash-flow modelling you can actually read.", "clock"),
        f("Succession", "Trusts, gifting and the conversations families postpone.", "users"),
      ],
      stats: [
        { value: "$1.4B", label: "Assets advised" },
        { value: "27 yrs", label: "Average client tenure" },
        { value: "0", label: "Product commissions taken" },
        { value: "1:40", label: "Adviser to client ratio" },
      ],
      team: [
        { name: "Claire Devlin", role: "Managing Partner", initials: "CD" },
        { name: "Hugo Marchetti", role: "Investment Director", initials: "HM" },
        { name: "Priya Shah", role: "Financial Planner", initials: "PS" },
        { name: "Tom Reilly", role: "Client Director", initials: "TR" },
      ],
      contact: { email: "enquiries@example.com", phone: "+44 20 7946 0155", address: "14 Bury Street, London", hours: "By appointment" },
      footerNote: "Capital at risk. Past performance is not a guide to future returns.",
    },
  },
  {
    slug: "ledgerline-crypto",
    name: "Ledgerline — Exchange",
    category: "finance",
    theme: "glacier",
    description: "Trading platform page with fees, security posture and asset coverage.",
    tags: ["crypto", "trading", "dark", "fintech"],
    layout: ["nav:simple", "hero:centered", "block:stats", "block:featureBento", "block:pricing", "block:faq", "block:footer"],
    data: {
      brand: "Ledgerline",
      nav: [{ label: "Markets", href: "#features" }, { label: "Fees", href: "#pricing" }, { label: "Security", href: "#faq" }, { label: "Sign up", href: "#contact" }],
      eyebrow: "Regulated exchange",
      headline: "Trade with the fee schedule on the front page",
      subhead: "No hidden spread, no surprise withdrawal charge. What you see here is what you are charged.",
      ctaPrimary: { label: "Open an account", href: "#contact" },
      ctaSecondary: { label: "See the fees", href: "#pricing" },
      heroImage: img("exchange-hero", 1600, 1000),
      stats: [
        { value: "0.10%", label: "Taker fee" },
        { value: "98%", label: "Assets in cold storage" },
        { value: "180+", label: "Trading pairs" },
        { value: "24/7", label: "Support" },
      ],
      features: [
        f("Cold storage", "Nearly everything held offline, with published proof of reserves.", "lock"),
        f("Fast settlement", "Withdrawals processed in minutes, not business days.", "bolt"),
        f("Real order book", "Full depth, no internalised matching.", "chart"),
        f("API access", "REST and WebSocket, documented and rate-limited fairly.", "code"),
        f("Insurance fund", "Independently audited and reported quarterly.", "shield"),
      ],
      plans: [
        { name: "Standard", price: "0.10%", cadence: "per trade", cta: "Open account", features: ["Spot trading", "Free deposits", "Email support"] },
        { name: "Active", price: "0.06%", cadence: "per trade", cta: "Open account", featured: true, features: ["Reduced fees over $100k volume", "API access", "Priority support"] },
      ],
      faq: [
        faq("Where are assets held?", "The large majority in cold storage with a qualified custodian. Reserves are published monthly."),
        faq("Are you regulated?", "Yes, and our registration number is in the footer of every page."),
      ],
      footerNote: "Trading involves risk. Only trade what you can afford to lose.",
    },
  },

  /* ───────────────────────────────────────────────────────── real estate */
  {
    slug: "quarry-property-developer",
    name: "Quarry — Property Developer",
    category: "real-estate",
    theme: "sandstone",
    description: "Development launch page with plot availability and a reservation path.",
    tags: ["property", "development", "warm", "listings"],
    layout: ["nav:simple", "hero:cover", "block:stats", "block:gallery", "block:pricing", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Quarry",
      nav: [{ label: "The development", href: "#work" }, { label: "Homes", href: "#pricing" }, { label: "FAQ", href: "#faq" }, { label: "Register", href: "#contact" }],
      eyebrow: "Phase two now released",
      headline: "Twenty-eight homes on the old quarry road",
      subhead: "Two to five bedrooms, air source heating throughout, and a green corridor running through the middle of the site.",
      ctaPrimary: { label: "Register interest", href: "#contact" },
      ctaSecondary: { label: "View the homes", href: "#pricing" },
      heroImage: img("development-hero", 1800, 1100),
      stats: [
        { value: "28", label: "Homes" },
        { value: "A", label: "Energy rating" },
        { value: "11", label: "Reserved so far" },
        { value: "2026", label: "First completions" },
      ],
      gallery: [
        { src: img("dev-1", 800, 600), caption: "The Ash — 3 bed semi" },
        { src: img("dev-2", 800, 600), caption: "The Rowan — 4 bed detached" },
        { src: img("dev-3", 800, 600), caption: "Green corridor and play area" },
      ],
      plans: [
        { name: "The Ash", price: "$385,000", cadence: "3 bed", cta: "Reserve", features: ["1,050 sq ft", "Parking for two", "South-facing garden"] },
        { name: "The Rowan", price: "$489,000", cadence: "4 bed", cta: "Reserve", featured: true, features: ["1,420 sq ft", "Garage", "En-suite", "Home office"] },
        { name: "The Willow", price: "$625,000", cadence: "5 bed", cta: "Enquire", features: ["1,890 sq ft", "Double garage", "Corner plot"] },
      ],
      faq: [
        faq("What is included?", "Flooring throughout, integrated appliances, turf to the rear and a ten-year structural warranty."),
        faq("Can I reserve off plan?", "Yes, with a refundable deposit and a fixed price for six months."),
      ],
      contact: { email: "sales@example.com", phone: "+44 1900 555 220", address: "Marketing suite, Quarry Road", hours: "Thu — Mon, 10am to 5pm" },
      footerNote: "Computer generated images are indicative. Specification may vary by plot.",
    },
  },
  {
    slug: "haven-rentals",
    name: "Haven — Rental Listings",
    category: "real-estate",
    theme: "porcelain",
    description: "Letting agency page with available properties and tenant information.",
    tags: ["rental", "letting", "light", "listings"],
    layout: ["nav:simple", "hero:split", "block:gallery", "block:steps", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Haven",
      nav: [{ label: "Available", href: "#work" }, { label: "Renting", href: "#how" }, { label: "Landlords", href: "#faq" }, { label: "Contact", href: "#contact" }],
      eyebrow: "No tenant fees, ever",
      headline: "Homes to rent, listed honestly",
      subhead: "Every listing shows the real monthly cost, the deposit, the bills included and how long the landlord wants you to stay.",
      ctaPrimary: { label: "Browse available homes", href: "#work" },
      ctaSecondary: { label: "How renting works", href: "#how" },
      heroImage: img("rental-hero", 1000, 1100),
      gallery: [
        { src: img("rent-1", 800, 600), caption: "2 bed flat — Mill Street · $1,450/mo" },
        { src: img("rent-2", 800, 600), caption: "Studio — Old Town · $950/mo" },
        { src: img("rent-3", 800, 600), caption: "3 bed house — Ash Grove · $1,900/mo" },
        { src: img("rent-4", 800, 600), caption: "1 bed conversion — Park Road · $1,150/mo" },
        { src: img("rent-5", 800, 600), caption: "4 bed share — University Hill · $2,400/mo" },
        { src: img("rent-6", 800, 600), caption: "2 bed cottage — Bell Lane · $1,600/mo" },
      ],
      steps: [
        f("Book a viewing", "Evenings and weekends included. No block viewings."),
        f("Apply", "One form, one referencing fee paid by the landlord."),
        f("Move in", "Inventory, keys and a named contact for the whole tenancy."),
      ],
      faq: [
        faq("Do you charge tenants?", "No. Referencing, contracts and renewals are paid by the landlord."),
        faq("How fast are repairs?", "Emergencies same day, everything else within five working days."),
      ],
      contact: { email: "lettings@example.com", phone: "+44 117 555 0122", address: "44 Mill Street", hours: "Mon — Sat, 9am to 6pm" },
      footerNote: "Client money protected. Deposits held in a government scheme.",
    },
  },

  /* ───────────────────────────────────────────────────────── healthcare */
  {
    slug: "quiet-room-therapy",
    name: "Quiet Room — Therapy Practice",
    category: "healthcare",
    theme: "linen",
    description: "Gentle, low-pressure therapy practice page with approach and fees.",
    tags: ["therapy", "counselling", "light", "calm"],
    layout: ["nav:minimal", "hero:editorial", "block:featureGrid", "block:pricing", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Quiet Room",
      nav: [{ label: "How I work", href: "#features" }, { label: "Fees", href: "#pricing" }, { label: "FAQ", href: "#faq" }],
      eyebrow: "Accepting new clients",
      headline: "A place to think out loud",
      subhead: "Individual therapy for anxiety, burnout and the things that are hard to say to people who know you.",
      ctaPrimary: { label: "Book a first session", href: "#contact" },
      heroImage: img("therapy-hero", 900, 1200),
      features: [
        f("Talking therapy", "Open-ended sessions led by what you bring, not a worksheet.", "heart"),
        f("Short-term work", "Six to twelve sessions with a clear focus, if that suits you better.", "clock"),
        f("Online or in person", "Same rate either way. Many clients mix the two.", "globe"),
      ],
      plans: [
        { name: "First session", price: "$40", cadence: "50 min", cta: "Book", features: ["Reduced rate", "No commitment", "Online or in person"] },
        { name: "Ongoing", price: "$85", cadence: "per session", cta: "Book", featured: true, features: ["Weekly or fortnightly", "Same time each week", "Sliding scale available"] },
      ],
      faq: [
        faq("Is it confidential?", "Yes, with the standard legal exceptions, which I will explain in the first session."),
        faq("What if I cannot afford it?", "A number of reduced-rate places are kept open. Just ask — it is not awkward."),
      ],
      contact: { email: "hello@example.com", phone: "+44 7700 900112", address: "Room 3, The Old Dispensary", hours: "Tue — Fri, 9am to 7pm" },
      footerNote: "Registered member of a professional counselling body.",
    },
  },
  {
    slug: "paws-veterinary",
    name: "Paws — Veterinary Clinic",
    category: "healthcare",
    theme: "forest",
    description: "Friendly vet practice page with services, plans and emergency details.",
    tags: ["veterinary", "pets", "dark", "clinic"],
    layout: ["nav:simple", "hero:split", "block:featureGrid", "block:pricing", "block:team", "block:contact", "block:footer"],
    data: {
      brand: "Paws Veterinary",
      nav: [{ label: "Services", href: "#features" }, { label: "Health plans", href: "#pricing" }, { label: "Our vets", href: "#team" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Emergency cover, 24 hours",
      headline: "Care for the ones who cannot tell you where it hurts",
      subhead: "A small animal practice with in-house diagnostics, honest pricing and appointments long enough to ask questions.",
      ctaPrimary: { label: "Book an appointment", href: "#contact" },
      ctaSecondary: { label: "See health plans", href: "#pricing" },
      heroImage: img("vet-hero", 1000, 1100),
      features: [
        f("Routine care", "Vaccinations, dentals and check-ups with prices published.", "heart"),
        f("Diagnostics", "X-ray, ultrasound and lab work on site, results the same day.", "chart"),
        f("Surgery", "Day procedures with a nurse assigned to your pet throughout.", "shield"),
      ],
      plans: [
        { name: "Kitten & puppy", price: "$18", cadence: "/mo", cta: "Join", features: ["Full vaccination course", "Two health checks", "Microchipping"] },
        { name: "Adult", price: "$26", cadence: "/mo", cta: "Join", featured: true, features: ["Annual boosters", "Flea and worm treatment", "Two check-ups", "10% off treatment"] },
        { name: "Senior", price: "$34", cadence: "/mo", cta: "Join", features: ["Everything in Adult", "Twice-yearly blood screening", "Arthritis checks"] },
      ],
      team: [
        { name: "Dr. Nia Roberts", role: "Lead veterinarian", initials: "NR" },
        { name: "Dr. Samir Khan", role: "Surgery", initials: "SK" },
        { name: "Bea Lindqvist", role: "Head nurse", initials: "BL" },
        { name: "Dr. Tom Egan", role: "Exotics", initials: "TE" },
      ],
      contact: { email: "reception@example.com", phone: "+1 (555) 771-0900", address: "9 Meadow Lane", hours: "Mon — Fri 8am to 7pm · Sat 9am to 1pm · Emergencies 24/7" },
      footerNote: "If your pet is in distress, phone before travelling.",
    },
  },

  /* ────────────────────────────────────────────────────────────── travel */
  {
    slug: "compass-tour-guide",
    name: "Compass — Local Tours",
    category: "travel",
    theme: "ember",
    description: "Independent guide page with tour list, booking and reviews.",
    tags: ["tours", "travel", "dark", "local"],
    layout: ["nav:simple", "hero:cover", "block:gallery", "block:pricing", "block:testimonials", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Compass",
      nav: [{ label: "Tours", href: "#work" }, { label: "Prices", href: "#pricing" }, { label: "Reviews", href: "#testimonials" }, { label: "Book", href: "#contact" }],
      eyebrow: "Small groups, licensed guide",
      headline: "The city, by someone who lives in it",
      subhead: "Walking tours built around food, architecture and the stories that do not make the guidebooks.",
      ctaPrimary: { label: "Book a tour", href: "#contact" },
      ctaSecondary: { label: "See the tours", href: "#work" },
      heroImage: img("tours-hero", 1800, 1100),
      gallery: [
        { src: img("tour-a", 800, 600), caption: "Old town, morning — 3 hours" },
        { src: img("tour-b", 800, 600), caption: "Market and food crawl — 4 hours" },
        { src: img("tour-c", 800, 600), caption: "Architecture walk — 2.5 hours" },
      ],
      plans: [
        { name: "Group tour", price: "$45", cadence: "per person", cta: "Book", features: ["Max eight people", "Three hours", "Tastings included"] },
        { name: "Private tour", price: "$260", cadence: "per group", cta: "Book", featured: true, features: ["Your pace, your interests", "Up to six people", "Flexible start time"] },
      ],
      quotes: [
        q("The best three hours of our trip, and we nearly skipped it.", "Hannah Brück", "Berlin"),
        q("He got us into a bakery that does not have a sign.", "Diego Ferrer", "Buenos Aires"),
      ],
      faq: [
        faq("What if it rains?", "We go anyway, with a rerouted indoor version. Full refund if you would rather not."),
        faq("Is it suitable for kids?", "Yes for the food tour. The architecture walk suits ages ten and up."),
      ],
      contact: { email: "book@example.com", phone: "+351 91 555 0140", address: "Meeting point: the old fountain", hours: "Daily, 9am and 2pm" },
      footerNote: "Licensed guide. Cancel free up to 24 hours before.",
    },
  },
  {
    slug: "driftwood-hostel",
    name: "Driftwood — Hostel",
    category: "travel",
    theme: "aurora",
    description: "Sociable hostel page with rooms, facilities and instant booking.",
    tags: ["hostel", "budget", "dark", "hospitality"],
    layout: ["nav:simple", "hero:stacked", "block:featureGrid", "block:pricing", "block:gallery", "block:contact", "block:footer"],
    data: {
      brand: "Driftwood",
      nav: [{ label: "Rooms", href: "#pricing" }, { label: "The place", href: "#features" }, { label: "Gallery", href: "#work" }, { label: "Book", href: "#contact" }],
      headline: "Cheap bed, good coffee, better people",
      subhead: "Forty beds two streets from the water. Free breakfast, no curfew, and a bar that closes when the last person leaves.",
      ctaPrimary: { label: "Check availability", href: "#contact" },
      ctaSecondary: { label: "See the rooms", href: "#pricing" },
      heroImage: img("hostel-hero", 1600, 900),
      features: [
        f("Actually clean", "Professionally cleaned twice daily. We are slightly obsessive about it.", "spark"),
        f("Free breakfast", "Bread, eggs, fruit and proper coffee, 7 to 10.", "heart"),
        f("Things to do", "Free walking tour Mondays, dinner Wednesdays, quiz Fridays.", "users"),
      ],
      plans: [
        { name: "Dorm bed", price: "$24", cadence: "/night", cta: "Book", features: ["6 or 8 bed rooms", "Locker and reading light", "Breakfast included"] },
        { name: "Private twin", price: "$68", cadence: "/night", cta: "Book", featured: true, features: ["Ensuite", "Towels included", "Breakfast included"] },
        { name: "Weekly", price: "$140", cadence: "/week", cta: "Enquire", features: ["Dorm bed", "Laundry included", "Kitchen shelf"] },
      ],
      gallery: [
        { src: img("hostel-1", 800, 600), caption: "The courtyard" },
        { src: img("hostel-2", 800, 600), caption: "Private twin" },
        { src: img("hostel-3", 800, 600), caption: "Kitchen" },
      ],
      contact: { email: "stay@example.com", phone: "+34 93 555 0166", address: "Carrer del Mar 22", hours: "Reception 24 hours" },
      footerNote: "Book direct — it is always cheaper than the aggregators.",
    },
  },

  /* ───────────────────────────────────────────────────────────── fitness */
  {
    slug: "pace-running-club",
    name: "Pace — Running Club",
    category: "fitness",
    theme: "cobalt",
    description: "Community running club page with sessions, routes and membership.",
    tags: ["running", "community", "dark", "club"],
    layout: ["nav:simple", "hero:cover", "block:stats", "block:steps", "block:featureGrid", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Pace",
      nav: [{ label: "Sessions", href: "#how" }, { label: "Join", href: "#features" }, { label: "Members", href: "#testimonials" }, { label: "Find us", href: "#contact" }],
      eyebrow: "First three runs are free",
      headline: "Everyone runs at the back sometimes",
      subhead: "A club for people who want to run regularly and not be the slowest person left behind at a junction.",
      ctaPrimary: { label: "Come to a session", href: "#contact" },
      ctaSecondary: { label: "See the sessions", href: "#how" },
      heroImage: img("running-hero", 1800, 1100),
      stats: [
        { value: "3", label: "Sessions a week" },
        { value: "240", label: "Members" },
        { value: "5k — 42k", label: "Distances covered" },
        { value: "$0", label: "For your first month" },
      ],
      steps: [
        f("Tuesday intervals", "Track session, four pace groups, coached."),
        f("Thursday social", "Five miles, conversational, nobody dropped."),
        f("Sunday long run", "Eight to twenty miles with route options."),
      ],
      features: [
        f("Coached sessions", "Qualified coaches at every track night, included in membership.", "users"),
        f("Every pace welcome", "Groups from 12 min/mile to 6 min/mile, with a back marker on every run.", "heart"),
        f("Races together", "Club entries, shared transport and someone holding your bag.", "star"),
      ],
      quotes: [
        q("I joined unable to run a mile. Marathon in April.", "Simone Rossi", "Member since 2023"),
        q("It is the only reason I leave the house in January.", "Dan Whitaker", "Member since 2019"),
      ],
      contact: { email: "hello@example.com", phone: "—", address: "Meet at the park gates", hours: "Tue 7pm · Thu 6:30pm · Sun 8am" },
      footerNote: "Affiliated club. Membership $40 a year.",
    },
  },
  {
    slug: "fuel-nutrition-coach",
    name: "Fuel — Nutrition Coaching",
    category: "fitness",
    theme: "forest",
    description: "One-to-one nutrition coaching page with programmes and results.",
    tags: ["nutrition", "coaching", "dark", "health"],
    layout: ["nav:simple", "hero:split", "block:steps", "block:pricing", "block:testimonials", "block:faq", "block:cta", "block:footer"],
    data: {
      brand: "Fuel",
      nav: [{ label: "How it works", href: "#how" }, { label: "Programmes", href: "#pricing" }, { label: "Results", href: "#testimonials" }, { label: "FAQ", href: "#faq" }],
      eyebrow: "Registered nutritionist",
      headline: "No meal plans you will abandon in a fortnight",
      subhead: "Coaching that starts from what you already eat and changes three things at a time.",
      ctaPrimary: { label: "Book a free call", href: "#contact" },
      ctaSecondary: { label: "See programmes", href: "#pricing" },
      heroImage: img("nutrition-hero", 1000, 1100),
      steps: [
        f("Assessment", "A week of normal eating logged, then a proper conversation about it."),
        f("Three changes", "We change three habits, not thirty. Then we check in."),
        f("Adjust", "Fortnightly calls, adjusted around real life — holidays included."),
      ],
      plans: [
        { name: "Kickstart", price: "$180", cadence: "one-off", cta: "Book", features: ["Full assessment", "90-minute session", "Written plan"] },
        { name: "Coaching", price: "$140", cadence: "/mo", cta: "Start", featured: true, features: ["Fortnightly calls", "Message support", "Ongoing adjustments"] },
        { name: "Athlete", price: "$260", cadence: "/mo", cta: "Enquire", features: ["Weekly calls", "Race and training fuelling", "Body composition tracking"] },
      ],
      quotes: [
        q("First approach that survived a family holiday.", "Ana Beltran", "Client, 14 months"),
        q("Down 11 kg and I still eat bread.", "Marcus Adeyemi", "Client, 9 months"),
      ],
      faq: [
        faq("Do I have to count calories?", "Only if it helps you. Plenty of clients never weigh anything."),
        faq("Do you sell supplements?", "No. I have no products to sell you, which is rather the point."),
      ],
      ctaTitle: "Start with a free twenty-minute call",
      footerNote: "Registered nutritionist. Not a substitute for medical advice.",
    },
  },

  /* ────────────────────────────────────────────────────────────── gaming */
  {
    slug: "static-streamer",
    name: "Static — Streamer",
    category: "gaming",
    theme: "neon",
    description: "Streamer page with schedule, sponsors and community links.",
    tags: ["streaming", "creator", "dark", "colorful"],
    layout: ["nav:minimal", "hero:split", "block:stats", "block:steps", "block:logos", "block:footer"],
    data: {
      brand: "STATIC",
      nav: [{ label: "Schedule", href: "#how" }, { label: "Sponsors", href: "#logos" }, { label: "Discord", href: "#" }],
      eyebrow: "Live five nights a week",
      headline: "Bad decisions, played well",
      subhead: "Roguelikes, horror on Fridays, and a community that is genuinely nice to newcomers.",
      ctaPrimary: { label: "Watch live", href: "#" },
      ctaSecondary: { label: "Join the Discord", href: "#" },
      heroImage: img("stream-hero", 1000, 1100),
      stats: [
        { value: "94k", label: "Followers" },
        { value: "1.8k", label: "Average viewers" },
        { value: "5", label: "Streams a week" },
        { value: "6 yrs", label: "Streaming" },
      ],
      steps: [
        f("Mon — Wed", "Roguelikes and runs. 8pm to midnight."),
        f("Friday", "Horror night, with the lights off and the chat unhelpful."),
        f("Sunday", "Community games. Anyone can join the lobby."),
      ],
      logos: ["Voltcore", "Hexbyte", "Nightfall", "Rapid"],
      footerNote: "Sponsorship enquiries by email only.",
    },
  },
  {
    slug: "clan-server",
    name: "Clan — Game Server",
    category: "gaming",
    theme: "terminal",
    description: "Community game server page with rules, ranks and how to join.",
    tags: ["gaming", "community", "dark", "terminal"],
    layout: ["nav:minimal", "hero:terminal", "block:featureGrid", "block:steps", "block:faq", "block:footer"],
    data: {
      brand: "clan.gg",
      nav: [{ label: "rules", href: "#features" }, { label: "join", href: "#how" }, { label: "faq", href: "#faq" }],
      eyebrow: "1,400 regulars",
      headline: "A server that is actually moderated",
      subhead: "Vanilla-plus survival, whitelisted, backed up hourly, with admins who log off at a reasonable hour.",
      ctaPrimary: { label: "Apply to join", href: "#how" },
      ctaSecondary: { label: "Read the rules", href: "#features" },
      features: [
        f("Whitelisted", "Short application. Griefers do not get through it.", "lock"),
        f("Hourly backups", "Thirty days of rollback, and we have used it exactly twice.", "shield"),
        f("No pay to win", "Donations cover the server bill. That is the whole benefit.", "heart"),
        f("Stable", "99.9% uptime over two years on dedicated hardware.", "bolt"),
      ],
      steps: [
        f("Apply", "Two questions and your username. Usually approved same day."),
        f("Read the rules", "There are six. They fit on one screen."),
        f("Play", "Claim a plot, join a town, or go live in a cave. Genuinely up to you."),
      ],
      faq: [
        faq("Is there a map reset?", "Once a year, announced two months ahead. Builds are archived and downloadable."),
        faq("Can I bring friends?", "Yes — put them on your application and we will process together."),
      ],
      footerNote: "Community run since 2019. Donations optional, never rewarded.",
    },
  },

  /* ─────────────────────────────────────────────────────────── education */
  {
    slug: "lingua-language-school",
    name: "Lingua — Language School",
    category: "education",
    theme: "blush",
    description: "Language school page with course levels, timetable and enrolment.",
    tags: ["language", "school", "light", "courses"],
    layout: ["nav:simple", "hero:split", "block:steps", "block:featureGrid", "block:pricing", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Lingua",
      nav: [{ label: "Courses", href: "#how" }, { label: "Method", href: "#features" }, { label: "Prices", href: "#pricing" }, { label: "Enrol", href: "#contact" }],
      eyebrow: "New terms start monthly",
      headline: "Speaking from the first lesson",
      subhead: "Small-group language classes where you talk more than the teacher does. Six levels, six students maximum.",
      ctaPrimary: { label: "Book a free trial class", href: "#contact" },
      ctaSecondary: { label: "See the levels", href: "#how" },
      heroImage: img("language-hero", 1000, 1100),
      steps: [
        f("Beginner", "A1 — A2. Everyday situations, present and past."),
        f("Intermediate", "B1 — B2. Opinions, work, and arguing about films."),
        f("Advanced", "C1 — C2. Nuance, register and reading the news comfortably."),
      ],
      features: [
        f("Six per class", "Everyone speaks in every lesson. No hiding at the back.", "users"),
        f("Native teachers", "All qualified, all trained in-house before they teach a class.", "star"),
        f("Free level test", "Twenty minutes, in person or online, before you pay anything.", "spark"),
      ],
      plans: [
        { name: "Evening course", price: "$220", cadence: "8 weeks", cta: "Enrol", features: ["Two evenings a week", "Materials included", "Six per class"] },
        { name: "Intensive", price: "$480", cadence: "4 weeks", cta: "Enrol", featured: true, features: ["Daily mornings", "Conversation club", "Progress report"] },
        { name: "Private", price: "$55", cadence: "per hour", cta: "Enquire", features: ["Fully flexible", "Exam preparation", "Online or in person"] },
      ],
      quotes: [
        q("Six weeks in and I ordered dinner without switching to English.", "Fiona Doyle", "B1 evening course"),
        q("The trial class sold it. Nobody let me stay quiet.", "Kenji Watanabe", "A2 intensive"),
      ],
      contact: { email: "enrol@example.com", phone: "+34 91 555 0199", address: "Calle Mayor 40, 2nd floor", hours: "Mon — Fri, 9am to 9pm" },
      footerNote: "Accredited school. Free level test, no obligation.",
    },
  },
  {
    slug: "vault-museum",
    name: "Vault — Museum",
    category: "education",
    theme: "noir",
    description: "Museum page with exhibitions, opening times and visitor information.",
    tags: ["museum", "culture", "dark", "institution"],
    layout: ["nav:centered", "hero:cover", "block:gallery", "block:steps", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "THE VAULT",
      nav: [{ label: "Exhibitions", href: "#work" }, { label: "Visit", href: "#how" }, { label: "FAQ", href: "#faq" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Free entry, always",
      headline: "Nine hundred years, four floors",
      subhead: "A civic museum of the city's making — trade, industry, migration and the arguments in between.",
      ctaPrimary: { label: "Plan your visit", href: "#how" },
      ctaSecondary: { label: "What's on", href: "#work" },
      heroImage: img("museum-hero", 1800, 1100),
      gallery: [
        { src: img("museum-1", 800, 600), caption: "Salt and Sail — until 14 June" },
        { src: img("museum-2", 800, 600), caption: "The Making Floor — permanent" },
        { src: img("museum-3", 800, 600), caption: "Arrivals — until 2 September" },
      ],
      steps: [
        f("Getting here", "Ten minutes from the central station, buses 4 and 17 stop outside."),
        f("With children", "Free trails at the desk, buggy parking and a room for feeding."),
        f("Access", "Step-free throughout, three wheelchairs available, quiet hour Tuesdays."),
      ],
      faq: [
        faq("Do I need a ticket?", "Not for the permanent collection. Special exhibitions are ticketed and often sell out."),
        faq("Can I take photographs?", "Yes, without flash, except where a sign says otherwise."),
      ],
      contact: { email: "visit@example.com", phone: "+44 151 555 0140", address: "Dock Road", hours: "Tue — Sun, 10am to 5pm · Late Thursdays until 9pm" },
      footerNote: "Free entry supported by donations and members.",
    },
  },

  /* ────────────────────────────────────────────────────────────── events */
  {
    slug: "lumen-festival",
    name: "Lumen — Music Festival",
    category: "events",
    theme: "neon",
    description: "Festival page with line-up, tickets and practical information.",
    tags: ["festival", "music", "dark", "colorful"],
    layout: ["nav:minimal", "hero:cover", "block:stats", "block:team", "block:pricing", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "LUMEN",
      nav: [{ label: "Line-up", href: "#team" }, { label: "Tickets", href: "#pricing" }, { label: "Info", href: "#faq" }],
      eyebrow: "22 — 24 August · Riverside Park",
      headline: "Three days, four stages, one very long weekend",
      subhead: "Forty artists across electronic, jazz and whatever the third stage is doing this year.",
      ctaPrimary: { label: "Get tickets", href: "#pricing" },
      ctaSecondary: { label: "See the line-up", href: "#team" },
      heroImage: img("festival-hero", 1800, 1100),
      stats: [
        { value: "40", label: "Artists" },
        { value: "4", label: "Stages" },
        { value: "3", label: "Days" },
        { value: "12k", label: "Capacity" },
      ],
      team: [
        { name: "NOVA SYSTEM", role: "Saturday headline", initials: "NS" },
        { name: "Marisol Vega", role: "Friday headline", initials: "MV" },
        { name: "Deep Field", role: "Sunday headline", initials: "DF" },
        { name: "+ 37 more", role: "Full line-up in June", initials: "37" },
      ],
      plans: [
        { name: "Day ticket", price: "$65", cadence: "one day", cta: "Buy", features: ["Any single day", "All stages", "Re-entry"] },
        { name: "Weekend", price: "$145", cadence: "3 days", cta: "Buy", featured: true, features: ["All three days", "All stages", "Re-entry", "Early entry Friday"] },
        { name: "Weekend + camping", price: "$195", cadence: "3 days", cta: "Buy", features: ["Everything in Weekend", "Camping pitch", "Showers and lockers"] },
      ],
      faq: [
        faq("Is it accessible?", "Yes — viewing platforms at every stage, accessible camping and a free carer ticket."),
        faq("Can I bring food?", "Sealed food and empty bottles, yes. Glass and alcohol, no."),
      ],
      contact: { email: "info@example.com", phone: "—", address: "Riverside Park, north entrance", hours: "Gates 12pm daily" },
      footerNote: "Under 12s free with a ticketed adult.",
    },
  },
  {
    slug: "gallery-opening",
    name: "Aperture — Art Exhibition",
    category: "events",
    theme: "porcelain",
    description: "Exhibition page with dates, artist statement and RSVP.",
    tags: ["exhibition", "art", "light", "editorial"],
    layout: ["nav:centered", "hero:editorial", "block:gallery", "block:steps", "block:contact", "block:footer"],
    data: {
      brand: "Aperture Gallery",
      nav: [{ label: "Exhibition", href: "#work" }, { label: "Visit", href: "#how" }, { label: "RSVP", href: "#contact" }, { label: "Artist", href: "#work" }],
      eyebrow: "Private view 6 March, 6 — 9pm",
      headline: "Interior Weather",
      subhead: "New paintings by Ines Cardoso. Twenty-two works made over three winters in the same north-facing room.",
      ctaPrimary: { label: "RSVP to the private view", href: "#contact" },
      heroImage: img("exhibition-hero", 900, 1200),
      gallery: [
        { src: img("art-a", 800, 600), caption: "Interior with Rain, 2024" },
        { src: img("art-b", 800, 600), caption: "Morning, Unfinished, 2023" },
        { src: img("art-c", 800, 600), caption: "Blue Room, 2024" },
        { src: img("art-d", 800, 600), caption: "Study for Weather, 2022" },
        { src: img("art-e", 800, 600), caption: "Late Light, 2024" },
        { src: img("art-f", 800, 600), caption: "The Same Window, 2023" },
      ],
      steps: [
        f("Private view", "6 March, 6 to 9pm. RSVP required, guests welcome."),
        f("Open to all", "7 March to 19 April, Wednesday to Sunday, free entry."),
        f("Artist talk", "22 March, 3pm. Booking recommended, forty seats."),
      ],
      contact: { email: "gallery@example.com", phone: "+351 21 555 0177", address: "Rua das Flores 12", hours: "Wed — Sun, 11am to 6pm" },
      footerNote: "Works available for purchase. Price list at the desk.",
    },
  },

  /* ─────────────────────────────────────────────────────────── developer */
  {
    slug: "shipyard-changelog",
    name: "Shipyard — Changelog",
    category: "developer",
    theme: "midnight",
    description: "Product changelog and status page for a developer product.",
    tags: ["changelog", "developer", "dark", "product"],
    layout: ["nav:minimal", "hero:stacked", "block:steps", "block:featureGrid", "block:faq", "block:footer"],
    data: {
      brand: "Shipyard",
      nav: [{ label: "Changelog", href: "#how" }, { label: "Status", href: "#features" }, { label: "Docs", href: "#" }],
      headline: "Everything we shipped, in order",
      subhead: "Weekly releases, written by the people who built them. No marketing passes over these notes.",
      ctaPrimary: { label: "Subscribe to updates", href: "#contact" },
      ctaSecondary: { label: "Read the docs", href: "#" },
      heroImage: img("changelog-hero", 1600, 900),
      steps: [
        f("v4.2 — Scheduled exports", "Cron-style schedules for any saved export, with delivery to S3 or a webhook."),
        f("v4.1 — Faster cold starts", "Median cold start down from 340 ms to 61 ms after moving the runtime bootstrap."),
        f("v4.0 — New permissions model", "Per-resource roles replacing workspace-wide access. Migration guide in the docs."),
      ],
      features: [
        f("API", "Operational · 99.99% over 90 days", "globe"),
        f("Dashboard", "Operational · 99.98% over 90 days", "layers"),
        f("Webhooks", "Operational · 99.95% over 90 days", "bolt"),
      ],
      faq: [
        faq("How do I get notified?", "RSS, email, or a webhook into your own Slack. All three are free."),
        faq("Do you post incidents here?", "Yes, including the postmortem, usually within five working days."),
      ],
      footerNote: "Written by engineers. Occasionally too honest.",
    },
  },
  {
    slug: "pipeline-devops-portfolio",
    name: "Pipeline — DevOps Portfolio",
    category: "developer",
    theme: "terminal",
    description: "Infrastructure engineer portfolio with projects, stack and contact.",
    tags: ["devops", "portfolio", "dark", "terminal"],
    layout: ["nav:minimal", "hero:terminal", "block:featureGrid", "block:gallery", "block:stats", "block:contact", "block:footer"],
    data: {
      brand: "~/kmartin",
      nav: [{ label: "work", href: "#work" }, { label: "stack", href: "#features" }, { label: "contact", href: "#contact" }],
      eyebrow: "Platform / SRE",
      headline: "I make deploys boring",
      subhead: "Infrastructure engineer working on Kubernetes, Terraform and the unglamorous work that stops pagers going off at 3am.",
      ctaPrimary: { label: "See recent work", href: "#work" },
      ctaSecondary: { label: "Get in touch", href: "#contact" },
      features: [
        f("Kubernetes", "Cluster design, autoscaling and cost work across three clouds.", "layers"),
        f("Terraform", "Modules that other teams actually reuse, with tests.", "code"),
        f("Observability", "Traces, SLOs and alerts people trust enough not to mute.", "chart"),
        f("On-call", "Rotations, runbooks and blameless postmortems.", "clock"),
      ],
      gallery: [
        { src: img("devops-1", 800, 600), caption: "Multi-region failover — 6s RTO" },
        { src: img("devops-2", 800, 600), caption: "Cost programme — 41% reduction" },
        { src: img("devops-3", 800, 600), caption: "CI rebuild — 34 min to 6 min" },
      ],
      stats: [
        { value: "99.99%", label: "Availability delivered" },
        { value: "-41%", label: "Cloud spend" },
        { value: "6 min", label: "CI pipeline" },
        { value: "0", label: "Sev-1s last year" },
      ],
      contact: { email: "hello@example.com", phone: "—", address: "Remote · UTC+1" },
      footerNote: "Open to contract work from Q3.",
    },
  },

  /* ─────────────────────────────────────────────────────── landing pages */
  {
    slug: "webinar-signup",
    name: "Broadcast — Webinar",
    category: "landing-page",
    theme: "cobalt",
    description: "Single-goal webinar registration page with agenda and speakers.",
    tags: ["webinar", "event", "dark", "conversion"],
    layout: ["nav:minimal", "hero:centered", "block:steps", "block:team", "block:faq", "block:cta", "block:footer"],
    data: {
      brand: "Broadcast",
      nav: [{ label: "Agenda", href: "#how" }, { label: "Speakers", href: "#team" }],
      eyebrow: "Free · 14 May · 60 minutes",
      headline: "How three teams cut their cloud bill without slowing down",
      subhead: "A live session with the engineers who did it, including the parts that did not work.",
      ctaPrimary: { label: "Save my seat", href: "#contact" },
      ctaSecondary: { label: "See the agenda", href: "#how" },
      heroImage: img("webinar-hero", 1600, 1000),
      steps: [
        f("Minutes 0 — 15", "What each team measured first, and what they got wrong."),
        f("Minutes 15 — 45", "Three case studies with real numbers on screen."),
        f("Minutes 45 — 60", "Live questions. No slides, no sales pitch."),
      ],
      team: [
        { name: "Amara Osei", role: "Principal Engineer, Fieldwork", initials: "AO" },
        { name: "Jonas Vik", role: "Head of Platform, Northline", initials: "JV" },
        { name: "Ruth Okonjo", role: "SRE Lead, Corvus", initials: "RO" },
        { name: "You", role: "Asking the awkward question", initials: "?" },
      ],
      faq: [
        faq("Will it be recorded?", "Yes — everyone registered gets the recording, whether or not you attend live."),
        faq("Is this a product demo?", "No. Nobody is selling anything, and the speakers do not work for us."),
      ],
      ctaTitle: "Seats are limited to 500",
      ctaBody: "Register once and we will send a calendar invite and the recording afterwards.",
      footerNote: "One email before, one after. That is it.",
    },
  },
  {
    slug: "ebook-download",
    name: "Chapter — Ebook Landing",
    category: "landing-page",
    theme: "linen",
    description: "Lead-magnet landing page for a downloadable guide.",
    tags: ["ebook", "lead", "light", "marketing"],
    layout: ["nav:minimal", "hero:split", "block:steps", "block:testimonials", "block:cta", "block:footer"],
    data: {
      brand: "Chapter",
      nav: [{ label: "Contents", href: "#how" }, { label: "Reviews", href: "#testimonials" }],
      eyebrow: "Free, 68 pages, no email gate on chapter one",
      headline: "The small-business guide to getting paid on time",
      subhead: "Invoicing, chasing, contracts and the three sentences that cut our own late payments by two thirds.",
      ctaPrimary: { label: "Download the guide", href: "#contact" },
      ctaSecondary: { label: "Read chapter one", href: "#how" },
      heroImage: img("ebook-hero", 1000, 1100),
      steps: [
        f("Part one — Before the work", "Terms, deposits and the questions to ask a new client."),
        f("Part two — The invoice", "What to put on it, when to send it, and why the wording matters."),
        f("Part three — When it is late", "A four-stage chase sequence, with the emails written for you."),
      ],
      quotes: [
        q("Used the stage-two email. Paid the next morning.", "Nadia Farrell", "Freelance designer"),
        q("Should be handed out with every business registration.", "Peter Amankwah", "Accountant"),
      ],
      ctaTitle: "Get the guide",
      ctaBody: "PDF and EPUB, no account required, unsubscribe in one click.",
      footerNote: "We will email you twice. Both are about getting paid.",
    },
  },

  /* ────────────────────────────────────────────────────────── restaurant */
  {
    slug: "forno-pizzeria",
    name: "Forno — Pizzeria",
    category: "restaurant",
    theme: "ember",
    description: "Neighbourhood pizzeria with menu, ordering and locations.",
    tags: ["pizza", "restaurant", "dark", "casual"],
    layout: ["nav:simple", "hero:split", "block:menu", "block:stats", "block:gallery", "block:contact", "block:footer"],
    data: {
      brand: "Forno",
      nav: [{ label: "Menu", href: "#menu" }, { label: "Gallery", href: "#work" }, { label: "Find us", href: "#contact" }],
      eyebrow: "48-hour dough",
      headline: "Neapolitan, more or less",
      subhead: "Wood-fired, ninety seconds, slightly charred and not up for negotiation. Two ovens, one recipe.",
      ctaPrimary: { label: "Order for collection", href: "#contact" },
      ctaSecondary: { label: "See the menu", href: "#menu" },
      heroImage: img("pizza-hero", 1000, 1100),
      menu: [
        {
          section: "Pizza",
          items: [
            { name: "Marinara", description: "Tomato, garlic, oregano, olive oil. No cheese, no apology.", price: "9" },
            { name: "Margherita", description: "Fior di latte, basil, tomato.", price: "11" },
            { name: "Diavola", description: "Spicy salami, chilli honey, fior di latte.", price: "14" },
            { name: "Funghi", description: "Mixed mushroom, thyme, taleggio, garlic oil.", price: "14" },
          ],
        },
        {
          section: "Sides and sweet",
          items: [
            { name: "Focaccia", description: "Rosemary and sea salt, from the same dough.", price: "5" },
            { name: "Rocket and parmesan", description: "Lemon, olive oil, too much parmesan.", price: "6" },
            { name: "Tiramisu", description: "Made this morning, gone by nine.", price: "7" },
          ],
        },
      ],
      stats: [
        { value: "90s", label: "In the oven" },
        { value: "48h", label: "Dough ferment" },
        { value: "2", label: "Locations" },
        { value: "430°C", label: "Oven temperature" },
      ],
      gallery: [
        { src: img("pizza-1", 800, 600), caption: "The oven" },
        { src: img("pizza-2", 800, 600), caption: "Friday night" },
        { src: img("pizza-3", 800, 600), caption: "Dough, day two" },
      ],
      contact: { email: "eat@example.com", phone: "+1 (555) 330-7788", address: "12 Kiln Street · 4 Market Row", hours: "Tue — Sun, 5pm to 10pm" },
      footerNote: "Collection only at Kiln Street. No pineapple conversation, please.",
    },
  },
  {
    slug: "cellar-wine-bar",
    name: "Cellar — Wine Bar",
    category: "restaurant",
    theme: "noir",
    description: "Intimate wine bar page with list, small plates and booking.",
    tags: ["wine", "bar", "dark", "intimate"],
    layout: ["nav:centered", "hero:cover", "block:menu", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "CELLAR",
      nav: [{ label: "The list", href: "#menu" }, { label: "Reviews", href: "#testimonials" }, { label: "Book", href: "#contact" }, { label: "About", href: "#menu" }],
      eyebrow: "Twenty-six seats",
      headline: "Small room, long list",
      subhead: "低 intervention wines by the glass, changed weekly, with plates designed to keep you here another hour.",
      ctaPrimary: { label: "Book a table", href: "#contact" },
      ctaSecondary: { label: "See the list", href: "#menu" },
      heroImage: img("winebar-hero", 1800, 1100),
      menu: [
        {
          section: "By the glass",
          items: [
            { name: "Chenin Blanc, Loire", description: "Dry, waxy, faintly saline. 2022.", price: "11" },
            { name: "Gamay, Beaujolais", description: "Chilled, light, dangerous. 2023.", price: "10" },
            { name: "Ribolla Gialla, Friuli", description: "Skin contact, four days. 2021.", price: "13" },
            { name: "Fino, Jerez", description: "Bone dry, served properly cold.", price: "8" },
          ],
        },
        {
          section: "Plates",
          items: [
            { name: "Bread and anchovy butter", description: "The bread is very good. The butter is better.", price: "7" },
            { name: "Cured meats", description: "Three, cut to order.", price: "14" },
            { name: "Grilled leeks, hazelnut", description: "Burnt properly, dressed while warm.", price: "11" },
          ],
        },
      ],
      quotes: [
        q("The list changes enough that I have never had the same glass twice.", "Regular, Tuesdays", "Since 2022"),
        q("Best bar snack in the city, and it is bread.", "The City Guide", "Bars of the year"),
      ],
      contact: { email: "book@example.com", phone: "+1 (555) 909-4400", address: "Basement, 3 Vine Court", hours: "Tue — Sat, 5pm to midnight" },
      footerNote: "Walk-ins welcome at the bar. Tables bookable two weeks ahead.",
    },
  },

  /* ──────────────────────────────────────────────────────── local trades */
  {
    slug: "sharp-barbershop",
    name: "Sharp — Barbershop",
    category: "business",
    theme: "midnight",
    description: "Barbershop page with services, barbers and online booking.",
    tags: ["barber", "grooming", "dark", "local"],
    layout: ["nav:simple", "hero:cover", "block:menu", "block:team", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "SHARP",
      nav: [{ label: "Services", href: "#menu" }, { label: "Barbers", href: "#team" }, { label: "Reviews", href: "#testimonials" }, { label: "Book", href: "#contact" }],
      eyebrow: "Walk-ins before 11am",
      headline: "A proper haircut, on time",
      subhead: "Four chairs, no music you have to shout over, and appointments that start when they say they will.",
      ctaPrimary: { label: "Book online", href: "#contact" },
      ctaSecondary: { label: "See prices", href: "#menu" },
      heroImage: img("barber-hero", 1800, 1100),
      menu: [
        {
          section: "Cuts",
          items: [
            { name: "Haircut", description: "Consultation, cut, wash and finish. 45 minutes.", price: "32" },
            { name: "Skin fade", description: "Clipper work to the skin, blended properly.", price: "36" },
            { name: "Buzz", description: "One length, in and out in fifteen.", price: "18" },
          ],
        },
        {
          section: "Beard and extras",
          items: [
            { name: "Beard trim", description: "Shaped, lined and oiled.", price: "18" },
            { name: "Hot towel shave", description: "Traditional, twice over, thirty minutes.", price: "34" },
            { name: "Cut and beard", description: "Both, together, saving you six.", price: "44" },
          ],
        },
      ],
      team: [
        { name: "Reece", role: "Fades and classic cuts", initials: "R" },
        { name: "Tomasz", role: "Scissor work, beards", initials: "T" },
        { name: "Ade", role: "Textured and curly hair", initials: "A" },
        { name: "Jules", role: "Shaves, apprentice trainer", initials: "J" },
      ],
      quotes: [
        q("Ten years, four barbers, never a bad one.", "Chris Neale", "Customer"),
        q("They actually know what to do with curly hair.", "Femi Adebayo", "Customer"),
      ],
      contact: { email: "book@example.com", phone: "+44 113 555 0104", address: "8 Kirkgate", hours: "Tue — Fri 9am to 7pm · Sat 8am to 5pm" },
      footerNote: "Card and cash. Tips optional and always split.",
    },
  },
  {
    slug: "bright-cleaning",
    name: "Bright — Cleaning Service",
    category: "business",
    theme: "glacier",
    description: "Domestic and commercial cleaning page with plans and instant quote.",
    tags: ["cleaning", "services", "dark", "local"],
    layout: ["nav:simple", "hero:split", "block:featureGrid", "block:pricing", "block:steps", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Bright",
      nav: [{ label: "Services", href: "#features" }, { label: "Prices", href: "#pricing" }, { label: "How it works", href: "#how" }, { label: "Quote", href: "#contact" }],
      eyebrow: "Insured, vetted, same cleaner every time",
      headline: "The same person, every week, who knows where things go",
      subhead: "Domestic and office cleaning with no rotating staff, no lock-in and no awkward conversation about the fee.",
      ctaPrimary: { label: "Get an instant quote", href: "#contact" },
      ctaSecondary: { label: "See prices", href: "#pricing" },
      heroImage: img("cleaning-hero", 1000, 1100),
      features: [
        f("Domestic", "Weekly or fortnightly, keys held securely if you are out.", "heart"),
        f("Office", "Early mornings or evenings, with a checklist you approve.", "layers"),
        f("One-off", "End of tenancy, post-build and spring cleans.", "spark"),
      ],
      plans: [
        { name: "Fortnightly", price: "$62", cadence: "per visit", cta: "Book", features: ["Three hours", "Same cleaner", "Products included"] },
        { name: "Weekly", price: "$55", cadence: "per visit", cta: "Book", featured: true, features: ["Three hours", "Same cleaner", "Products included", "Priority rescheduling"] },
        { name: "One-off deep clean", price: "$220", cadence: "per clean", cta: "Enquire", features: ["Two cleaners", "Six hours", "Inside appliances"] },
      ],
      steps: [
        f("Quote", "Answer four questions online and get a real price, not a range."),
        f("Trial clean", "First visit at half price. No commitment after it."),
        f("Regular slot", "Same day, same time, same person."),
      ],
      quotes: [
        q("Three years, never had to explain anything twice.", "Helen Mbeki", "Customer"),
        q("They rescheduled around our building work without a fuss.", "Owen Price", "Office manager"),
      ],
      contact: { email: "quotes@example.com", phone: "+44 191 555 0166", address: "Serving the city and 15 miles around", hours: "Office Mon — Fri, 8am to 6pm" },
      footerNote: "Fully insured. Staff paid above the living wage.",
    },
  },
  {
    slug: "haul-moving-company",
    name: "Haul — Moving Company",
    category: "business",
    theme: "sandstone",
    description: "Removals company page with services, quotes and moving checklist.",
    tags: ["moving", "removals", "warm", "services"],
    layout: ["nav:simple", "hero:split", "block:stats", "block:steps", "block:featureGrid", "block:faq", "block:contact", "block:footer"],
    data: {
      brand: "Haul",
      nav: [{ label: "Services", href: "#features" }, { label: "How it works", href: "#how" }, { label: "FAQ", href: "#faq" }, { label: "Quote", href: "#contact" }],
      eyebrow: "Free survey, fixed price",
      headline: "Moving day, without the dread",
      subhead: "Packing, loading and putting the bed back together at the other end. Fixed quotes that do not move on the day.",
      ctaPrimary: { label: "Get a fixed quote", href: "#contact" },
      ctaSecondary: { label: "How it works", href: "#how" },
      heroImage: img("moving-hero", 1000, 1100),
      stats: [
        { value: "9,400", label: "Moves completed" },
        { value: "0.2%", label: "Claims rate" },
        { value: "Fixed", label: "Quotes, always" },
        { value: "7 days", label: "A week" },
      ],
      steps: [
        f("Survey", "Video or in person, twenty minutes, and you get the price the same day."),
        f("Pack", "Optional — we bring materials and do it the day before."),
        f("Move", "Loaded, transported, unloaded and reassembled where you want it."),
      ],
      features: [
        f("Full packing", "Including the kitchen, which is the bit everyone underestimates.", "layers"),
        f("Storage", "Containerised, insured, by the week or the year.", "lock"),
        f("Piano and specialist", "Trained crew and the right equipment.", "shield"),
      ],
      faq: [
        faq("Is my stuff insured?", "Yes — goods in transit cover as standard, with higher limits available."),
        faq("What if the completion date slips?", "We hold your slot and reschedule free of charge. It happens constantly."),
      ],
      contact: { email: "quotes@example.com", phone: "+44 1234 555 190", address: "Depot 6, Riverside Industrial Estate", hours: "Mon — Sun, 7am to 8pm" },
      footerNote: "Members of a recognised removals association.",
    },
  },
  {
    slug: "petal-florist",
    name: "Petal — Florist",
    category: "business",
    theme: "blush",
    description: "Florist page with arrangements, subscriptions and local delivery.",
    tags: ["florist", "shop", "light", "local"],
    layout: ["nav:centered", "hero:split", "block:gallery", "block:pricing", "block:steps", "block:contact", "block:footer"],
    data: {
      brand: "Petal",
      nav: [{ label: "Shop", href: "#work" }, { label: "Subscriptions", href: "#pricing" }, { label: "Delivery", href: "#how" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Same-day delivery before 1pm",
      headline: "Flowers that last more than four days",
      subhead: "Seasonal arrangements from British growers where we can, wrapped by hand, delivered by us.",
      ctaPrimary: { label: "Order flowers", href: "#work" },
      ctaSecondary: { label: "See subscriptions", href: "#pricing" },
      heroImage: img("florist-hero", 1000, 1100),
      gallery: [
        { src: img("flower-1", 800, 600), caption: "The Seasonal — from $38" },
        { src: img("flower-2", 800, 600), caption: "The Big One — $85" },
        { src: img("flower-3", 800, 600), caption: "Dried arrangement — $46" },
        { src: img("flower-4", 800, 600), caption: "Table centrepiece — $60" },
        { src: img("flower-5", 800, 600), caption: "Single stems — from $4" },
        { src: img("flower-6", 800, 600), caption: "Plants — from $22" },
      ],
      plans: [
        { name: "Monthly", price: "$42", cadence: "/mo", cta: "Subscribe", features: ["One arrangement a month", "Free delivery", "Pause any time"] },
        { name: "Fortnightly", price: "$74", cadence: "/mo", cta: "Subscribe", featured: true, features: ["Two arrangements a month", "Free delivery", "Vase on your first order"] },
        { name: "Office weekly", price: "$180", cadence: "/mo", cta: "Enquire", features: ["Weekly delivery", "Large arrangement", "Invoiced monthly"] },
      ],
      steps: [
        f("Order by 1pm", "For same-day delivery within the city."),
        f("We deliver", "By hand, by us, with a photo when it arrives."),
        f("They last", "Conditioned properly and cut fresh. Ten days is normal."),
      ],
      contact: { email: "shop@example.com", phone: "+44 1223 555 0130", address: "3 Green Street", hours: "Tue — Sat, 9am to 5:30pm" },
      footerNote: "Compostable wrapping. No floral foam, ever.",
    },
  },

  /* ─────────────────────────────────────────────────────────── saas etc */
  {
    slug: "helpdesk-support",
    name: "Console — Help Desk",
    category: "saas",
    theme: "slate",
    description: "Customer support platform page with channels, automation and pricing.",
    tags: ["support", "helpdesk", "light", "b2b"],
    layout: ["nav:simple", "hero:split", "block:logos", "block:featureGrid", "block:stats", "block:pricing", "block:faq", "block:footer"],
    data: {
      brand: "Console",
      nav: [{ label: "Product", href: "#features" }, { label: "Pricing", href: "#pricing" }, { label: "Customers", href: "#logos" }, { label: "FAQ", href: "#faq" }],
      eyebrow: "Support software",
      headline: "One inbox, every channel, no ticket left unread",
      subhead: "Email, chat and social in a single queue, with automation that routes rather than replies.",
      ctaPrimary: { label: "Start free trial", href: "#pricing" },
      ctaSecondary: { label: "Book a demo", href: "#contact" },
      heroImage: img("helpdesk-hero", 1000, 1100),
      logos: ["Fieldwork", "Northline", "Basalt", "Perigee", "Aurum"],
      features: [
        f("Shared inbox", "Assignment, collision detection and internal notes that stay internal.", "users"),
        f("Smart routing", "Rules on content, customer tier and language — not a black box.", "spark"),
        f("Reporting", "First response, resolution and backlog, by team and by channel.", "chart"),
      ],
      stats: [
        { value: "-42%", label: "Median first response" },
        { value: "18", label: "Channels supported" },
        { value: "6 min", label: "Setup time" },
        { value: "4.8/5", label: "Agent satisfaction" },
      ],
      plans: [
        { name: "Team", price: "$29", cadence: "/agent/mo", cta: "Start trial", features: ["Shared inbox", "Email and chat", "Basic reporting"] },
        { name: "Growth", price: "$59", cadence: "/agent/mo", cta: "Start trial", featured: true, features: ["All channels", "Automation rules", "Full reporting", "API"] },
        { name: "Scale", price: "Custom", cadence: "annual", cta: "Talk to sales", features: ["SSO and audit logs", "Dedicated manager", "SLA"] },
      ],
      faq: [
        faq("Can we migrate our history?", "Yes — importers for the major help desks, including tags and assignments."),
        faq("Do you charge for light agents?", "No. Anyone who only reads or comments internally is free."),
      ],
      footerNote: "No per-ticket pricing. Ever.",
    },
  },
  {
    slug: "postmark-email-marketing",
    name: "Dispatch — Email Marketing",
    category: "saas",
    theme: "ember",
    description: "Email marketing platform page with deliverability focus and pricing.",
    tags: ["email", "marketing", "dark", "saas"],
    layout: ["nav:simple", "hero:centered", "block:stats", "block:featureBento", "block:pricing", "block:testimonials", "block:faq", "block:footer"],
    data: {
      brand: "Dispatch",
      nav: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }, { label: "Customers", href: "#testimonials" }, { label: "FAQ", href: "#faq" }],
      eyebrow: "Deliverability first",
      headline: "Emails that reach the inbox, not the promotions tab",
      subhead: "A sending platform built around reputation — warm-up, authentication and per-domain monitoring, from the first send.",
      ctaPrimary: { label: "Send your first campaign", href: "#pricing" },
      ctaSecondary: { label: "See the features", href: "#features" },
      heroImage: img("email-hero", 1600, 1000),
      stats: [
        { value: "99.2%", label: "Median inbox placement" },
        { value: "1.4s", label: "Median delivery time" },
        { value: "0", label: "Shared IP surprises" },
        { value: "24/7", label: "Deliverability support" },
      ],
      features: [
        f("Automatic warm-up", "New domains ramped over three weeks, monitored daily.", "clock"),
        f("Authentication", "SPF, DKIM and DMARC configured with a guided check.", "shield"),
        f("Visual builder", "Drag, type, send. Or paste your own HTML and MJML.", "layers"),
        f("Segments", "Behaviour-based, recalculated at send time.", "users"),
        f("Real analytics", "Opens with Apple privacy correctly accounted for.", "chart"),
      ],
      plans: [
        { name: "Starter", price: "$19", cadence: "/mo", cta: "Start", features: ["10,000 emails", "Unlimited contacts", "Deliverability checks"] },
        { name: "Growth", price: "$79", cadence: "/mo", cta: "Start", featured: true, features: ["100,000 emails", "Automation", "Dedicated IP option", "A/B testing"] },
        { name: "Scale", price: "$249", cadence: "/mo", cta: "Talk to us", features: ["500,000 emails", "Dedicated IP", "Deliverability review", "SSO"] },
      ],
      quotes: [
        q("Inbox rate went from 71% to 98% in a month.", "Ines Duarte", "Head of CRM, Perigee"),
        q("The warm-up did what three consultants could not.", "Lars Jensen", "Founder, Northline"),
      ],
      faq: [
        faq("Do you charge per contact?", "No. You pay for emails sent, and storing contacts is free."),
        faq("Can we bring our own domain?", "Yes, and we will walk you through the DNS records in about ten minutes."),
      ],
      footerNote: "No open-tracking pixels unless you switch them on.",
    },
  },

  /* ─────────────────────────────────────────────────────────── portfolio */
  {
    slug: "resonance-musician",
    name: "Resonance — Musician",
    category: "portfolio",
    theme: "aurora",
    description: "Musician page with releases, tour dates and booking.",
    tags: ["music", "artist", "dark", "gradient"],
    layout: ["nav:minimal", "hero:cover", "block:gallery", "block:steps", "block:stats", "block:contact", "block:footer"],
    data: {
      brand: "RESONANCE",
      nav: [{ label: "Music", href: "#work" }, { label: "Tour", href: "#how" }, { label: "Booking", href: "#contact" }],
      eyebrow: "New album out now",
      headline: "Nightlines",
      subhead: "Third album. Recorded live over nine days in a converted chapel, with the doors open.",
      ctaPrimary: { label: "Listen now", href: "#work" },
      ctaSecondary: { label: "Tour dates", href: "#how" },
      heroImage: img("music-hero", 1800, 1100),
      gallery: [
        { src: img("album-1", 800, 600), caption: "Nightlines — 2025" },
        { src: img("album-2", 800, 600), caption: "Low Country — 2022" },
        { src: img("album-3", 800, 600), caption: "First Light — 2019" },
      ],
      steps: [
        f("12 April — Berlin", "Silent Green · tickets available"),
        f("15 April — Amsterdam", "Paradiso · sold out"),
        f("19 April — London", "Union Chapel · limited"),
      ],
      stats: [
        { value: "3", label: "Albums" },
        { value: "41", label: "Tour dates" },
        { value: "9 days", label: "To record Nightlines" },
        { value: "1", label: "Take, mostly" },
      ],
      contact: { email: "booking@example.com", phone: "—", address: "Management: Field & Co.", hours: "Press enquiries by email" },
      footerNote: "Vinyl and merchandise shipped from Rotterdam.",
    },
  },
  {
    slug: "typeset-writer",
    name: "Typeset — Writer",
    category: "portfolio",
    theme: "paper",
    description: "Author page with books, essays and speaking enquiries.",
    tags: ["writer", "author", "light", "editorial"],
    layout: ["nav:centered", "hero:editorial", "block:gallery", "block:featureGrid", "block:contact", "block:footer"],
    data: {
      brand: "Helena Marsh",
      nav: [{ label: "Books", href: "#work" }, { label: "Essays", href: "#features" }, { label: "Speaking", href: "#contact" }, { label: "About", href: "#features" }],
      eyebrow: "Writer and essayist",
      headline: "Books about how things get made",
      subhead: "Three books on industry, labour and the people who keep complicated systems running.",
      ctaPrimary: { label: "Read an extract", href: "#work" },
      heroImage: img("writer-hero", 900, 1200),
      gallery: [
        { src: img("book-1", 800, 600), caption: "The Long Shift — 2024" },
        { src: img("book-2", 800, 600), caption: "Salt and Iron — 2021" },
        { src: img("book-3", 800, 600), caption: "Nobody's Machine — 2018" },
      ],
      features: [
        f("Essays", "Longer pieces for magazines, collected here as they are published.", "code"),
        f("Speaking", "Festivals, universities and the occasional trade conference.", "users"),
        f("Teaching", "A short course on reported non-fiction, twice a year.", "star"),
      ],
      contact: { email: "hello@example.com", phone: "—", address: "Represented by Field Literary", hours: "Speaking enquiries via my agent" },
      footerNote: "Newsletter roughly monthly. No advertising in it.",
    },
  },

  /* ────────────────────────────────────────────────── creative & commerce */
  {
    slug: "reel-film-studio",
    name: "Reel — Film Studio",
    category: "creative",
    theme: "midnight",
    description: "Production company page with showreel, services and clients.",
    tags: ["film", "production", "dark", "studio"],
    layout: ["nav:minimal", "hero:cover", "block:gallery", "block:featureGrid", "block:logos", "block:contact", "block:footer"],
    data: {
      brand: "REEL",
      nav: [{ label: "Work", href: "#work" }, { label: "Services", href: "#features" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Production company",
      headline: "Films that hold attention past the first ten seconds",
      subhead: "Brand films, documentary and commercial work, made by a small crew that shoots and edits in the same building.",
      ctaPrimary: { label: "Watch the reel", href: "#work" },
      ctaSecondary: { label: "Start a project", href: "#contact" },
      heroImage: img("film-hero", 1800, 1100),
      gallery: [
        { src: img("film-1", 800, 600), caption: "Northline — brand film" },
        { src: img("film-2", 800, 600), caption: "Salt Road — documentary short" },
        { src: img("film-3", 800, 600), caption: "Perigee — product launch" },
        { src: img("film-4", 800, 600), caption: "Fieldwork — recruitment" },
        { src: img("film-5", 800, 600), caption: "Aurum — six-part series" },
        { src: img("film-6", 800, 600), caption: "Corvus — event film" },
      ],
      features: [
        f("Direction", "Concept, script and the shoot itself.", "camera"),
        f("Post", "Edit, grade and sound in house, so revisions take hours not weeks.", "layers"),
        f("Motion", "Titles, graphics and animation built to match the footage.", "spark"),
      ],
      logos: ["Northline", "Perigee", "Fieldwork", "Aurum", "Corvus"],
      contact: { email: "hello@example.com", phone: "+44 141 555 0121", address: "Studio 2, The Bonded Warehouse", hours: "Mon — Fri, 9am to 6pm" },
      footerNote: "Crew paid on standard rates. No unpaid runners.",
    },
  },
  {
    slug: "roast-coffee-subscription",
    name: "Roast — Coffee Subscription",
    category: "ecommerce",
    theme: "sandstone",
    description: "Coffee subscription store with plans, origins and delivery.",
    tags: ["coffee", "subscription", "warm", "shop"],
    layout: ["nav:simple", "hero:split", "block:steps", "block:pricing", "block:gallery", "block:faq", "block:cta", "block:footer"],
    data: {
      brand: "Roast",
      nav: [{ label: "How it works", href: "#how" }, { label: "Plans", href: "#pricing" }, { label: "Coffees", href: "#work" }, { label: "FAQ", href: "#faq" }],
      eyebrow: "Roasted Monday, posted Tuesday",
      headline: "Coffee that arrives while it is still worth drinking",
      subhead: "Single origins roasted to order and sent the next morning. Pause, skip or change grind whenever you like.",
      ctaPrimary: { label: "Start a subscription", href: "#pricing" },
      ctaSecondary: { label: "See this month's coffees", href: "#work" },
      heroImage: img("coffee-hero", 1000, 1100),
      steps: [
        f("Pick a plan", "How much, how often, and whole bean or ground for your brewer."),
        f("We roast", "Every Monday, to order. Nothing sits in a warehouse."),
        f("It arrives", "Through the letterbox, usually Wednesday."),
      ],
      plans: [
        { name: "One bag", price: "$14", cadence: "/mo", cta: "Subscribe", features: ["250g a month", "Free delivery", "Pause any time"] },
        { name: "Two bags", price: "$25", cadence: "/mo", cta: "Subscribe", featured: true, features: ["500g a month", "Free delivery", "Two different origins", "Pause any time"] },
        { name: "Office", price: "$96", cadence: "/mo", cta: "Enquire", features: ["2kg a month", "Invoiced", "Brewing guide session"] },
      ],
      gallery: [
        { src: img("coffee-1", 800, 600), caption: "Kenya, Nyeri — blackcurrant, cane sugar" },
        { src: img("coffee-2", 800, 600), caption: "Colombia, Huila — cocoa, orange" },
        { src: img("coffee-3", 800, 600), caption: "Ethiopia, Guji — peach, jasmine" },
      ],
      faq: [
        faq("Can I skip a month?", "Yes, from your account, up to the Sunday before roasting."),
        faq("Do you pay farmers properly?", "We publish what we paid per kilo for every lot, alongside the market price."),
      ],
      ctaTitle: "First bag half price",
      ctaBody: "Cancel after one delivery if it is not for you.",
      footerNote: "Compostable bags. Prices published per lot.",
    },
  },
  {
    slug: "atlas-robotics",
    name: "Atlas — Robotics",
    category: "technology",
    theme: "glacier",
    description: "Industrial robotics page with capabilities, deployments and specs.",
    tags: ["robotics", "industrial", "dark", "hardware"],
    layout: ["nav:simple", "hero:split", "block:logos", "block:stats", "block:featureBento", "block:steps", "block:faq", "block:footer"],
    data: {
      brand: "Atlas Robotics",
      nav: [{ label: "Platform", href: "#features" }, { label: "Deployments", href: "#how" }, { label: "Specs", href: "#faq" }, { label: "Contact", href: "#contact" }],
      eyebrow: "Warehouse automation",
      headline: "Robots that work the aisles you already have",
      subhead: "No re-racking, no floor markings, no six-month integration. It maps your building and starts moving stock.",
      ctaPrimary: { label: "Book a site assessment", href: "#contact" },
      ctaSecondary: { label: "Read the specs", href: "#faq" },
      heroImage: img("robotics-hero", 1000, 1100),
      logos: ["Northline", "Basalt", "Kestrel", "Ridgeway"],
      stats: [
        { value: "3 wks", label: "Median time to production" },
        { value: "1,400", label: "Picks per unit per shift" },
        { value: "0", label: "Floor modifications" },
        { value: "18 hrs", label: "Runtime per charge" },
      ],
      features: [
        f("Self-mapping", "Drive it once around the building and it builds its own map.", "globe"),
        f("Works with people", "Certified for shared aisles with staff and forklifts.", "shield"),
        f("Fleet control", "One dashboard for one unit or ninety.", "layers"),
        f("Open integration", "REST and MQTT into your existing warehouse system.", "code"),
        f("Serviceable", "Field-replaceable batteries, wheels and sensors.", "bolt"),
      ],
      steps: [
        f("Assessment", "One day on site. You get a throughput model, not a brochure."),
        f("Pilot", "Two units, four weeks, measured against your current numbers."),
        f("Scale", "Add units as demand grows. Same software, no re-commissioning."),
      ],
      faq: [
        faq("What is the payload?", "120 kg per unit, with a tow variant rated to 600 kg."),
        faq("What happens in a power cut?", "Units park safely and resume automatically. No manual recovery."),
      ],
      footerNote: "Manufactured in the EU. Two-year warranty, parts available for ten.",
    },
  },
  {
    slug: "keynote-speaker",
    name: "Keynote — Speaker",
    category: "personal",
    theme: "cobalt",
    description: "Professional speaker page with talks, video and booking.",
    tags: ["speaker", "personal", "dark", "professional"],
    layout: ["nav:simple", "hero:split", "block:stats", "block:featureGrid", "block:logos", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Dr. Ada Mensah",
      nav: [{ label: "Talks", href: "#features" }, { label: "Clients", href: "#logos" }, { label: "Reviews", href: "#testimonials" }, { label: "Book", href: "#contact" }],
      eyebrow: "Keynote speaker · Systems and reliability",
      headline: "Talks that survive the flight home",
      subhead: "Forty-five minutes on complexity, failure and why organisations keep rebuilding the same broken thing.",
      ctaPrimary: { label: "Check availability", href: "#contact" },
      ctaSecondary: { label: "See the talks", href: "#features" },
      heroImage: img("speaker-hero", 1000, 1100),
      stats: [
        { value: "180+", label: "Talks delivered" },
        { value: "26", label: "Countries" },
        { value: "4.9/5", label: "Average rating" },
        { value: "2", label: "Books published" },
      ],
      features: [
        f("The Cost of Complexity", "Why the second system is always worse, and what to do instead. 45 min.", "layers"),
        f("Failing Well", "Incident culture, blamelessness and the limits of both. 40 min.", "shield"),
        f("Workshop", "Half day, hands-on, capped at thirty people.", "users"),
      ],
      logos: ["Assembly", "Northline", "Perigee", "Corvus", "Aurum"],
      quotes: [
        q("The only keynote our engineers quoted back to us for months.", "Grace Miller", "Conference chair"),
        q("She rewrote the talk for our industry. Nobody does that.", "Devin Park", "Head of Engineering"),
      ],
      contact: { email: "speaking@example.com", phone: "—", address: "Travelling from Accra and Berlin", hours: "Booking two quarters ahead" },
      footerNote: "Fee reduced or waived for non-profits and community events.",
    },
  },
  {
    slug: "signal-pr-agency",
    name: "Amplify — PR Agency",
    category: "agency",
    theme: "porcelain",
    description: "Communications agency page with services, results and press coverage.",
    tags: ["pr", "communications", "light", "agency"],
    layout: ["nav:simple", "hero:stacked", "block:logos", "block:featureGrid", "block:stats", "block:testimonials", "block:contact", "block:footer"],
    data: {
      brand: "Amplify",
      nav: [{ label: "Services", href: "#features" }, { label: "Results", href: "#stats" }, { label: "Clients", href: "#testimonials" }, { label: "Contact", href: "#contact" }],
      headline: "Coverage that a journalist actually wanted to write",
      subhead: "Communications for technical companies — the ones whose story takes more than a paragraph to explain.",
      ctaPrimary: { label: "Start a conversation", href: "#contact" },
      ctaSecondary: { label: "See our services", href: "#features" },
      heroImage: img("pr-hero", 1600, 900),
      logos: ["The Standard", "Trade Weekly", "Sector", "Broadsheet", "The Wire"],
      features: [
        f("Media relations", "Real relationships, not a spreadsheet of 4,000 addresses.", "users"),
        f("Positioning", "The sentence your founder can say on a podcast without wincing.", "spark"),
        f("Crisis", "On call, with a plan written before you need it.", "shield"),
      ],
      stats: [
        { value: "310", label: "Placements last year" },
        { value: "11", label: "Front pages" },
        { value: "72%", label: "Pitch-to-coverage rate" },
        { value: "0", label: "Press releases sent blind" },
      ],
      quotes: [
        q("They killed three of our ideas and got the fourth on the front page.", "Nina Farrow", "Founder, Kite"),
        q("The first agency that read the technical documentation.", "Ravi Menon", "CTO, Basalt"),
      ],
      contact: { email: "new@example.com", phone: "+44 20 7946 0199", address: "Third floor, 8 Rivington Street", hours: "Mon — Fri, 9am to 6pm" },
      footerNote: "Retainers from three months. No twelve-month minimums.",
    },
  },
];
