import type { Theme } from "./themes";
import { googleFonts, SYSTEM_SANS } from "./theme-kit";

/**
 * Art directions for the kinetic collection.
 *
 * Three rules separate these from the original presets, and they are the whole
 * point of the collection:
 *
 *  1. One dominant saturated colour, used at full strength. Not a palette of
 *     five tints politely sharing the page — a single colour that decides what
 *     the site is, against near-black or an off-white paper.
 *  2. A typeface with an opinion. Anton, Bebas, Fraunces, Bodoni, Syne —
 *     never Inter, Roboto or Arial, which are the defaults everything already
 *     looks like.
 *  3. No glow. `texture` never uses the blurred wash the original presets lean
 *     on; grain, grid and flat fields only.
 */

const K = (t: Theme): Theme => t;

export const KINETIC_THEMES: Record<string, Theme> = {
  /* ───────────────────────────────────────────── vermilion on carbon */
  detonate: K({
    id: "detonate",
    scheme: "dark",
    bg: "#0A0A0A",
    bgAlt: "#121212",
    surface: "#151515",
    border: "#282828",
    ink: "#FFFFFF",
    inkMuted: "#A3A3A3",
    accent: "#FF3B00",
    accentInk: "#0A0A0A",
    accentSoft: "rgba(255,59,0,0.14)",
    headingFont: `'Anton', ${SYSTEM_SANS}`,
    bodyFont: `'Space Grotesk', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "-0.02em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1240px",
    sectionPad: "128px",
    fontsHref: googleFonts("Anton", "Space Grotesk:wght@400;500;700"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ───────────────────────────────────────────────── acid on graphite */
  voltage: K({
    id: "voltage",
    scheme: "dark",
    bg: "#0B0C08",
    bgAlt: "#131509",
    surface: "#16180F",
    border: "#2A2E1B",
    ink: "#F4FFE0",
    inkMuted: "#9AA382",
    accent: "#C8FF00",
    accentInk: "#0B0C08",
    accentSoft: "rgba(200,255,0,0.13)",
    headingFont: `'Archivo Black', ${SYSTEM_SANS}`,
    bodyFont: `'Archivo', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "-0.035em",
    radius: "2px",
    radiusLg: "4px",
    shadow: "none",
    maxWidth: "1200px",
    sectionPad: "120px",
    fontsHref: googleFonts("Archivo Black", "Archivo:wght@400;500;600"),
    texture: "grid",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ──────────────────────────────────────────────── klein blue on bone */
  yves: K({
    id: "yves",
    scheme: "light",
    bg: "#F4F1EA",
    bgAlt: "#EAE6DC",
    surface: "#FFFFFF",
    border: "#D6D1C4",
    ink: "#0E1116",
    inkMuted: "#585349",
    accent: "#002FA7",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(0,47,167,0.10)",
    headingFont: `'Bodoni Moda', Georgia, serif`,
    bodyFont: `'Work Sans', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.02em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1160px",
    sectionPad: "132px",
    fontsHref: googleFonts("Bodoni Moda:opsz,wght@6..96,600;6..96,700", "Work Sans:wght@400;500;600"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ─────────────────────────────────────────────── magenta on obsidian */
  siren: K({
    id: "siren",
    scheme: "dark",
    bg: "#0D0A0C",
    bgAlt: "#151016",
    surface: "#191219",
    border: "#33202E",
    ink: "#FFF2F8",
    inkMuted: "#A88E9C",
    accent: "#FF0059",
    accentInk: "#0D0A0C",
    accentSoft: "rgba(255,0,89,0.14)",
    headingFont: `'Syne', ${SYSTEM_SANS}`,
    bodyFont: `'Space Grotesk', ${SYSTEM_SANS}`,
    headingWeight: 800,
    headingSpacing: "-0.03em",
    radius: "0px",
    radiusLg: "2px",
    shadow: "none",
    maxWidth: "1220px",
    sectionPad: "124px",
    fontsHref: googleFonts("Syne:wght@600;700;800", "Space Grotesk:wght@400;500;700"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ─────────────────────────────────────────────── safety yellow, hard */
  hazard: K({
    id: "hazard",
    scheme: "dark",
    bg: "#111111",
    bgAlt: "#1A1A18",
    surface: "#1C1C1A",
    border: "#333330",
    ink: "#FFFDF2",
    inkMuted: "#A5A398",
    accent: "#FFE500",
    accentInk: "#111111",
    accentSoft: "rgba(255,229,0,0.13)",
    headingFont: `'Big Shoulders Display', ${SYSTEM_SANS}`,
    bodyFont: `'IBM Plex Sans', ${SYSTEM_SANS}`,
    headingWeight: 800,
    headingSpacing: "0em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1260px",
    sectionPad: "116px",
    fontsHref: googleFonts("Big Shoulders Display:wght@700;800;900", "IBM Plex Sans:wght@400;500;600"),
    texture: "grid",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ───────────────────────────────────────────────── cyan on deep navy */
  beacon: K({
    id: "beacon",
    scheme: "dark",
    bg: "#04070A",
    bgAlt: "#081119",
    surface: "#0A141C",
    border: "#16303F",
    ink: "#EAF9FF",
    inkMuted: "#7C97A5",
    accent: "#00E5FF",
    accentInk: "#04070A",
    accentSoft: "rgba(0,229,255,0.13)",
    headingFont: `'Space Mono', ui-monospace, monospace`,
    bodyFont: `'Space Grotesk', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.04em",
    radius: "2px",
    radiusLg: "2px",
    shadow: "none",
    maxWidth: "1180px",
    sectionPad: "118px",
    fontsHref: googleFonts("Space Mono:wght@400;700", "Space Grotesk:wght@400;500;700"),
    texture: "grid",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ─────────────────────────────────────────── blood orange on newsprint */
  press: K({
    id: "press",
    scheme: "light",
    bg: "#FFF8F0",
    bgAlt: "#F6EADC",
    surface: "#FFFFFF",
    border: "#E0CDB8",
    ink: "#171310",
    inkMuted: "#655A50",
    accent: "#C93A0C",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(201,58,12,0.14)",
    headingFont: `'Abril Fatface', Georgia, serif`,
    bodyFont: `'Cabin', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "-0.01em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1140px",
    sectionPad: "126px",
    fontsHref: googleFonts("Abril Fatface", "Cabin:wght@400;500;600"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: false,
  }),

  /* ───────────────────────────────────────────────── pine on warm paper */
  thicket: K({
    id: "thicket",
    scheme: "light",
    bg: "#F2F0E6",
    bgAlt: "#E6E3D5",
    surface: "#FFFFFF",
    border: "#CFCBB8",
    ink: "#101A14",
    inkMuted: "#4F5C53",
    accent: "#0B6E4F",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(11,110,79,0.10)",
    headingFont: `'Fraunces', Georgia, serif`,
    bodyFont: `'Public Sans', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.025em",
    radius: "3px",
    radiusLg: "6px",
    shadow: "none",
    maxWidth: "1120px",
    sectionPad: "128px",
    fontsHref: googleFonts("Fraunces:opsz,wght@9..144,600;9..144,700", "Public Sans:wght@400;500;600"),
    texture: "none",
    buttonShape: "rounded",
    uppercaseNav: false,
  }),

  /* ──────────────────────────────────────────────── signal red on black */
  alarm: K({
    id: "alarm",
    scheme: "dark",
    bg: "#0A0A0A",
    bgAlt: "#141212",
    surface: "#161313",
    border: "#2E2626",
    ink: "#FFFFFF",
    inkMuted: "#9E9494",
    accent: "#FF0A00",
    accentInk: "#0A0A0A",
    accentSoft: "rgba(255,10,0,0.14)",
    headingFont: `'Bebas Neue', ${SYSTEM_SANS}`,
    bodyFont: `'Work Sans', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "0.01em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1240px",
    sectionPad: "120px",
    fontsHref: googleFonts("Bebas Neue", "Work Sans:wght@400;500;600"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ─────────────────────────────────────────── terracotta on clay paper */
  kiln: K({
    id: "kiln",
    scheme: "light",
    bg: "#FBF3E4",
    bgAlt: "#F0E4CF",
    surface: "#FFFFFF",
    border: "#DCC8AA",
    ink: "#1C140D",
    inkMuted: "#6B5A48",
    accent: "#C1440E",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(193,68,14,0.10)",
    headingFont: `'Yeseva One', Georgia, serif`,
    bodyFont: `'Mulish', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "-0.01em",
    radius: "4px",
    radiusLg: "10px",
    shadow: "none",
    maxWidth: "1120px",
    sectionPad: "124px",
    fontsHref: googleFonts("Yeseva One", "Mulish:wght@400;500;700"),
    texture: "none",
    buttonShape: "rounded",
    uppercaseNav: false,
  }),

  /* ───────────────────────────────────────────────── cobalt on hard white */
  ultramarine: K({
    id: "ultramarine",
    scheme: "light",
    bg: "#FFFFFF",
    bgAlt: "#F0F2F8",
    surface: "#FFFFFF",
    border: "#D3D8E6",
    ink: "#080B14",
    inkMuted: "#4C5468",
    accent: "#0033FF",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(0,51,255,0.09)",
    headingFont: `'Unbounded', ${SYSTEM_SANS}`,
    bodyFont: `'Karla', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.04em",
    radius: "0px",
    radiusLg: "2px",
    shadow: "none",
    maxWidth: "1200px",
    sectionPad: "122px",
    fontsHref: googleFonts("Unbounded:wght@600;700;800", "Karla:wght@400;500;700"),
    texture: "grid",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ──────────────────────────────────────────────── mustard on charcoal */
  brass: K({
    id: "brass",
    scheme: "dark",
    bg: "#131210",
    bgAlt: "#1C1A16",
    surface: "#1E1C18",
    border: "#37332B",
    ink: "#FBF6EA",
    inkMuted: "#A39B88",
    accent: "#E0A800",
    accentInk: "#131210",
    accentSoft: "rgba(224,168,0,0.13)",
    headingFont: `'Zilla Slab', Georgia, serif`,
    bodyFont: `'Public Sans', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.015em",
    radius: "2px",
    radiusLg: "4px",
    shadow: "none",
    maxWidth: "1160px",
    sectionPad: "120px",
    fontsHref: googleFonts("Zilla Slab:wght@500;600;700", "Public Sans:wght@400;500;600"),
    texture: "noise",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ───────────────────────────────────────────────── coral on off-black */
  flare: K({
    id: "flare",
    scheme: "dark",
    bg: "#0C0B0B",
    bgAlt: "#161312",
    surface: "#181514",
    border: "#302927",
    ink: "#FFF4F1",
    inkMuted: "#A6968F",
    accent: "#FF5A36",
    accentInk: "#0C0B0B",
    accentSoft: "rgba(255,90,54,0.14)",
    headingFont: `'Bricolage Grotesque', ${SYSTEM_SANS}`,
    bodyFont: `'Figtree', ${SYSTEM_SANS}`,
    headingWeight: 800,
    headingSpacing: "-0.035em",
    radius: "6px",
    radiusLg: "16px",
    shadow: "none",
    maxWidth: "1180px",
    sectionPad: "118px",
    fontsHref: googleFonts(
      "Bricolage Grotesque:opsz,wght@12..96,700;12..96,800",
      "Figtree:wght@400;500;700",
    ),
    texture: "dots",
    buttonShape: "rounded",
    uppercaseNav: false,
  }),

  /* ─────────────────────────────────────────────── oxblood on bone white */
  cellar: K({
    id: "cellar",
    scheme: "light",
    bg: "#F7F4F1",
    bgAlt: "#EBE4DF",
    surface: "#FFFFFF",
    border: "#D8CDC6",
    ink: "#140C0E",
    inkMuted: "#5E4E51",
    accent: "#6B0F1A",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(107,15,26,0.09)",
    headingFont: `'Playfair Display', Georgia, serif`,
    bodyFont: `'Karla', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.02em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1100px",
    sectionPad: "130px",
    fontsHref: googleFonts("Playfair Display:wght@600;700;800", "Karla:wght@400;500;700"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ────────────────────────────────────────────── teal on near-black ink */
  lagoon: K({
    id: "lagoon",
    scheme: "dark",
    bg: "#07100F",
    bgAlt: "#0C1A18",
    surface: "#0E1D1B",
    border: "#1C3733",
    ink: "#E8FFFB",
    inkMuted: "#7E9B96",
    accent: "#00C2A8",
    accentInk: "#07100F",
    accentSoft: "rgba(0,194,168,0.13)",
    headingFont: `'Chivo', ${SYSTEM_SANS}`,
    bodyFont: `'Chivo', ${SYSTEM_SANS}`,
    headingWeight: 900,
    headingSpacing: "-0.04em",
    radius: "2px",
    radiusLg: "4px",
    shadow: "none",
    maxWidth: "1200px",
    sectionPad: "120px",
    fontsHref: googleFonts("Chivo:wght@400;500;700;900"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ────────────────────────────────────────────── ink black on hot white */
  newsprint: K({
    id: "newsprint",
    scheme: "light",
    bg: "#FFFFFF",
    bgAlt: "#F2F2F2",
    surface: "#FFFFFF",
    border: "#111111",
    ink: "#000000",
    inkMuted: "#4A4A4A",
    accent: "#000000",
    accentInk: "#FFFFFF",
    accentSoft: "rgba(0,0,0,0.07)",
    headingFont: `'Instrument Serif', Georgia, serif`,
    bodyFont: `'Space Grotesk', ${SYSTEM_SANS}`,
    headingWeight: 400,
    headingSpacing: "-0.03em",
    radius: "0px",
    radiusLg: "0px",
    shadow: "none",
    maxWidth: "1160px",
    sectionPad: "128px",
    fontsHref: googleFonts("Instrument Serif:ital@0;1", "Space Grotesk:wght@400;500;700"),
    texture: "none",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ───────────────────────────────────────────── terminal green, utilitarian */
  console: K({
    id: "console",
    scheme: "dark",
    bg: "#080A08",
    bgAlt: "#0E120E",
    surface: "#101410",
    border: "#1E2A1E",
    ink: "#DFF5DF",
    inkMuted: "#7C907C",
    accent: "#3DF07A",
    accentInk: "#080A08",
    accentSoft: "rgba(61,240,122,0.12)",
    headingFont: `'JetBrains Mono', ui-monospace, monospace`,
    bodyFont: `'IBM Plex Sans', ${SYSTEM_SANS}`,
    headingWeight: 700,
    headingSpacing: "-0.03em",
    radius: "2px",
    radiusLg: "2px",
    shadow: "none",
    maxWidth: "1140px",
    sectionPad: "112px",
    fontsHref: googleFonts("JetBrains Mono:wght@400;700", "IBM Plex Sans:wght@400;500;600"),
    texture: "grid",
    buttonShape: "square",
    uppercaseNav: true,
  }),

  /* ──────────────────────────────────────────────── violet-free electric blue */
  cadet: K({
    id: "cadet",
    scheme: "dark",
    bg: "#080B12",
    bgAlt: "#0E141F",
    surface: "#101724",
    border: "#1E2A3D",
    ink: "#EDF3FF",
    inkMuted: "#8593AB",
    accent: "#4C86FF",
    accentInk: "#080B12",
    accentSoft: "rgba(76,134,255,0.14)",
    headingFont: `'Sora', ${SYSTEM_SANS}`,
    bodyFont: `'Hanken Grotesk', ${SYSTEM_SANS}`,
    headingWeight: 800,
    headingSpacing: "-0.04em",
    radius: "4px",
    radiusLg: "12px",
    shadow: "none",
    maxWidth: "1200px",
    sectionPad: "118px",
    fontsHref: googleFonts("Sora:wght@600;700;800", "Hanken Grotesk:wght@400;500;700"),
    texture: "dots",
    buttonShape: "rounded",
    uppercaseNav: false,
  }),
};
