/**
 * Compiles /templates into src/generated so the running app never touches the
 * filesystem.
 *
 *   npm run templates:index
 *
 * Vercel's serverless functions do not ship the repo's working tree, and
 * `public/` lives on the CDN rather than in the function. Baking the bundled
 * templates into a module removes that whole class of "works locally, 404s in
 * production" problem. Imported libraries at scale go to Blob storage instead.
 */

import fs from "node:fs";
import path from "node:path";

const TEMPLATES_DIR = path.resolve(process.cwd(), "templates");
const OUT_DIR = path.resolve(process.cwd(), "src/generated");

const TEXT_EXTENSIONS = new Set(["html", "htm", "css", "js", "mjs", "json", "svg", "txt", "md", "xml", "webmanifest"]);

type Meta = Record<string, unknown> & { slug: string };
type Bundle = { meta: Meta; files: Record<string, string> };

function collect(dir: string, prefix = ""): Record<string, string> {
  const out: Record<string, string> = {};
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      Object.assign(out, collect(full, rel));
      continue;
    }
    if (rel === "template.json") continue;

    const ext = entry.name.split(".").pop()?.toLowerCase() ?? "";
    if (!TEXT_EXTENSIONS.has(ext)) {
      console.warn(`  skipping binary asset ${rel} — host it remotely or upload via admin`);
      continue;
    }
    out[rel] = fs.readFileSync(full, "utf8");
  }
  return out;
}

function main() {
  if (!fs.existsSync(TEMPLATES_DIR)) {
    console.warn("No /templates directory — writing an empty index.");
    emit({});
    return;
  }

  const bundles: Record<string, Bundle> = {};

  for (const entry of fs.readdirSync(TEMPLATES_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith("_") || entry.name.startsWith(".")) continue;

    const dir = path.join(TEMPLATES_DIR, entry.name);
    const manifestPath = path.join(dir, "template.json");
    if (!fs.existsSync(manifestPath)) {
      console.warn(`  ${entry.name}: no template.json, skipped`);
      continue;
    }

    const meta = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as Meta;
    const files = collect(dir);

    const entryFile = String(meta.entryFile ?? "index.html");
    if (!files[entryFile]) {
      console.warn(`  ${entry.name}: entry file "${entryFile}" missing, skipped`);
      continue;
    }

    bundles[entry.name] = { meta: { ...meta, slug: meta.slug ?? entry.name }, files };
  }

  emit(bundles);
}

function emit(bundles: Record<string, Bundle>) {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const json = JSON.stringify(bundles);
  fs.writeFileSync(path.join(OUT_DIR, "templates.json"), json, "utf8");

  fs.writeFileSync(
    path.join(OUT_DIR, "templates.ts"),
    `// AUTO-GENERATED by scripts/build-template-index.ts — do not edit by hand.
import data from "./templates.json";

export type BundledTemplateMeta = {
  name: string;
  slug: string;
  category: string;
  tags: string[];
  description: string;
  theme?: string;
  colorScheme?: "dark" | "light" | "colorful";
  tier?: "FREE" | "PRO";
  featured?: boolean;
  entryFile: string;
  pages: string[];
  thumbnail?: string;
  license: string;
  author?: string;
  source?: string;
  attribution?: string | null;
  responsive?: boolean;
};

export type BundledTemplate = {
  meta: BundledTemplateMeta;
  /** path -> file contents */
  files: Record<string, string>;
};

export const bundledTemplates = data as unknown as Record<string, BundledTemplate>;
export const bundledTemplateCount = Object.keys(bundledTemplates).length;
`,
    "utf8",
  );

  const count = Object.keys(bundles).length;
  const bytes = json.length;
  console.log(
    `Indexed ${count} bundled templates (${(bytes / 1024 / 1024).toFixed(2)} MB) into src/generated/templates.json`,
  );
}

main();
